/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5-dev at Fri Aug 26 15:56:55 2022. */

#ifndef PB_WIPPERSNAPPER_PWM_V1_WIPPERSNAPPER_PWM_V1_PWM_PB_H_INCLUDED
#define PB_WIPPERSNAPPER_PWM_V1_WIPPERSNAPPER_PWM_V1_PWM_PB_H_INCLUDED
#include <pb.h>
#include "nanopb/nanopb.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _wippersnapper_pwm_v1_Deinit {
    char pin[6];
} wippersnapper_pwm_v1_Deinit;

typedef struct _wippersnapper_pwm_v1_WriteDutyCycle {
    char pin[6];
    int32_t frequency;
    int32_t duty_cycle;
    int32_t resolution;
} wippersnapper_pwm_v1_WriteDutyCycle;

typedef struct _wippersnapper_pwm_v1_WriteFrequency {
    char pin[6];
    int32_t frequency;
} wippersnapper_pwm_v1_WriteFrequency;

typedef struct _wippersnapper_pwm_v1_WriteDutyCycleMulti {
    pb_size_t write_duty_cycle_count;
    wippersnapper_pwm_v1_WriteDutyCycle write_duty_cycle[4];
} wippersnapper_pwm_v1_WriteDutyCycleMulti;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define wippersnapper_pwm_v1_WriteDutyCycle_init_default {"", 0, 0, 0}
#define wippersnapper_pwm_v1_WriteDutyCycleMulti_init_default {0, {wippersnapper_pwm_v1_WriteDutyCycle_init_default, wippersnapper_pwm_v1_WriteDutyCycle_init_default, wippersnapper_pwm_v1_WriteDutyCycle_init_default, wippersnapper_pwm_v1_WriteDutyCycle_init_default}}
#define wippersnapper_pwm_v1_WriteFrequency_init_default {"", 0}
#define wippersnapper_pwm_v1_Deinit_init_default {""}
#define wippersnapper_pwm_v1_WriteDutyCycle_init_zero {"", 0, 0, 0}
#define wippersnapper_pwm_v1_WriteDutyCycleMulti_init_zero {0, {wippersnapper_pwm_v1_WriteDutyCycle_init_zero, wippersnapper_pwm_v1_WriteDutyCycle_init_zero, wippersnapper_pwm_v1_WriteDutyCycle_init_zero, wippersnapper_pwm_v1_WriteDutyCycle_init_zero}}
#define wippersnapper_pwm_v1_WriteFrequency_init_zero {"", 0}
#define wippersnapper_pwm_v1_Deinit_init_zero    {""}

/* Field tags (for use in manual encoding/decoding) */
#define wippersnapper_pwm_v1_Deinit_pin_tag      1
#define wippersnapper_pwm_v1_WriteDutyCycle_pin_tag 1
#define wippersnapper_pwm_v1_WriteDutyCycle_frequency_tag 2
#define wippersnapper_pwm_v1_WriteDutyCycle_duty_cycle_tag 3
#define wippersnapper_pwm_v1_WriteDutyCycle_resolution_tag 4
#define wippersnapper_pwm_v1_WriteFrequency_pin_tag 1
#define wippersnapper_pwm_v1_WriteFrequency_frequency_tag 2
#define wippersnapper_pwm_v1_WriteDutyCycleMulti_write_duty_cycle_tag 1

/* Struct field encoding specification for nanopb */
#define wippersnapper_pwm_v1_WriteDutyCycle_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin,               1) \
X(a, STATIC,   SINGULAR, INT32,    frequency,         2) \
X(a, STATIC,   SINGULAR, INT32,    duty_cycle,        3) \
X(a, STATIC,   SINGULAR, INT32,    resolution,        4)
#define wippersnapper_pwm_v1_WriteDutyCycle_CALLBACK NULL
#define wippersnapper_pwm_v1_WriteDutyCycle_DEFAULT NULL

#define wippersnapper_pwm_v1_WriteDutyCycleMulti_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  write_duty_cycle,   1)
#define wippersnapper_pwm_v1_WriteDutyCycleMulti_CALLBACK NULL
#define wippersnapper_pwm_v1_WriteDutyCycleMulti_DEFAULT NULL
#define wippersnapper_pwm_v1_WriteDutyCycleMulti_write_duty_cycle_MSGTYPE wippersnapper_pwm_v1_WriteDutyCycle

#define wippersnapper_pwm_v1_WriteFrequency_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin,               1) \
X(a, STATIC,   SINGULAR, INT32,    frequency,         2)
#define wippersnapper_pwm_v1_WriteFrequency_CALLBACK NULL
#define wippersnapper_pwm_v1_WriteFrequency_DEFAULT NULL

#define wippersnapper_pwm_v1_Deinit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin,               1)
#define wippersnapper_pwm_v1_Deinit_CALLBACK NULL
#define wippersnapper_pwm_v1_Deinit_DEFAULT NULL

extern const pb_msgdesc_t wippersnapper_pwm_v1_WriteDutyCycle_msg;
extern const pb_msgdesc_t wippersnapper_pwm_v1_WriteDutyCycleMulti_msg;
extern const pb_msgdesc_t wippersnapper_pwm_v1_WriteFrequency_msg;
extern const pb_msgdesc_t wippersnapper_pwm_v1_Deinit_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define wippersnapper_pwm_v1_WriteDutyCycle_fields &wippersnapper_pwm_v1_WriteDutyCycle_msg
#define wippersnapper_pwm_v1_WriteDutyCycleMulti_fields &wippersnapper_pwm_v1_WriteDutyCycleMulti_msg
#define wippersnapper_pwm_v1_WriteFrequency_fields &wippersnapper_pwm_v1_WriteFrequency_msg
#define wippersnapper_pwm_v1_Deinit_fields &wippersnapper_pwm_v1_Deinit_msg

/* Maximum encoded size of messages (where known) */
#define wippersnapper_pwm_v1_WriteDutyCycle_size 40
#define wippersnapper_pwm_v1_WriteDutyCycleMulti_size 168
#define wippersnapper_pwm_v1_WriteFrequency_size 18
#define wippersnapper_pwm_v1_Deinit_size         7

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
