/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev at Thu Sep  1 20:52:19 2022. */

#include "wippersnapper/pwm/v1/pwm.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_pwm_v1_AttachRequest, wippersnapper_pwm_v1_AttachRequest, AUTO)


PB_BIND(wippersnapper_pwm_v1_AttachResponse, wippersnapper_pwm_v1_AttachResponse, AUTO)


PB_BIND(wippersnapper_pwm_v1_DetachRequest, wippersnapper_pwm_v1_DetachRequest, AUTO)


PB_BIND(wippersnapper_pwm_v1_WriteDutyCycleRequest, wippersnapper_pwm_v1_WriteDutyCycleRequest, AUTO)


PB_BIND(wippersnapper_pwm_v1_WriteDutyCycleMultiRequest, wippersnapper_pwm_v1_WriteDutyCycleMultiRequest, AUTO)


PB_BIND(wippersnapper_pwm_v1_WriteFrequencyRequest, wippersnapper_pwm_v1_WriteFrequencyRequest, AUTO)



