/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Tue Aug 20 16:38:43 2024. */

#include "checkin.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_checkin_CheckinRequest, wippersnapper_checkin_CheckinRequest, AUTO)


PB_BIND(wippersnapper_checkin_CheckinResponse, wippersnapper_checkin_CheckinResponse, AUTO)




