/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev at Wed Oct 12 12:31:27 2022. */

#include "wippersnapper/pin/v1/pin.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_pin_v1_ConfigurePinRequests, wippersnapper_pin_v1_ConfigurePinRequests, AUTO)


PB_BIND(wippersnapper_pin_v1_ConfigurePinRequest, wippersnapper_pin_v1_ConfigurePinRequest, AUTO)


PB_BIND(wippersnapper_pin_v1_PinEvent, wippersnapper_pin_v1_PinEvent, AUTO)


PB_BIND(wippersnapper_pin_v1_ConfigureReferenceVoltage, wippersnapper_pin_v1_ConfigureReferenceVoltage, AUTO)


PB_BIND(wippersnapper_pin_v1_PinEvents, wippersnapper_pin_v1_PinEvents, AUTO)


PB_BIND(wippersnapper_pin_v1_ConfigurePWMPinRequest, wippersnapper_pin_v1_ConfigurePWMPinRequest, AUTO)


PB_BIND(wippersnapper_pin_v1_ConfigurePWMPinRequests, wippersnapper_pin_v1_ConfigurePWMPinRequests, AUTO)


PB_BIND(wippersnapper_pin_v1_PWMPinEvent, wippersnapper_pin_v1_PWMPinEvent, AUTO)


PB_BIND(wippersnapper_pin_v1_PWMPinEvents, wippersnapper_pin_v1_PWMPinEvents, AUTO)








