/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 at Thu Jul 28 12:28:13 2022. */

#ifndef PB_WIPPERSNAPPER_SERVO_V1_WIPPERSNAPPER_SERVO_V1_SERVO_PB_H_INCLUDED
#define PB_WIPPERSNAPPER_SERVO_V1_WIPPERSNAPPER_SERVO_V1_SERVO_PB_H_INCLUDED
#include <pb.h>
#include "nanopb/nanopb.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* *
 ServoAttachReq represents a request to attach a servo to a pin. */
typedef struct _wippersnapper_servo_v1_ServoAttachReq { 
    char servo_pin[6]; /* * The name of pin to attach a servo to. */
    int32_t servo_freq; /* * The overall PWM frequency, default sent by Adafruit IO is 50Hz. * */
    int32_t min_pulse_width; /* * The minimum pulse length in uS. Default sent by Adafruit IO is 500uS. * */
    int32_t max_pulse_width; /* * The maximum pulse length in uS. Default sent by Adafruit IO is 2500uS. * */
} wippersnapper_servo_v1_ServoAttachReq;

/* *
 ServoAttachResp represents the result of attaching a servo to a pin. */
typedef struct _wippersnapper_servo_v1_ServoAttachResp { 
    bool attach_success; /* * True if a servo was attached successfully, False otherwise. * */
} wippersnapper_servo_v1_ServoAttachResp;

/* *
 ServoDetachReq represents request to detach a servo from a pin and de-initialize the pin for other uses. */
typedef struct _wippersnapper_servo_v1_ServoDetachReq { 
    char servo_pin[5]; /* * The name of pin to use as a servo pin. */
} wippersnapper_servo_v1_ServoDetachReq;

/* *
 ServoWriteReq represents a message to write the servo's position.

 NOTE: Position is sent from Adafruit IO as a pulse width in uS between 500uS
 and 2500uS. The client application must convert pulse width to duty cycle w/fixed
 freq of 50Hz prior to writing to the servo pin. */
typedef struct _wippersnapper_servo_v1_ServoWriteReq { 
    char servo_pin[5]; /* * The name of pin we're addressing. */
    int32_t pulse_width; /* * The pulse width to write to the servo, in uS * */
} wippersnapper_servo_v1_ServoWriteReq;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define wippersnapper_servo_v1_ServoAttachReq_init_default {"", 0, 0, 0}
#define wippersnapper_servo_v1_ServoAttachResp_init_default {0}
#define wippersnapper_servo_v1_ServoDetachReq_init_default {""}
#define wippersnapper_servo_v1_ServoWriteReq_init_default {"", 0}
#define wippersnapper_servo_v1_ServoAttachReq_init_zero {"", 0, 0, 0}
#define wippersnapper_servo_v1_ServoAttachResp_init_zero {0}
#define wippersnapper_servo_v1_ServoDetachReq_init_zero {""}
#define wippersnapper_servo_v1_ServoWriteReq_init_zero {"", 0}

/* Field tags (for use in manual encoding/decoding) */
#define wippersnapper_servo_v1_ServoAttachReq_servo_pin_tag 1
#define wippersnapper_servo_v1_ServoAttachReq_servo_freq_tag 2
#define wippersnapper_servo_v1_ServoAttachReq_min_pulse_width_tag 3
#define wippersnapper_servo_v1_ServoAttachReq_max_pulse_width_tag 4
#define wippersnapper_servo_v1_ServoAttachResp_attach_success_tag 1
#define wippersnapper_servo_v1_ServoDetachReq_servo_pin_tag 1
#define wippersnapper_servo_v1_ServoWriteReq_servo_pin_tag 1
#define wippersnapper_servo_v1_ServoWriteReq_pulse_width_tag 2

/* Struct field encoding specification for nanopb */
#define wippersnapper_servo_v1_ServoAttachReq_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   servo_pin,         1) \
X(a, STATIC,   SINGULAR, INT32,    servo_freq,        2) \
X(a, STATIC,   SINGULAR, INT32,    min_pulse_width,   3) \
X(a, STATIC,   SINGULAR, INT32,    max_pulse_width,   4)
#define wippersnapper_servo_v1_ServoAttachReq_CALLBACK NULL
#define wippersnapper_servo_v1_ServoAttachReq_DEFAULT NULL

#define wippersnapper_servo_v1_ServoAttachResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     attach_success,    1)
#define wippersnapper_servo_v1_ServoAttachResp_CALLBACK NULL
#define wippersnapper_servo_v1_ServoAttachResp_DEFAULT NULL

#define wippersnapper_servo_v1_ServoDetachReq_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   servo_pin,         1)
#define wippersnapper_servo_v1_ServoDetachReq_CALLBACK NULL
#define wippersnapper_servo_v1_ServoDetachReq_DEFAULT NULL

#define wippersnapper_servo_v1_ServoWriteReq_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   servo_pin,         1) \
X(a, STATIC,   SINGULAR, INT32,    pulse_width,       2)
#define wippersnapper_servo_v1_ServoWriteReq_CALLBACK NULL
#define wippersnapper_servo_v1_ServoWriteReq_DEFAULT NULL

extern const pb_msgdesc_t wippersnapper_servo_v1_ServoAttachReq_msg;
extern const pb_msgdesc_t wippersnapper_servo_v1_ServoAttachResp_msg;
extern const pb_msgdesc_t wippersnapper_servo_v1_ServoDetachReq_msg;
extern const pb_msgdesc_t wippersnapper_servo_v1_ServoWriteReq_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define wippersnapper_servo_v1_ServoAttachReq_fields &wippersnapper_servo_v1_ServoAttachReq_msg
#define wippersnapper_servo_v1_ServoAttachResp_fields &wippersnapper_servo_v1_ServoAttachResp_msg
#define wippersnapper_servo_v1_ServoDetachReq_fields &wippersnapper_servo_v1_ServoDetachReq_msg
#define wippersnapper_servo_v1_ServoWriteReq_fields &wippersnapper_servo_v1_ServoWriteReq_msg

/* Maximum encoded size of messages (where known) */
#define wippersnapper_servo_v1_ServoAttachReq_size 40
#define wippersnapper_servo_v1_ServoAttachResp_size 2
#define wippersnapper_servo_v1_ServoDetachReq_size 6
#define wippersnapper_servo_v1_ServoWriteReq_size 17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
