/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev at Wed Oct 12 12:31:27 2022. */

#include "wippersnapper/servo/v1/servo.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_servo_v1_ServoAttachRequest, wippersnapper_servo_v1_ServoAttachRequest, AUTO)


PB_BIND(wippersnapper_servo_v1_ServoAttachResponse, wippersnapper_servo_v1_ServoAttachResponse, AUTO)


PB_BIND(wippersnapper_servo_v1_ServoDetachRequest, wippersnapper_servo_v1_ServoDetachRequest, AUTO)


PB_BIND(wippersnapper_servo_v1_ServoWriteRequest, wippersnapper_servo_v1_ServoWriteRequest, AUTO)



