/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev at Thu Jul 15 15:07:04 2021. */

#include "wippersnapper/sensor/v1/sensor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_sensor_v1_AttachOrUpdateSensorRequest, wippersnapper_sensor_v1_AttachOrUpdateSensorRequest, AUTO)


PB_BIND(wippersnapper_sensor_v1_AttachOrUpdateSensorRequests, wippersnapper_sensor_v1_AttachOrUpdateSensorRequests, AUTO)


PB_BIND(wippersnapper_sensor_v1_AttachOrUpdateSensorResponse, wippersnapper_sensor_v1_AttachOrUpdateSensorResponse, AUTO)


PB_BIND(wippersnapper_sensor_v1_DetachSensorRequest, wippersnapper_sensor_v1_DetachSensorRequest, AUTO)


PB_BIND(wippersnapper_sensor_v1_DetachSensorResponse, wippersnapper_sensor_v1_DetachSensorResponse, AUTO)


PB_BIND(wippersnapper_sensor_v1_SensorEventRequest, wippersnapper_sensor_v1_SensorEventRequest, AUTO)


PB_BIND(wippersnapper_sensor_v1_SensorEventRequest_SensorVect, wippersnapper_sensor_v1_SensorEventRequest_SensorVect, AUTO)


PB_BIND(wippersnapper_sensor_v1_SensorEventRequest_SensorColor, wippersnapper_sensor_v1_SensorEventRequest_SensorColor, AUTO)


PB_BIND(wippersnapper_sensor_v1_SensorEventRequests, wippersnapper_sensor_v1_SensorEventRequests, AUTO)





