/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev at Wed Oct 12 12:31:27 2022. */

#include "wippersnapper/i2c/v1/i2c.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_i2c_v1_I2CBusInitRequest, wippersnapper_i2c_v1_I2CBusInitRequest, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CBusInitResponse, wippersnapper_i2c_v1_I2CBusInitResponse, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CBusSetFrequency, wippersnapper_i2c_v1_I2CBusSetFrequency, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CBusScanRequest, wippersnapper_i2c_v1_I2CBusScanRequest, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CBusScanResponse, wippersnapper_i2c_v1_I2CBusScanResponse, 2)


PB_BIND(wippersnapper_i2c_v1_I2CDeviceSensorProperties, wippersnapper_i2c_v1_I2CDeviceSensorProperties, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CDeviceInitRequests, wippersnapper_i2c_v1_I2CDeviceInitRequests, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CDeviceInitRequest, wippersnapper_i2c_v1_I2CDeviceInitRequest, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CDeviceInitResponse, wippersnapper_i2c_v1_I2CDeviceInitResponse, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CDeviceUpdateRequest, wippersnapper_i2c_v1_I2CDeviceUpdateRequest, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CDeviceUpdateResponse, wippersnapper_i2c_v1_I2CDeviceUpdateResponse, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CDeviceDeinitRequest, wippersnapper_i2c_v1_I2CDeviceDeinitRequest, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CDeviceDeinitResponse, wippersnapper_i2c_v1_I2CDeviceDeinitResponse, AUTO)


PB_BIND(wippersnapper_i2c_v1_SensorEvent, wippersnapper_i2c_v1_SensorEvent, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CDeviceEvent, wippersnapper_i2c_v1_I2CDeviceEvent, AUTO)





