/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev at Tue Aug  3 20:36:10 2021. */

#include "wippersnapper/i2c/v1/i2c.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_i2c_v1_I2CInitRequest, wippersnapper_i2c_v1_I2CInitRequest, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CInitResponse, wippersnapper_i2c_v1_I2CInitResponse, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CSetFrequency, wippersnapper_i2c_v1_I2CSetFrequency, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CScanRequest, wippersnapper_i2c_v1_I2CScanRequest, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CScanResponse, wippersnapper_i2c_v1_I2CScanResponse, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CDeviceInitRequest, wippersnapper_i2c_v1_I2CDeviceInitRequest, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CDeviceInitResponse, wippersnapper_i2c_v1_I2CDeviceInitResponse, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CDeviceDeinitRequest, wippersnapper_i2c_v1_I2CDeviceDeinitRequest, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CDeviceDeinitResponse, wippersnapper_i2c_v1_I2CDeviceDeinitResponse, AUTO)


PB_BIND(wippersnapper_i2c_v1_AHTInitRequest, wippersnapper_i2c_v1_AHTInitRequest, AUTO)


PB_BIND(wippersnapper_i2c_v1_AHTDeinitRequest, wippersnapper_i2c_v1_AHTDeinitRequest, AUTO)


PB_BIND(wippersnapper_i2c_v1_DPS310InitRequest, wippersnapper_i2c_v1_DPS310InitRequest, AUTO)


PB_BIND(wippersnapper_i2c_v1_SHT4XInitRequest, wippersnapper_i2c_v1_SHT4XInitRequest, AUTO)


PB_BIND(wippersnapper_i2c_v1_SCD30InitRequest, wippersnapper_i2c_v1_SCD30InitRequest, AUTO)


PB_BIND(wippersnapper_i2c_v1_SCD30ReadEvent, wippersnapper_i2c_v1_SCD30ReadEvent, AUTO)


PB_BIND(wippersnapper_i2c_v1_BH1750InitRequest, wippersnapper_i2c_v1_BH1750InitRequest, AUTO)


PB_BIND(wippersnapper_i2c_v1_BH1750ReadEvent, wippersnapper_i2c_v1_BH1750ReadEvent, AUTO)


PB_BIND(wippersnapper_i2c_v1_SensorDetails, wippersnapper_i2c_v1_SensorDetails, AUTO)


PB_BIND(wippersnapper_i2c_v1_SensorEvent, wippersnapper_i2c_v1_SensorEvent, AUTO)


PB_BIND(wippersnapper_i2c_v1_I2CSensorEvent, wippersnapper_i2c_v1_I2CSensorEvent, AUTO)






