/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev at Wed Oct 12 12:31:27 2022. */

#include "wippersnapper/ds18x20/v1/ds18x20.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_ds18x20_v1_Ds18x20InitRequest, wippersnapper_ds18x20_v1_Ds18x20InitRequest, AUTO)


PB_BIND(wippersnapper_ds18x20_v1_Ds18x20InitResponse, wippersnapper_ds18x20_v1_Ds18x20InitResponse, AUTO)


PB_BIND(wippersnapper_ds18x20_v1_Ds18x20DeInitRequest, wippersnapper_ds18x20_v1_Ds18x20DeInitRequest, AUTO)


PB_BIND(wippersnapper_ds18x20_v1_Ds18x20DeviceEvent, wippersnapper_ds18x20_v1_Ds18x20DeviceEvent, AUTO)



