/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev at Fri Nov 11 15:41:43 2022. */

#include "wippersnapper/pixels/v1/pixels.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_pixels_v1_PixelsCreateRequest, wippersnapper_pixels_v1_PixelsCreateRequest, AUTO)


PB_BIND(wippersnapper_pixels_v1_PixelsCreateResponse, wippersnapper_pixels_v1_PixelsCreateResponse, AUTO)


PB_BIND(wippersnapper_pixels_v1_PixelsDeleteRequest, wippersnapper_pixels_v1_PixelsDeleteRequest, AUTO)


PB_BIND(wippersnapper_pixels_v1_PixelsWriteRequest, wippersnapper_pixels_v1_PixelsWriteRequest, AUTO)





