/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5-dev at Tue Jul 25 20:36:13 2023. */

#ifndef PB_WIPPERSNAPPER_UART_V1_WIPPERSNAPPER_UART_V1_UART_PB_H_INCLUDED
#define PB_WIPPERSNAPPER_UART_V1_WIPPERSNAPPER_UART_V1_UART_PB_H_INCLUDED
#include <pb.h>
#include "nanopb/nanopb.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _wippersnapper_uart_v1_UARTBusData {
    int32_t baudrate;
    pb_callback_t pin_rx;
    pb_callback_t pin_tx;
    bool is_invert;
    bool is_software_uart;
} wippersnapper_uart_v1_UARTBusData;

typedef struct _wippersnapper_uart_v1_UARTDeviceAttachResponse {
    pb_callback_t device_id;
    bool is_success;
} wippersnapper_uart_v1_UARTDeviceAttachResponse;

typedef struct _wippersnapper_uart_v1_UARTDeviceAttachRequest {
    bool has_bus_info;
    wippersnapper_uart_v1_UARTBusData bus_info;
    pb_callback_t device_id;
    int32_t polling_interval;
} wippersnapper_uart_v1_UARTDeviceAttachRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define wippersnapper_uart_v1_UARTBusData_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define wippersnapper_uart_v1_UARTDeviceAttachRequest_init_default {false, wippersnapper_uart_v1_UARTBusData_init_default, {{NULL}, NULL}, 0}
#define wippersnapper_uart_v1_UARTDeviceAttachResponse_init_default {{{NULL}, NULL}, 0}
#define wippersnapper_uart_v1_UARTBusData_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define wippersnapper_uart_v1_UARTDeviceAttachRequest_init_zero {false, wippersnapper_uart_v1_UARTBusData_init_zero, {{NULL}, NULL}, 0}
#define wippersnapper_uart_v1_UARTDeviceAttachResponse_init_zero {{{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define wippersnapper_uart_v1_UARTBusData_baudrate_tag 1
#define wippersnapper_uart_v1_UARTBusData_pin_rx_tag 2
#define wippersnapper_uart_v1_UARTBusData_pin_tx_tag 3
#define wippersnapper_uart_v1_UARTBusData_is_invert_tag 4
#define wippersnapper_uart_v1_UARTBusData_is_software_uart_tag 5
#define wippersnapper_uart_v1_UARTDeviceAttachResponse_device_id_tag 1
#define wippersnapper_uart_v1_UARTDeviceAttachResponse_is_success_tag 2
#define wippersnapper_uart_v1_UARTDeviceAttachRequest_bus_info_tag 1
#define wippersnapper_uart_v1_UARTDeviceAttachRequest_device_id_tag 2
#define wippersnapper_uart_v1_UARTDeviceAttachRequest_polling_interval_tag 3

/* Struct field encoding specification for nanopb */
#define wippersnapper_uart_v1_UARTBusData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    baudrate,          1) \
X(a, CALLBACK, SINGULAR, STRING,   pin_rx,            2) \
X(a, CALLBACK, SINGULAR, STRING,   pin_tx,            3) \
X(a, STATIC,   SINGULAR, BOOL,     is_invert,         4) \
X(a, STATIC,   SINGULAR, BOOL,     is_software_uart,   5)
#define wippersnapper_uart_v1_UARTBusData_CALLBACK pb_default_field_callback
#define wippersnapper_uart_v1_UARTBusData_DEFAULT NULL

#define wippersnapper_uart_v1_UARTDeviceAttachRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bus_info,          1) \
X(a, CALLBACK, SINGULAR, STRING,   device_id,         2) \
X(a, STATIC,   SINGULAR, INT32,    polling_interval,   3)
#define wippersnapper_uart_v1_UARTDeviceAttachRequest_CALLBACK pb_default_field_callback
#define wippersnapper_uart_v1_UARTDeviceAttachRequest_DEFAULT NULL
#define wippersnapper_uart_v1_UARTDeviceAttachRequest_bus_info_MSGTYPE wippersnapper_uart_v1_UARTBusData

#define wippersnapper_uart_v1_UARTDeviceAttachResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, BOOL,     is_success,        2)
#define wippersnapper_uart_v1_UARTDeviceAttachResponse_CALLBACK pb_default_field_callback
#define wippersnapper_uart_v1_UARTDeviceAttachResponse_DEFAULT NULL

extern const pb_msgdesc_t wippersnapper_uart_v1_UARTBusData_msg;
extern const pb_msgdesc_t wippersnapper_uart_v1_UARTDeviceAttachRequest_msg;
extern const pb_msgdesc_t wippersnapper_uart_v1_UARTDeviceAttachResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define wippersnapper_uart_v1_UARTBusData_fields &wippersnapper_uart_v1_UARTBusData_msg
#define wippersnapper_uart_v1_UARTDeviceAttachRequest_fields &wippersnapper_uart_v1_UARTDeviceAttachRequest_msg
#define wippersnapper_uart_v1_UARTDeviceAttachResponse_fields &wippersnapper_uart_v1_UARTDeviceAttachResponse_msg

/* Maximum encoded size of messages (where known) */
/* wippersnapper_uart_v1_UARTBusData_size depends on runtime parameters */
/* wippersnapper_uart_v1_UARTDeviceAttachRequest_size depends on runtime parameters */
/* wippersnapper_uart_v1_UARTDeviceAttachResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
