/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "analogio.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_analogio_AnalogIOAdd, wippersnapper_analogio_AnalogIOAdd, AUTO)


PB_BIND(wippersnapper_analogio_AnalogIORemove, wippersnapper_analogio_AnalogIORemove, AUTO)


PB_BIND(wippersnapper_analogio_AnalogIOEvent, wippersnapper_analogio_AnalogIOEvent, AUTO)



