/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Fri Dec 19 19:36:01 2025. */

#include "analogio.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_analogio_B2D, ws_analogio_B2D, AUTO)


PB_BIND(ws_analogio_D2B, ws_analogio_D2B, AUTO)


PB_BIND(ws_analogio_Add, ws_analogio_Add, AUTO)


PB_BIND(ws_analogio_Remove, ws_analogio_Remove, AUTO)


PB_BIND(ws_analogio_Event, ws_analogio_Event, AUTO)



