/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Fri Dec 19 19:36:01 2025. */

#include "checkin.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_checkin_B2D, ws_checkin_B2D, AUTO)


PB_BIND(ws_checkin_D2B, ws_checkin_D2B, AUTO)


PB_BIND(ws_checkin_Request, ws_checkin_Request, AUTO)


PB_BIND(ws_checkin_Response, ws_checkin_Response, AUTO)


PB_BIND(ws_checkin_ComponentAdd, ws_checkin_ComponentAdd, 2)


PB_BIND(ws_checkin_Complete, ws_checkin_Complete, AUTO)




