/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 at Wed Mar 18 14:59:25 2026. */

#ifndef PB_WS_CHECKIN_CHECKIN_PB_H_INCLUDED
#define PB_WS_CHECKIN_CHECKIN_PB_H_INCLUDED
#include <pb.h>
#include "analogio.pb.h"
#include "digitalio.pb.h"
#include "ds18x20.pb.h"
#include "i2c.pb.h"
#include "pixels.pb.h"
#include "pwm.pb.h"
#include "servo.pb.h"
#include "sleep.pb.h"
#include "uart.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* *
 Response. Specifies if the hardware definiton is within the database. */
typedef enum _ws_checkin_Response_Response {
    ws_checkin_Response_Response_R_UNSPECIFIED = 0, /* * Invalid response from server */
    ws_checkin_Response_Response_R_OK = 1, /* * Board found within definition index */
    ws_checkin_Response_Response_R_BOARD_NOT_FOUND = 2 /* * Board not found in definition index */
} ws_checkin_Response_Response;

/* Struct definitions */
/* *
 Request notifies the MQTT broker that a new/existing device is requesting to connect. */
typedef struct _ws_checkin_Request {
    char hardware_uid[64]; /* * Identifies the client's physical hardware (board name + last 3 of NIC's MAC address). */
    char firmware_version[25]; /* * Identifies the client's firmware version. */
} ws_checkin_Request;

/* *
 Generic component add message, could contain any *Add message from component protos */
typedef struct _ws_checkin_ComponentAdds {
    pb_callback_t digitalio_adds;
    pb_callback_t analogio_adds;
    pb_callback_t servo_adds;
    pb_callback_t pwm_adds;
    pb_callback_t pixels_adds;
    pb_callback_t ds18x20_adds;
    pb_callback_t uart_adds;
    pb_callback_t i2c_adds;
} ws_checkin_ComponentAdds;

/* *
 Response sends a broker response to the client's Request. */
typedef struct _ws_checkin_Response {
    ws_checkin_Response_Response response; /* * Specifies if the hardware definition exists on the server. */
    int32_t total_gpio_pins; /* * Specifies the number of GPIO pins on the device. */
    int32_t total_analog_pins; /* * Specifies the number of analog pins on the device. */
    float reference_voltage; /* * Specifies the hardware's default reference voltage. */
    bool has_component_adds;
    ws_checkin_ComponentAdds component_adds; /* * A list of components to set up and initialize during checkin */
    bool sleep_enabled; /* * Whether sleep is enabled or not, ignore config if not */
    bool has_sleep_config;
    ws_sleep_SleepConfig sleep_config; /* * Sleep configuration for the device */
} ws_checkin_Response;

/* *
 BrokerToDevice message envelope */
typedef struct _ws_checkin_B2D {
    pb_callback_t cb_payload;
    pb_size_t which_payload;
    union {
        ws_checkin_Response response;
    } payload;
} ws_checkin_B2D;

/* *
 Signal to the broker that the device has completed the checkin
 routine and is now operating normally */
typedef struct _ws_checkin_Complete {
    char dummy_field;
} ws_checkin_Complete;

/* *
 DeviceToBroker message envelope */
typedef struct _ws_checkin_D2B {
    pb_size_t which_payload;
    union {
        ws_checkin_Request request;
        ws_checkin_Complete complete;
    } payload;
} ws_checkin_D2B;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ws_checkin_Response_Response_MIN ws_checkin_Response_Response_R_UNSPECIFIED
#define _ws_checkin_Response_Response_MAX ws_checkin_Response_Response_R_BOARD_NOT_FOUND
#define _ws_checkin_Response_Response_ARRAYSIZE ((ws_checkin_Response_Response)(ws_checkin_Response_Response_R_BOARD_NOT_FOUND+1))




#define ws_checkin_Response_response_ENUMTYPE ws_checkin_Response_Response




/* Initializer values for message structs */
#define ws_checkin_B2D_init_default              {{{NULL}, NULL}, 0, {ws_checkin_Response_init_default}}
#define ws_checkin_D2B_init_default              {0, {ws_checkin_Request_init_default}}
#define ws_checkin_Request_init_default          {"", ""}
#define ws_checkin_Response_init_default         {_ws_checkin_Response_Response_MIN, 0, 0, 0, false, ws_checkin_ComponentAdds_init_default, 0, false, ws_sleep_SleepConfig_init_default}
#define ws_checkin_ComponentAdds_init_default    {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define ws_checkin_Complete_init_default         {0}
#define ws_checkin_B2D_init_zero                 {{{NULL}, NULL}, 0, {ws_checkin_Response_init_zero}}
#define ws_checkin_D2B_init_zero                 {0, {ws_checkin_Request_init_zero}}
#define ws_checkin_Request_init_zero             {"", ""}
#define ws_checkin_Response_init_zero            {_ws_checkin_Response_Response_MIN, 0, 0, 0, false, ws_checkin_ComponentAdds_init_zero, 0, false, ws_sleep_SleepConfig_init_zero}
#define ws_checkin_ComponentAdds_init_zero       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define ws_checkin_Complete_init_zero            {0}

/* Field tags (for use in manual encoding/decoding) */
#define ws_checkin_Request_hardware_uid_tag      1
#define ws_checkin_Request_firmware_version_tag  2
#define ws_checkin_ComponentAdds_digitalio_adds_tag 1
#define ws_checkin_ComponentAdds_analogio_adds_tag 2
#define ws_checkin_ComponentAdds_servo_adds_tag  3
#define ws_checkin_ComponentAdds_pwm_adds_tag    4
#define ws_checkin_ComponentAdds_pixels_adds_tag 5
#define ws_checkin_ComponentAdds_ds18x20_adds_tag 6
#define ws_checkin_ComponentAdds_uart_adds_tag   7
#define ws_checkin_ComponentAdds_i2c_adds_tag    8
#define ws_checkin_Response_response_tag         1
#define ws_checkin_Response_total_gpio_pins_tag  2
#define ws_checkin_Response_total_analog_pins_tag 3
#define ws_checkin_Response_reference_voltage_tag 4
#define ws_checkin_Response_component_adds_tag   5
#define ws_checkin_Response_sleep_enabled_tag    6
#define ws_checkin_Response_sleep_config_tag     7
#define ws_checkin_B2D_response_tag              1
#define ws_checkin_D2B_request_tag               1
#define ws_checkin_D2B_complete_tag              2

/* Struct field encoding specification for nanopb */
#define ws_checkin_B2D_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,response,payload.response),   1)
#define ws_checkin_B2D_CALLBACK NULL
#define ws_checkin_B2D_DEFAULT NULL
#define ws_checkin_B2D_payload_response_MSGTYPE ws_checkin_Response

#define ws_checkin_D2B_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,request,payload.request),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,complete,payload.complete),   2)
#define ws_checkin_D2B_CALLBACK NULL
#define ws_checkin_D2B_DEFAULT NULL
#define ws_checkin_D2B_payload_request_MSGTYPE ws_checkin_Request
#define ws_checkin_D2B_payload_complete_MSGTYPE ws_checkin_Complete

#define ws_checkin_Request_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   hardware_uid,      1) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   2)
#define ws_checkin_Request_CALLBACK NULL
#define ws_checkin_Request_DEFAULT NULL

#define ws_checkin_Response_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    response,          1) \
X(a, STATIC,   SINGULAR, INT32,    total_gpio_pins,   2) \
X(a, STATIC,   SINGULAR, INT32,    total_analog_pins,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    reference_voltage,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  component_adds,    5) \
X(a, STATIC,   SINGULAR, BOOL,     sleep_enabled,     6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sleep_config,      7)
#define ws_checkin_Response_CALLBACK NULL
#define ws_checkin_Response_DEFAULT NULL
#define ws_checkin_Response_component_adds_MSGTYPE ws_checkin_ComponentAdds
#define ws_checkin_Response_sleep_config_MSGTYPE ws_sleep_SleepConfig

#define ws_checkin_ComponentAdds_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  digitalio_adds,    1) \
X(a, CALLBACK, REPEATED, MESSAGE,  analogio_adds,     2) \
X(a, CALLBACK, REPEATED, MESSAGE,  servo_adds,        3) \
X(a, CALLBACK, REPEATED, MESSAGE,  pwm_adds,          4) \
X(a, CALLBACK, REPEATED, MESSAGE,  pixels_adds,       5) \
X(a, CALLBACK, REPEATED, MESSAGE,  ds18x20_adds,      6) \
X(a, CALLBACK, REPEATED, MESSAGE,  uart_adds,         7) \
X(a, CALLBACK, REPEATED, MESSAGE,  i2c_adds,          8)
#define ws_checkin_ComponentAdds_CALLBACK pb_default_field_callback
#define ws_checkin_ComponentAdds_DEFAULT NULL
#define ws_checkin_ComponentAdds_digitalio_adds_MSGTYPE ws_digitalio_Add
#define ws_checkin_ComponentAdds_analogio_adds_MSGTYPE ws_analogio_Add
#define ws_checkin_ComponentAdds_servo_adds_MSGTYPE ws_servo_Add
#define ws_checkin_ComponentAdds_pwm_adds_MSGTYPE ws_pwm_Add
#define ws_checkin_ComponentAdds_pixels_adds_MSGTYPE ws_pixels_Add
#define ws_checkin_ComponentAdds_ds18x20_adds_MSGTYPE ws_ds18x20_Add
#define ws_checkin_ComponentAdds_uart_adds_MSGTYPE ws_uart_Add
#define ws_checkin_ComponentAdds_i2c_adds_MSGTYPE ws_i2c_DeviceAddOrReplace

#define ws_checkin_Complete_FIELDLIST(X, a) \

#define ws_checkin_Complete_CALLBACK NULL
#define ws_checkin_Complete_DEFAULT NULL

extern const pb_msgdesc_t ws_checkin_B2D_msg;
extern const pb_msgdesc_t ws_checkin_D2B_msg;
extern const pb_msgdesc_t ws_checkin_Request_msg;
extern const pb_msgdesc_t ws_checkin_Response_msg;
extern const pb_msgdesc_t ws_checkin_ComponentAdds_msg;
extern const pb_msgdesc_t ws_checkin_Complete_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ws_checkin_B2D_fields &ws_checkin_B2D_msg
#define ws_checkin_D2B_fields &ws_checkin_D2B_msg
#define ws_checkin_Request_fields &ws_checkin_Request_msg
#define ws_checkin_Response_fields &ws_checkin_Response_msg
#define ws_checkin_ComponentAdds_fields &ws_checkin_ComponentAdds_msg
#define ws_checkin_Complete_fields &ws_checkin_Complete_msg

/* Maximum encoded size of messages (where known) */
/* ws_checkin_B2D_size depends on runtime parameters */
/* ws_checkin_Response_size depends on runtime parameters */
/* ws_checkin_ComponentAdds_size depends on runtime parameters */
#define WS_CHECKIN_CHECKIN_PB_H_MAX_SIZE         ws_checkin_D2B_size
#define ws_checkin_Complete_size                 0
#define ws_checkin_D2B_size                      93
#define ws_checkin_Request_size                  91

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
