/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 at Wed May 27 15:48:49 2026. */

#ifndef PB_WS_CONFIG_CONFIG_PB_H_INCLUDED
#define PB_WS_CONFIG_CONFIG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* *
 Value represents a configuration value that, may be one of several types. */
typedef struct _ws_config_Value {
    pb_size_t which_value;
    union {
        pb_callback_t str_value;
        int32_t int_value;
        float float_value;
        bool bool_value;
    } value;
} ws_config_Value;

/* *
 Settings represents a collection of configuration settings, where each setting is a key-value pair. */
typedef struct _ws_config_Settings {
    pb_callback_t settings;
} ws_config_Settings;

typedef struct _ws_config_Settings_SettingsEntry {
    pb_callback_t key;
    bool has_value;
    ws_config_Value value;
} ws_config_Settings_SettingsEntry;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ws_config_Value_init_default             {0, {{{NULL}, NULL}}}
#define ws_config_Settings_init_default          {{{NULL}, NULL}}
#define ws_config_Settings_SettingsEntry_init_default {{{NULL}, NULL}, false, ws_config_Value_init_default}
#define ws_config_Value_init_zero                {0, {{{NULL}, NULL}}}
#define ws_config_Settings_init_zero             {{{NULL}, NULL}}
#define ws_config_Settings_SettingsEntry_init_zero {{{NULL}, NULL}, false, ws_config_Value_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ws_config_Value_str_value_tag            1
#define ws_config_Value_int_value_tag            2
#define ws_config_Value_float_value_tag          3
#define ws_config_Value_bool_value_tag           4
#define ws_config_Settings_settings_tag          1
#define ws_config_Settings_SettingsEntry_key_tag 1
#define ws_config_Settings_SettingsEntry_value_tag 2

/* Struct field encoding specification for nanopb */
#define ws_config_Value_FIELDLIST(X, a) \
X(a, CALLBACK, ONEOF,    STRING,   (value,str_value,value.str_value),   1) \
X(a, STATIC,   ONEOF,    INT32,    (value,int_value,value.int_value),   2) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,value.float_value),   3) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_value,value.bool_value),   4)
#define ws_config_Value_CALLBACK pb_default_field_callback
#define ws_config_Value_DEFAULT NULL

#define ws_config_Settings_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  settings,          1)
#define ws_config_Settings_CALLBACK pb_default_field_callback
#define ws_config_Settings_DEFAULT NULL
#define ws_config_Settings_settings_MSGTYPE ws_config_Settings_SettingsEntry

#define ws_config_Settings_SettingsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define ws_config_Settings_SettingsEntry_CALLBACK pb_default_field_callback
#define ws_config_Settings_SettingsEntry_DEFAULT NULL
#define ws_config_Settings_SettingsEntry_value_MSGTYPE ws_config_Value

extern const pb_msgdesc_t ws_config_Value_msg;
extern const pb_msgdesc_t ws_config_Settings_msg;
extern const pb_msgdesc_t ws_config_Settings_SettingsEntry_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ws_config_Value_fields &ws_config_Value_msg
#define ws_config_Settings_fields &ws_config_Settings_msg
#define ws_config_Settings_SettingsEntry_fields &ws_config_Settings_SettingsEntry_msg

/* Maximum encoded size of messages (where known) */
/* ws_config_Value_size depends on runtime parameters */
/* ws_config_Settings_size depends on runtime parameters */
/* ws_config_Settings_SettingsEntry_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
