/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_WS_DISPLAY_DISPLAY_PB_H_INCLUDED
#define PB_WS_DISPLAY_DISPLAY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* *
 DisplayType determines the type of display
 and selects which driver should be used. */
typedef enum _ws_display_DisplayType {
    ws_display_DisplayType_DISPLAY_TYPE_UNSPECIFIED = 0, /* * Unspecified display type. */
    ws_display_DisplayType_DISPLAY_TYPE_EPD = 1, /* * EPD (E-Paper Display) type */
    ws_display_DisplayType_DISPLAY_TYPE_TFT = 2, /* * TFT (Thin Film Transistor) type */
    ws_display_DisplayType_DISPLAY_TYPE_OLED = 3, /* * OLED (Organic LED) type */
    ws_display_DisplayType_DISPLAY_TYPE_LED_BACKPACK = 4, /* * LED Backpack (HT16K33-based 7-segment/14-segment displays) */
    ws_display_DisplayType_DISPLAY_TYPE_CHAR_LCD = 5 /* * Character LCD (text-based LCD displays) */
} ws_display_DisplayType;

/* *
 EPDMode defines the mode of the EPD display.
 This affects how the display renders images. */
typedef enum _ws_display_EPDMode {
    ws_display_EPDMode_EPD_MODE_UNSPECIFIED = 0, /* * Unspecified EPD mode */
    ws_display_EPDMode_EPD_MODE_GRAYSCALE4 = 1, /* * Grayscale 4 EPD mode */
    ws_display_EPDMode_EPD_MODE_MONO = 2 /* * Monochrome EPD mode */
} ws_display_EPDMode;

/* *
 LedBackpackAlignment represents text alignment options for LED backpack displays */
typedef enum _ws_display_LedBackpackAlignment {
    ws_display_LedBackpackAlignment_LBA_UNSPECIFIED = 0, /* * Unspecified alignment option. */
    ws_display_LedBackpackAlignment_LBA_LEFT = 1, /* * (Default) Left-aligned. */
    ws_display_LedBackpackAlignment_LBA_RIGHT = 2 /* * Right-aligned. */
} ws_display_LedBackpackAlignment;

/* *
 OledTextSize represents the desired OLED display text 'magnification' size. */
typedef enum _ws_display_OledTextSize {
    ws_display_OledTextSize_OTS_UNSPECIFIED = 0, /* * Unspecified text size. */
    ws_display_OledTextSize_OTS_DEFAULT = 1, /* * Default text size, 6x8px. */
    ws_display_OledTextSize_OTS_LARGE = 2 /* * Larger text size option, 12x16px. */
} ws_display_OledTextSize;

/* Struct definitions */
/* *
 I2cDisplayConfig contains the I2C bus configuration for I2C-based displays
 (OLED, LED Backpack, Character LCD)
 Matches DeviceDescriptor structure from i2c.proto for consistency */
typedef struct _ws_display_I2cDisplayConfig {
    uint32_t device_address; /* * I2C device address (typically 0x3C or 0x3D for OLED, 0x70 for HT16K33) */
    char bus_sda[6]; /* * Optional SDA pin for alternate I2C bus */
    char bus_scl[6]; /* * Optional SCL pin for alternate I2C bus */
    uint32_t mux_address; /* * Optional I2C multiplexer address */
    uint32_t mux_channel; /* * Optional I2C multiplexer channel (0-7) */
} ws_display_I2cDisplayConfig;

/* *
 EpdSpiConfig contains the configuration for SPI-based EPD displays.
 Includes the SPI bus number and pin assignments. */
typedef struct _ws_display_EpdSpiConfig {
    int32_t bus; /* * The SPI bus to use */
    char pin_dc[6]; /* * Pin for data/command */
    char pin_rst[6]; /* * Pin for reset */
    char pin_cs[6]; /* * Pin for chip select */
    char pin_sram_cs[6]; /* * Pin for SRAM chip select */
    char pin_busy[6]; /* * Pin for busy signal */
} ws_display_EpdSpiConfig;

/* *
 EPDConfig contains the configuration for an EPD display.
 It includes the mode, dimensions, and panel type. */
typedef struct _ws_display_EPDConfig {
    ws_display_EPDMode mode; /* * The mode of the EPD display */
    int32_t width; /* * Width of the EPD display, in pixels */
    int32_t height; /* * Height of the EPD display, in pixels */
    int32_t text_size; /* * Scale factor for text (1 = 6x8px, 2 = 12x16px,...) */
} ws_display_EPDConfig;

/* *
 OledConfig represents the configuration for an OLED display. */
typedef struct _ws_display_OledConfig {
    uint32_t width; /* * Width of the OLED display in pixels. */
    uint32_t height; /* * Height of the OLED display in pixels. */
    ws_display_OledTextSize font_size; /* * Desired font magnification for the OLED display. Defaults to OTS_DEFAULT. */
} ws_display_OledConfig;

/* *
 LedBackpackConfig represents the configuration for a LED backpack display. */
typedef struct _ws_display_LedBackpackConfig {
    int32_t brightness; /* * Desired brightness of the LED backpack, from 0 (off) to 15 (full brightness). */
    ws_display_LedBackpackAlignment alignment; /* * Desired text alignment for the LED backpack. */
} ws_display_LedBackpackConfig;

/* *
 CharLcdConfig represents the configuration for a character LCD display. */
typedef struct _ws_display_CharLcdConfig {
    uint32_t rows; /* * Number of rows for the character LCD. */
    uint32_t columns; /* * Number of columns for the character LCD. */
} ws_display_CharLcdConfig;

/* *
 TftSpiConfig contains the configuration for SPI TFT displays.
 Includes the SPI bus number and pin assignments. */
typedef struct _ws_display_TftSpiConfig {
    int32_t bus; /* * The SPI bus to use */
    char pin_cs[6]; /* * Pin for chip select */
    char pin_dc[6]; /* * Pin for data/command */
    char pin_mosi[6]; /* * Pin for MOSI */
    char pin_sck[6]; /* * Pin for SCK */
    char pin_rst[6]; /* * Pin for reset */
    char pin_miso[6]; /* * Pin for MISO */
} ws_display_TftSpiConfig;

typedef struct _ws_display_TftConfig {
    int32_t width; /* * Width of the TFT display in pixels */
    int32_t height; /* * Height of the TFT display in pixels */
    int32_t rotation; /* * Rotation of the display (0-3) */
    int32_t text_size; /* * Scale factor for text (1 = 6x8px, 2 = 12x16px,...) */
} ws_display_TftConfig;

typedef struct _ws_display_TtlRgb666PinConfig {
    char pin_r0[6]; /* * Pin for R0 */
    char pin_r1[6]; /* * Pin for R1 */
    char pin_r2[6]; /* * Pin for R2 */
    char pin_g0[6]; /* * Pin for G0 */
    char pin_g1[6]; /* * Pin for G1 */
    char pin_g2[6]; /* * Pin for G2 */
    char pin_b0[6]; /* * Pin for B0 */
    char pin_b1[6]; /* * Pin for B1 */
    char pin_b2[6]; /* * Pin for B2 */
} ws_display_TtlRgb666PinConfig;

typedef struct _ws_display_TtlRgb666Config {
    int32_t width; /* * Width of the display in pixels */
    int32_t height; /* * Height of the display in pixels */
    int32_t rotation; /* * Rotation of the display (0-3) */
    int32_t text_size; /* * Scale factor for text (1 = 6x8px, 2 = 12x16px,...) */
} ws_display_TtlRgb666Config;

typedef struct _ws_display_I8080PinConfig {
    char pin_d0[6]; /* * Pin for D0 */
    char pin_d1[6]; /* * Pin for D1 */
    char pin_d2[6]; /* * Pin for D2 */
    char pin_d3[6]; /* * Pin for D3 */
    char pin_d4[6]; /* * Pin for D4 */
    char pin_d5[6]; /* * Pin for D5 */
    char pin_d6[6]; /* * Pin for D6 */
    char pin_d7[6]; /* * Pin for D7 */
    char pin_cs[6]; /* * Pin for chip select */
    char pin_dc[6]; /* * Pin for data/command */
    char pin_rst[6]; /* * Pin for reset */
} ws_display_I8080PinConfig;

typedef struct _ws_display_I8080Config {
    int32_t width; /* * Width of the display in pixels */
    int32_t height; /* * Height of the display in pixels */
    int32_t rotation; /* * Rotation of the display (0-3) */
    int32_t text_size; /* * Scale factor for text (1 = 6x8px, 2 = 12x16px,...) */
} ws_display_I8080Config;

typedef struct _ws_display_DsiPinConfig {
    char pin_clk[6]; /* * Pin for DSI clock */
    char pin_data0[6]; /* * Pin for DSI data lane 0 */
    char pin_data1[6]; /* * Pin for DSI data lane 1 */
    char pin_data2[6]; /* * Pin for DSI data lane 2 */
    char pin_data3[6]; /* * Pin for DSI data lane 3 */
} ws_display_DsiPinConfig;

typedef struct _ws_display_DsiConfig {
    int32_t width; /* * Width of the display in pixels */
    int32_t height; /* * Height of the display in pixels */
    int32_t rotation; /* * Rotation of the display (0-3) */
    int32_t text_size; /* * Scale factor for text (1 = 6x8px, 2 = 12x16px,...) */
} ws_display_DsiConfig;

/* *
 Remove removes an existing display. */
typedef struct _ws_display_Remove {
    char name[64]; /* * Identifier for the display. */
} ws_display_Remove;

typedef PB_BYTES_ARRAY_T(102400) ws_display_BinaryImageType_data_t;
typedef struct _ws_display_BinaryImageType {
    char content_type[64]; /* * MIME type of the image (e.g., "image/png"). */
    ws_display_BinaryImageType_data_t data; /* * Raw image bytes. */
} ws_display_BinaryImageType;

/* *
 Write writes content to a display. */
typedef struct _ws_display_Write {
    char name[64]; /* * Identifies the display. */
    pb_size_t which_content;
    union {
        char message[1024]; /* * Monospace text message */
        char url[10240]; /* * URL to fetch the image from. */
        char base64image[102400]; /* * Base64-encoded w/content-type prefix. */
        ws_display_BinaryImageType binary_image; /* * Binary image data with content type. */
    } content;
    /* Display-specific write options (optional, with defaults) */
    bool clear_first; /* * Clear display before writing. Default: true */
    int32_t cursor_x; /* * Cursor position X (for char LCD/OLED). Default: 0 */
    int32_t cursor_y; /* * Cursor position Y (for char LCD/OLED). Default: 0 */
} ws_display_Write;

/* *
 Add adds a new display or replaces an existing one.
 Used as ws.display.Add in i2c.proto for I2C-based displays.

 Known driver strings (migrated from DisplayDriver enum):
 EPD drivers: "SSD1680", "ILI0373", "UC8253", "UC8179", "UC8151", "SSD1683"
 TFT drivers: "ST7789"
 OLED drivers: "SSD1306", "SSD1305", "SH1106", "SH1107"
 LED Backpack drivers: "HT16K33"
 Character LCD drivers: "MCP23008", "PCF8574"

 Panel naming conventions (for E-Paper displays with same driver, different panels):
 Format: "{size}-{resolution}-{color_mode}" or "adafruit-{product_id}"
 Examples: "5.83-648x480-mono", "4.2-300x400-gray", "adafruit-6397" */
typedef struct _ws_display_Add {
    ws_display_DisplayType type; /* * The type of display */
    char driver[32]; /* * Driver name (e.g., "UC8179", "SSD1306", "HT16K33") */
    char panel[32]; /* * Panel identifier for same driver with different configs */
    char name[64]; /* * Instance identifier for the display. */
    pb_size_t which_interface_type;
    union {
        ws_display_EpdSpiConfig spi_epd; /* * SPI configuration for EPD. */
        ws_display_TftSpiConfig spi_tft; /* * SPI configuration for TFT. */
        ws_display_I2cDisplayConfig i2c; /* * I2C configuration for OLED/LED/LCD displays. */
        ws_display_TtlRgb666PinConfig ttl_rgb666; /* * RGB666 configuration for Qualia. */
        ws_display_I8080PinConfig i8080; /* * i8080 8-bit parallel for T-DisplayS3/Memento. */
        ws_display_DsiPinConfig dsi; /* * DSI configuration for T-DisplayS3/Memento. */
    } interface_type;
    pb_size_t which_config;
    union {
        ws_display_EPDConfig config_epd; /* * Configuration for EPD. */
        ws_display_TftConfig config_tft; /* * Configuration for TFT. */
        ws_display_OledConfig config_oled; /* * Configuration for OLED. */
        ws_display_LedBackpackConfig config_led; /* * Configuration for LED Backpack. */
        ws_display_CharLcdConfig config_char_lcd; /* * Configuration for Character LCD. */
        ws_display_TtlRgb666Config config_ttl_rgb666; /* * Configuration for TTL RGB666. */
        ws_display_I8080Config config_i8080; /* * Configuration for i8080. */
        ws_display_DsiConfig config_dsi; /* * Configuration for DSI. */
    } config;
    bool has_write;
    ws_display_Write write; /* * Optional initial write for a display, used during check-in. */
} ws_display_Add;

/* *
 BrokerToDevice message envelope */
typedef struct _ws_display_B2D {
    pb_size_t which_payload;
    union {
        ws_display_Add add;
        ws_display_Remove remove;
        ws_display_Write write;
    } payload;
} ws_display_B2D;

/* *
 AddedOrReplaced confirms a display was added or replaced. */
typedef struct _ws_display_AddedOrReplaced {
    char name[64]; /* * Identifier for the display. */
    bool did_add; /* * Indicates if a display was added */
} ws_display_AddedOrReplaced;

/* *
 Removed confirms a display was removed. */
typedef struct _ws_display_Removed {
    char name[64]; /* * Identifies the display. */
    bool did_remove; /* * Indicates if a display was removed */
} ws_display_Removed;

/* *
 DeviceToBroker message envelope */
typedef struct _ws_display_D2B {
    pb_size_t which_payload;
    union {
        ws_display_AddedOrReplaced added_or_replaced;
        ws_display_Removed removed;
    } payload;
} ws_display_D2B;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ws_display_DisplayType_MIN ws_display_DisplayType_DISPLAY_TYPE_UNSPECIFIED
#define _ws_display_DisplayType_MAX ws_display_DisplayType_DISPLAY_TYPE_CHAR_LCD
#define _ws_display_DisplayType_ARRAYSIZE ((ws_display_DisplayType)(ws_display_DisplayType_DISPLAY_TYPE_CHAR_LCD+1))

#define _ws_display_EPDMode_MIN ws_display_EPDMode_EPD_MODE_UNSPECIFIED
#define _ws_display_EPDMode_MAX ws_display_EPDMode_EPD_MODE_MONO
#define _ws_display_EPDMode_ARRAYSIZE ((ws_display_EPDMode)(ws_display_EPDMode_EPD_MODE_MONO+1))

#define _ws_display_LedBackpackAlignment_MIN ws_display_LedBackpackAlignment_LBA_UNSPECIFIED
#define _ws_display_LedBackpackAlignment_MAX ws_display_LedBackpackAlignment_LBA_RIGHT
#define _ws_display_LedBackpackAlignment_ARRAYSIZE ((ws_display_LedBackpackAlignment)(ws_display_LedBackpackAlignment_LBA_RIGHT+1))

#define _ws_display_OledTextSize_MIN ws_display_OledTextSize_OTS_UNSPECIFIED
#define _ws_display_OledTextSize_MAX ws_display_OledTextSize_OTS_LARGE
#define _ws_display_OledTextSize_ARRAYSIZE ((ws_display_OledTextSize)(ws_display_OledTextSize_OTS_LARGE+1))





#define ws_display_EPDConfig_mode_ENUMTYPE ws_display_EPDMode

#define ws_display_OledConfig_font_size_ENUMTYPE ws_display_OledTextSize

#define ws_display_LedBackpackConfig_alignment_ENUMTYPE ws_display_LedBackpackAlignment










#define ws_display_Add_type_ENUMTYPE ws_display_DisplayType







/* Initializer values for message structs */
#define ws_display_B2D_init_default              {0, {ws_display_Add_init_default}}
#define ws_display_D2B_init_default              {0, {ws_display_AddedOrReplaced_init_default}}
#define ws_display_I2cDisplayConfig_init_default {0, "", "", 0, 0}
#define ws_display_EpdSpiConfig_init_default     {0, "", "", "", "", ""}
#define ws_display_EPDConfig_init_default        {_ws_display_EPDMode_MIN, 0, 0, 0}
#define ws_display_OledConfig_init_default       {0, 0, _ws_display_OledTextSize_MIN}
#define ws_display_LedBackpackConfig_init_default {0, _ws_display_LedBackpackAlignment_MIN}
#define ws_display_CharLcdConfig_init_default    {0, 0}
#define ws_display_TftSpiConfig_init_default     {0, "", "", "", "", "", ""}
#define ws_display_TftConfig_init_default        {0, 0, 0, 0}
#define ws_display_TtlRgb666PinConfig_init_default {"", "", "", "", "", "", "", "", ""}
#define ws_display_TtlRgb666Config_init_default  {0, 0, 0, 0}
#define ws_display_I8080PinConfig_init_default   {"", "", "", "", "", "", "", "", "", "", ""}
#define ws_display_I8080Config_init_default      {0, 0, 0, 0}
#define ws_display_DsiPinConfig_init_default     {"", "", "", "", ""}
#define ws_display_DsiConfig_init_default        {0, 0, 0, 0}
#define ws_display_Add_init_default              {_ws_display_DisplayType_MIN, "", "", "", 0, {ws_display_EpdSpiConfig_init_default}, 0, {ws_display_EPDConfig_init_default}, false, ws_display_Write_init_default}
#define ws_display_Remove_init_default           {""}
#define ws_display_BinaryImageType_init_default  {"", {0, {0}}}
#define ws_display_Write_init_default            {"", 0, {""}, 0, 0, 0}
#define ws_display_AddedOrReplaced_init_default  {"", 0}
#define ws_display_Removed_init_default          {"", 0}
#define ws_display_B2D_init_zero                 {0, {ws_display_Add_init_zero}}
#define ws_display_D2B_init_zero                 {0, {ws_display_AddedOrReplaced_init_zero}}
#define ws_display_I2cDisplayConfig_init_zero    {0, "", "", 0, 0}
#define ws_display_EpdSpiConfig_init_zero        {0, "", "", "", "", ""}
#define ws_display_EPDConfig_init_zero           {_ws_display_EPDMode_MIN, 0, 0, 0}
#define ws_display_OledConfig_init_zero          {0, 0, _ws_display_OledTextSize_MIN}
#define ws_display_LedBackpackConfig_init_zero   {0, _ws_display_LedBackpackAlignment_MIN}
#define ws_display_CharLcdConfig_init_zero       {0, 0}
#define ws_display_TftSpiConfig_init_zero        {0, "", "", "", "", "", ""}
#define ws_display_TftConfig_init_zero           {0, 0, 0, 0}
#define ws_display_TtlRgb666PinConfig_init_zero  {"", "", "", "", "", "", "", "", ""}
#define ws_display_TtlRgb666Config_init_zero     {0, 0, 0, 0}
#define ws_display_I8080PinConfig_init_zero      {"", "", "", "", "", "", "", "", "", "", ""}
#define ws_display_I8080Config_init_zero         {0, 0, 0, 0}
#define ws_display_DsiPinConfig_init_zero        {"", "", "", "", ""}
#define ws_display_DsiConfig_init_zero           {0, 0, 0, 0}
#define ws_display_Add_init_zero                 {_ws_display_DisplayType_MIN, "", "", "", 0, {ws_display_EpdSpiConfig_init_zero}, 0, {ws_display_EPDConfig_init_zero}, false, ws_display_Write_init_zero}
#define ws_display_Remove_init_zero              {""}
#define ws_display_BinaryImageType_init_zero     {"", {0, {0}}}
#define ws_display_Write_init_zero               {"", 0, {""}, 0, 0, 0}
#define ws_display_AddedOrReplaced_init_zero     {"", 0}
#define ws_display_Removed_init_zero             {"", 0}

/* Field tags (for use in manual encoding/decoding) */
#define ws_display_I2cDisplayConfig_device_address_tag 1
#define ws_display_I2cDisplayConfig_bus_sda_tag  2
#define ws_display_I2cDisplayConfig_bus_scl_tag  3
#define ws_display_I2cDisplayConfig_mux_address_tag 4
#define ws_display_I2cDisplayConfig_mux_channel_tag 5
#define ws_display_EpdSpiConfig_bus_tag          1
#define ws_display_EpdSpiConfig_pin_dc_tag       2
#define ws_display_EpdSpiConfig_pin_rst_tag      3
#define ws_display_EpdSpiConfig_pin_cs_tag       4
#define ws_display_EpdSpiConfig_pin_sram_cs_tag  5
#define ws_display_EpdSpiConfig_pin_busy_tag     6
#define ws_display_EPDConfig_mode_tag            1
#define ws_display_EPDConfig_width_tag           2
#define ws_display_EPDConfig_height_tag          3
#define ws_display_EPDConfig_text_size_tag       4
#define ws_display_OledConfig_width_tag          1
#define ws_display_OledConfig_height_tag         2
#define ws_display_OledConfig_font_size_tag      3
#define ws_display_LedBackpackConfig_brightness_tag 1
#define ws_display_LedBackpackConfig_alignment_tag 2
#define ws_display_CharLcdConfig_rows_tag        1
#define ws_display_CharLcdConfig_columns_tag     2
#define ws_display_TftSpiConfig_bus_tag          1
#define ws_display_TftSpiConfig_pin_cs_tag       2
#define ws_display_TftSpiConfig_pin_dc_tag       3
#define ws_display_TftSpiConfig_pin_mosi_tag     4
#define ws_display_TftSpiConfig_pin_sck_tag      5
#define ws_display_TftSpiConfig_pin_rst_tag      6
#define ws_display_TftSpiConfig_pin_miso_tag     7
#define ws_display_TftConfig_width_tag           1
#define ws_display_TftConfig_height_tag          2
#define ws_display_TftConfig_rotation_tag        3
#define ws_display_TftConfig_text_size_tag       4
#define ws_display_TtlRgb666PinConfig_pin_r0_tag 1
#define ws_display_TtlRgb666PinConfig_pin_r1_tag 2
#define ws_display_TtlRgb666PinConfig_pin_r2_tag 3
#define ws_display_TtlRgb666PinConfig_pin_g0_tag 4
#define ws_display_TtlRgb666PinConfig_pin_g1_tag 5
#define ws_display_TtlRgb666PinConfig_pin_g2_tag 6
#define ws_display_TtlRgb666PinConfig_pin_b0_tag 7
#define ws_display_TtlRgb666PinConfig_pin_b1_tag 8
#define ws_display_TtlRgb666PinConfig_pin_b2_tag 9
#define ws_display_TtlRgb666Config_width_tag     1
#define ws_display_TtlRgb666Config_height_tag    2
#define ws_display_TtlRgb666Config_rotation_tag  3
#define ws_display_TtlRgb666Config_text_size_tag 4
#define ws_display_I8080PinConfig_pin_d0_tag     1
#define ws_display_I8080PinConfig_pin_d1_tag     2
#define ws_display_I8080PinConfig_pin_d2_tag     3
#define ws_display_I8080PinConfig_pin_d3_tag     4
#define ws_display_I8080PinConfig_pin_d4_tag     5
#define ws_display_I8080PinConfig_pin_d5_tag     6
#define ws_display_I8080PinConfig_pin_d6_tag     7
#define ws_display_I8080PinConfig_pin_d7_tag     8
#define ws_display_I8080PinConfig_pin_cs_tag     9
#define ws_display_I8080PinConfig_pin_dc_tag     10
#define ws_display_I8080PinConfig_pin_rst_tag    11
#define ws_display_I8080Config_width_tag         1
#define ws_display_I8080Config_height_tag        2
#define ws_display_I8080Config_rotation_tag      3
#define ws_display_I8080Config_text_size_tag     4
#define ws_display_DsiPinConfig_pin_clk_tag      1
#define ws_display_DsiPinConfig_pin_data0_tag    2
#define ws_display_DsiPinConfig_pin_data1_tag    3
#define ws_display_DsiPinConfig_pin_data2_tag    4
#define ws_display_DsiPinConfig_pin_data3_tag    5
#define ws_display_DsiConfig_width_tag           1
#define ws_display_DsiConfig_height_tag          2
#define ws_display_DsiConfig_rotation_tag        3
#define ws_display_DsiConfig_text_size_tag       4
#define ws_display_Remove_name_tag               1
#define ws_display_BinaryImageType_content_type_tag 1
#define ws_display_BinaryImageType_data_tag      2
#define ws_display_Write_name_tag                1
#define ws_display_Write_message_tag             2
#define ws_display_Write_url_tag                 3
#define ws_display_Write_base64image_tag         4
#define ws_display_Write_binary_image_tag        5
#define ws_display_Write_clear_first_tag         6
#define ws_display_Write_cursor_x_tag            7
#define ws_display_Write_cursor_y_tag            8
#define ws_display_Add_type_tag                  1
#define ws_display_Add_driver_tag                2
#define ws_display_Add_panel_tag                 3
#define ws_display_Add_name_tag                  4
#define ws_display_Add_spi_epd_tag               5
#define ws_display_Add_spi_tft_tag               6
#define ws_display_Add_i2c_tag                   7
#define ws_display_Add_ttl_rgb666_tag            8
#define ws_display_Add_i8080_tag                 9
#define ws_display_Add_dsi_tag                   10
#define ws_display_Add_config_epd_tag            11
#define ws_display_Add_config_tft_tag            12
#define ws_display_Add_config_oled_tag           13
#define ws_display_Add_config_led_tag            14
#define ws_display_Add_config_char_lcd_tag       15
#define ws_display_Add_config_ttl_rgb666_tag     16
#define ws_display_Add_config_i8080_tag          17
#define ws_display_Add_config_dsi_tag            18
#define ws_display_Add_write_tag                 19
#define ws_display_B2D_add_tag                   1
#define ws_display_B2D_remove_tag                2
#define ws_display_B2D_write_tag                 3
#define ws_display_AddedOrReplaced_name_tag      1
#define ws_display_AddedOrReplaced_did_add_tag   2
#define ws_display_Removed_name_tag              1
#define ws_display_Removed_did_remove_tag        2
#define ws_display_D2B_added_or_replaced_tag     1
#define ws_display_D2B_removed_tag               2

/* Struct field encoding specification for nanopb */
#define ws_display_B2D_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,add,payload.add),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,remove,payload.remove),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,write,payload.write),   3)
#define ws_display_B2D_CALLBACK NULL
#define ws_display_B2D_DEFAULT NULL
#define ws_display_B2D_payload_add_MSGTYPE ws_display_Add
#define ws_display_B2D_payload_remove_MSGTYPE ws_display_Remove
#define ws_display_B2D_payload_write_MSGTYPE ws_display_Write

#define ws_display_D2B_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,added_or_replaced,payload.added_or_replaced),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,removed,payload.removed),   2)
#define ws_display_D2B_CALLBACK NULL
#define ws_display_D2B_DEFAULT NULL
#define ws_display_D2B_payload_added_or_replaced_MSGTYPE ws_display_AddedOrReplaced
#define ws_display_D2B_payload_removed_MSGTYPE ws_display_Removed

#define ws_display_I2cDisplayConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   device_address,    1) \
X(a, STATIC,   SINGULAR, STRING,   bus_sda,           2) \
X(a, STATIC,   SINGULAR, STRING,   bus_scl,           3) \
X(a, STATIC,   SINGULAR, UINT32,   mux_address,       4) \
X(a, STATIC,   SINGULAR, UINT32,   mux_channel,       5)
#define ws_display_I2cDisplayConfig_CALLBACK NULL
#define ws_display_I2cDisplayConfig_DEFAULT NULL

#define ws_display_EpdSpiConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    bus,               1) \
X(a, STATIC,   SINGULAR, STRING,   pin_dc,            2) \
X(a, STATIC,   SINGULAR, STRING,   pin_rst,           3) \
X(a, STATIC,   SINGULAR, STRING,   pin_cs,            4) \
X(a, STATIC,   SINGULAR, STRING,   pin_sram_cs,       5) \
X(a, STATIC,   SINGULAR, STRING,   pin_busy,          6)
#define ws_display_EpdSpiConfig_CALLBACK NULL
#define ws_display_EpdSpiConfig_DEFAULT NULL

#define ws_display_EPDConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1) \
X(a, STATIC,   SINGULAR, INT32,    width,             2) \
X(a, STATIC,   SINGULAR, INT32,    height,            3) \
X(a, STATIC,   SINGULAR, INT32,    text_size,         4)
#define ws_display_EPDConfig_CALLBACK NULL
#define ws_display_EPDConfig_DEFAULT NULL

#define ws_display_OledConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   width,             1) \
X(a, STATIC,   SINGULAR, UINT32,   height,            2) \
X(a, STATIC,   SINGULAR, UENUM,    font_size,         3)
#define ws_display_OledConfig_CALLBACK NULL
#define ws_display_OledConfig_DEFAULT NULL

#define ws_display_LedBackpackConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    brightness,        1) \
X(a, STATIC,   SINGULAR, UENUM,    alignment,         2)
#define ws_display_LedBackpackConfig_CALLBACK NULL
#define ws_display_LedBackpackConfig_DEFAULT NULL

#define ws_display_CharLcdConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   rows,              1) \
X(a, STATIC,   SINGULAR, UINT32,   columns,           2)
#define ws_display_CharLcdConfig_CALLBACK NULL
#define ws_display_CharLcdConfig_DEFAULT NULL

#define ws_display_TftSpiConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    bus,               1) \
X(a, STATIC,   SINGULAR, STRING,   pin_cs,            2) \
X(a, STATIC,   SINGULAR, STRING,   pin_dc,            3) \
X(a, STATIC,   SINGULAR, STRING,   pin_mosi,          4) \
X(a, STATIC,   SINGULAR, STRING,   pin_sck,           5) \
X(a, STATIC,   SINGULAR, STRING,   pin_rst,           6) \
X(a, STATIC,   SINGULAR, STRING,   pin_miso,          7)
#define ws_display_TftSpiConfig_CALLBACK NULL
#define ws_display_TftSpiConfig_DEFAULT NULL

#define ws_display_TftConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    width,             1) \
X(a, STATIC,   SINGULAR, INT32,    height,            2) \
X(a, STATIC,   SINGULAR, INT32,    rotation,          3) \
X(a, STATIC,   SINGULAR, INT32,    text_size,         4)
#define ws_display_TftConfig_CALLBACK NULL
#define ws_display_TftConfig_DEFAULT NULL

#define ws_display_TtlRgb666PinConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin_r0,            1) \
X(a, STATIC,   SINGULAR, STRING,   pin_r1,            2) \
X(a, STATIC,   SINGULAR, STRING,   pin_r2,            3) \
X(a, STATIC,   SINGULAR, STRING,   pin_g0,            4) \
X(a, STATIC,   SINGULAR, STRING,   pin_g1,            5) \
X(a, STATIC,   SINGULAR, STRING,   pin_g2,            6) \
X(a, STATIC,   SINGULAR, STRING,   pin_b0,            7) \
X(a, STATIC,   SINGULAR, STRING,   pin_b1,            8) \
X(a, STATIC,   SINGULAR, STRING,   pin_b2,            9)
#define ws_display_TtlRgb666PinConfig_CALLBACK NULL
#define ws_display_TtlRgb666PinConfig_DEFAULT NULL

#define ws_display_TtlRgb666Config_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    width,             1) \
X(a, STATIC,   SINGULAR, INT32,    height,            2) \
X(a, STATIC,   SINGULAR, INT32,    rotation,          3) \
X(a, STATIC,   SINGULAR, INT32,    text_size,         4)
#define ws_display_TtlRgb666Config_CALLBACK NULL
#define ws_display_TtlRgb666Config_DEFAULT NULL

#define ws_display_I8080PinConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin_d0,            1) \
X(a, STATIC,   SINGULAR, STRING,   pin_d1,            2) \
X(a, STATIC,   SINGULAR, STRING,   pin_d2,            3) \
X(a, STATIC,   SINGULAR, STRING,   pin_d3,            4) \
X(a, STATIC,   SINGULAR, STRING,   pin_d4,            5) \
X(a, STATIC,   SINGULAR, STRING,   pin_d5,            6) \
X(a, STATIC,   SINGULAR, STRING,   pin_d6,            7) \
X(a, STATIC,   SINGULAR, STRING,   pin_d7,            8) \
X(a, STATIC,   SINGULAR, STRING,   pin_cs,            9) \
X(a, STATIC,   SINGULAR, STRING,   pin_dc,           10) \
X(a, STATIC,   SINGULAR, STRING,   pin_rst,          11)
#define ws_display_I8080PinConfig_CALLBACK NULL
#define ws_display_I8080PinConfig_DEFAULT NULL

#define ws_display_I8080Config_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    width,             1) \
X(a, STATIC,   SINGULAR, INT32,    height,            2) \
X(a, STATIC,   SINGULAR, INT32,    rotation,          3) \
X(a, STATIC,   SINGULAR, INT32,    text_size,         4)
#define ws_display_I8080Config_CALLBACK NULL
#define ws_display_I8080Config_DEFAULT NULL

#define ws_display_DsiPinConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin_clk,           1) \
X(a, STATIC,   SINGULAR, STRING,   pin_data0,         2) \
X(a, STATIC,   SINGULAR, STRING,   pin_data1,         3) \
X(a, STATIC,   SINGULAR, STRING,   pin_data2,         4) \
X(a, STATIC,   SINGULAR, STRING,   pin_data3,         5)
#define ws_display_DsiPinConfig_CALLBACK NULL
#define ws_display_DsiPinConfig_DEFAULT NULL

#define ws_display_DsiConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    width,             1) \
X(a, STATIC,   SINGULAR, INT32,    height,            2) \
X(a, STATIC,   SINGULAR, INT32,    rotation,          3) \
X(a, STATIC,   SINGULAR, INT32,    text_size,         4)
#define ws_display_DsiConfig_CALLBACK NULL
#define ws_display_DsiConfig_DEFAULT NULL

#define ws_display_Add_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, STRING,   driver,            2) \
X(a, STATIC,   SINGULAR, STRING,   panel,             3) \
X(a, STATIC,   SINGULAR, STRING,   name,              4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (interface_type,spi_epd,interface_type.spi_epd),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (interface_type,spi_tft,interface_type.spi_tft),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (interface_type,i2c,interface_type.i2c),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (interface_type,ttl_rgb666,interface_type.ttl_rgb666),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (interface_type,i8080,interface_type.i8080),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (interface_type,dsi,interface_type.dsi),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config,config_epd,config.config_epd),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config,config_tft,config.config_tft),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config,config_oled,config.config_oled),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config,config_led,config.config_led),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config,config_char_lcd,config.config_char_lcd),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config,config_ttl_rgb666,config.config_ttl_rgb666),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config,config_i8080,config.config_i8080),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config,config_dsi,config.config_dsi),  18) \
X(a, STATIC,   OPTIONAL, MESSAGE,  write,            19)
#define ws_display_Add_CALLBACK NULL
#define ws_display_Add_DEFAULT NULL
#define ws_display_Add_interface_type_spi_epd_MSGTYPE ws_display_EpdSpiConfig
#define ws_display_Add_interface_type_spi_tft_MSGTYPE ws_display_TftSpiConfig
#define ws_display_Add_interface_type_i2c_MSGTYPE ws_display_I2cDisplayConfig
#define ws_display_Add_interface_type_ttl_rgb666_MSGTYPE ws_display_TtlRgb666PinConfig
#define ws_display_Add_interface_type_i8080_MSGTYPE ws_display_I8080PinConfig
#define ws_display_Add_interface_type_dsi_MSGTYPE ws_display_DsiPinConfig
#define ws_display_Add_config_config_epd_MSGTYPE ws_display_EPDConfig
#define ws_display_Add_config_config_tft_MSGTYPE ws_display_TftConfig
#define ws_display_Add_config_config_oled_MSGTYPE ws_display_OledConfig
#define ws_display_Add_config_config_led_MSGTYPE ws_display_LedBackpackConfig
#define ws_display_Add_config_config_char_lcd_MSGTYPE ws_display_CharLcdConfig
#define ws_display_Add_config_config_ttl_rgb666_MSGTYPE ws_display_TtlRgb666Config
#define ws_display_Add_config_config_i8080_MSGTYPE ws_display_I8080Config
#define ws_display_Add_config_config_dsi_MSGTYPE ws_display_DsiConfig
#define ws_display_Add_write_MSGTYPE ws_display_Write

#define ws_display_Remove_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1)
#define ws_display_Remove_CALLBACK NULL
#define ws_display_Remove_DEFAULT NULL

#define ws_display_BinaryImageType_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   content_type,      1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2)
#define ws_display_BinaryImageType_CALLBACK NULL
#define ws_display_BinaryImageType_DEFAULT NULL

#define ws_display_Write_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   ONEOF,    STRING,   (content,message,content.message),   2) \
X(a, STATIC,   ONEOF,    STRING,   (content,url,content.url),   3) \
X(a, STATIC,   ONEOF,    STRING,   (content,base64image,content.base64image),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (content,binary_image,content.binary_image),   5) \
X(a, STATIC,   SINGULAR, BOOL,     clear_first,       6) \
X(a, STATIC,   SINGULAR, INT32,    cursor_x,          7) \
X(a, STATIC,   SINGULAR, INT32,    cursor_y,          8)
#define ws_display_Write_CALLBACK NULL
#define ws_display_Write_DEFAULT NULL
#define ws_display_Write_content_binary_image_MSGTYPE ws_display_BinaryImageType

#define ws_display_AddedOrReplaced_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, BOOL,     did_add,           2)
#define ws_display_AddedOrReplaced_CALLBACK NULL
#define ws_display_AddedOrReplaced_DEFAULT NULL

#define ws_display_Removed_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, BOOL,     did_remove,        2)
#define ws_display_Removed_CALLBACK NULL
#define ws_display_Removed_DEFAULT NULL

extern const pb_msgdesc_t ws_display_B2D_msg;
extern const pb_msgdesc_t ws_display_D2B_msg;
extern const pb_msgdesc_t ws_display_I2cDisplayConfig_msg;
extern const pb_msgdesc_t ws_display_EpdSpiConfig_msg;
extern const pb_msgdesc_t ws_display_EPDConfig_msg;
extern const pb_msgdesc_t ws_display_OledConfig_msg;
extern const pb_msgdesc_t ws_display_LedBackpackConfig_msg;
extern const pb_msgdesc_t ws_display_CharLcdConfig_msg;
extern const pb_msgdesc_t ws_display_TftSpiConfig_msg;
extern const pb_msgdesc_t ws_display_TftConfig_msg;
extern const pb_msgdesc_t ws_display_TtlRgb666PinConfig_msg;
extern const pb_msgdesc_t ws_display_TtlRgb666Config_msg;
extern const pb_msgdesc_t ws_display_I8080PinConfig_msg;
extern const pb_msgdesc_t ws_display_I8080Config_msg;
extern const pb_msgdesc_t ws_display_DsiPinConfig_msg;
extern const pb_msgdesc_t ws_display_DsiConfig_msg;
extern const pb_msgdesc_t ws_display_Add_msg;
extern const pb_msgdesc_t ws_display_Remove_msg;
extern const pb_msgdesc_t ws_display_BinaryImageType_msg;
extern const pb_msgdesc_t ws_display_Write_msg;
extern const pb_msgdesc_t ws_display_AddedOrReplaced_msg;
extern const pb_msgdesc_t ws_display_Removed_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ws_display_B2D_fields &ws_display_B2D_msg
#define ws_display_D2B_fields &ws_display_D2B_msg
#define ws_display_I2cDisplayConfig_fields &ws_display_I2cDisplayConfig_msg
#define ws_display_EpdSpiConfig_fields &ws_display_EpdSpiConfig_msg
#define ws_display_EPDConfig_fields &ws_display_EPDConfig_msg
#define ws_display_OledConfig_fields &ws_display_OledConfig_msg
#define ws_display_LedBackpackConfig_fields &ws_display_LedBackpackConfig_msg
#define ws_display_CharLcdConfig_fields &ws_display_CharLcdConfig_msg
#define ws_display_TftSpiConfig_fields &ws_display_TftSpiConfig_msg
#define ws_display_TftConfig_fields &ws_display_TftConfig_msg
#define ws_display_TtlRgb666PinConfig_fields &ws_display_TtlRgb666PinConfig_msg
#define ws_display_TtlRgb666Config_fields &ws_display_TtlRgb666Config_msg
#define ws_display_I8080PinConfig_fields &ws_display_I8080PinConfig_msg
#define ws_display_I8080Config_fields &ws_display_I8080Config_msg
#define ws_display_DsiPinConfig_fields &ws_display_DsiPinConfig_msg
#define ws_display_DsiConfig_fields &ws_display_DsiConfig_msg
#define ws_display_Add_fields &ws_display_Add_msg
#define ws_display_Remove_fields &ws_display_Remove_msg
#define ws_display_BinaryImageType_fields &ws_display_BinaryImageType_msg
#define ws_display_Write_fields &ws_display_Write_msg
#define ws_display_AddedOrReplaced_fields &ws_display_AddedOrReplaced_msg
#define ws_display_Removed_fields &ws_display_Removed_msg

/* Maximum encoded size of messages (where known) */
#define WS_DISPLAY_DISPLAY_PB_H_MAX_SIZE         ws_display_B2D_size
#define ws_display_Add_size                      102826
#define ws_display_AddedOrReplaced_size          67
#define ws_display_B2D_size                      102830
#define ws_display_BinaryImageType_size          102469
#define ws_display_CharLcdConfig_size            12
#define ws_display_D2B_size                      69
#define ws_display_DsiConfig_size                44
#define ws_display_DsiPinConfig_size             35
#define ws_display_EPDConfig_size                35
#define ws_display_EpdSpiConfig_size             46
#define ws_display_I2cDisplayConfig_size         32
#define ws_display_I8080Config_size              44
#define ws_display_I8080PinConfig_size           77
#define ws_display_LedBackpackConfig_size        13
#define ws_display_OledConfig_size               14
#define ws_display_Remove_size                   65
#define ws_display_Removed_size                  67
#define ws_display_TftConfig_size                44
#define ws_display_TftSpiConfig_size             53
#define ws_display_TtlRgb666Config_size          44
#define ws_display_TtlRgb666PinConfig_size       63
#define ws_display_Write_size                    102562

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
