/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 at Thu Apr  9 23:30:13 2026. */

#ifndef PB_WS_DISPLAY_DISPLAY_PB_H_INCLUDED
#define PB_WS_DISPLAY_DISPLAY_PB_H_INCLUDED
#include <pb.h>
#include "i2c.pb.h"
#include "pwm.pb.h"
#include "digitalio.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* *
 DisplayClass determines the type of display
 and selects which driver should be used. */
typedef enum _ws_display_DisplayClass {
    ws_display_DisplayClass_DISPLAY_CLASS_UNSPECIFIED = 0, /* * Unspecified display type. */
    ws_display_DisplayClass_DISPLAY_CLASS_EPD = 1, /* * EPD (E-Paper Display) type */
    ws_display_DisplayClass_DISPLAY_CLASS_TFT = 2, /* * TFT (Thin Film Transistor) type */
    ws_display_DisplayClass_DISPLAY_CLASS_OLED = 3, /* * OLED (Organic LED) type */
    ws_display_DisplayClass_DISPLAY_CLASS_LED_BACKPACK = 4, /* * LED Backpack (HT16K33-based 7-segment/14-segment displays) */
    ws_display_DisplayClass_DISPLAY_CLASS_CHAR_LCD = 5 /* * Character LCD (text-based LCD displays) */
} ws_display_DisplayClass;

/* *
 EPDMode defines the mode of the EPD display.
 This affects how the display renders images. */
typedef enum _ws_display_EPDMode {
    ws_display_EPDMode_EPD_MODE_UNSPECIFIED = 0, /* * Unspecified EPD mode */
    ws_display_EPDMode_EPD_MODE_GRAYSCALE4 = 1, /* * Grayscale 4 EPD mode */
    ws_display_EPDMode_EPD_MODE_MONO = 2 /* * Monochrome EPD mode */
} ws_display_EPDMode;

/* *
 LedBackpackAlignment represents text alignment options for LED backpack displays */
typedef enum _ws_display_LedBackpackAlignment {
    ws_display_LedBackpackAlignment_LBA_UNSPECIFIED = 0, /* * Unspecified alignment option. */
    ws_display_LedBackpackAlignment_LBA_LEFT = 1, /* * (Default) Left-aligned. */
    ws_display_LedBackpackAlignment_LBA_RIGHT = 2 /* * Right-aligned. */
} ws_display_LedBackpackAlignment;

/* Struct definitions */
typedef struct _ws_display_DisplayProperties {
    int32_t width; /* * Display width in pixels. */
    int32_t height; /* * Display height in pixels. */
    int32_t rotation; /* * Display rotation (Clockwise 90* increments 0-3). */
    int32_t text_size; /* * Text size or magnification factor (if applicable) - 1 = 6x8px, 2 = 12x16px, ... */
} ws_display_DisplayProperties;

/* * SPI pin configuration for display interfaces. */
typedef struct _ws_display_SpiPinConfig {
    int32_t bus; /* * The SPI bus to use */
    char pin_mosi[6]; /* * Pin for MOSI */
    char pin_sck[6]; /* * Pin for SCK */
    char pin_miso[6]; /* * Pin for MISO */
    char pin_cs[6]; /* * Pin for chip select */
    char pin_dc[6]; /* * Pin for data/command */
    char pin_rst[6]; /* * Pin for reset */
} ws_display_SpiPinConfig;

/* *
 EpdSpiConfig contains the configuration for SPI-based EPD displays.
 Includes the SPI Pin Config plus the SRAM chip select pin. */
typedef struct _ws_display_EpdSpiConfig {
    bool has_spi_pins;
    ws_display_SpiPinConfig spi_pins; /* * SPI bus and pin configuration for EPD. */
    uint32_t pin_sram_cs; /* * Pin for SRAM chip select (if required by the EPD). */
    uint32_t pin_busy; /* * Pin for busy signal */
} ws_display_EpdSpiConfig;

/* *
 EPDConfig contains the configuration for an EPD display.
 It includes the mode, dimensions, and panel type. */
typedef struct _ws_display_EPDConfig {
    ws_display_EPDMode mode; /* * The mode of the EPD display */
    bool has_properties;
    ws_display_DisplayProperties properties; /* * Common display properties (dimensions, rotation, text size). */
} ws_display_EPDConfig;

/* *
 LedBackpackConfig represents the configuration for a LED backpack display. */
typedef struct _ws_display_LedBackpackConfig {
    int32_t brightness; /* * Desired brightness of the LED backpack, from 0 (off) to 15 (full brightness). */
    ws_display_LedBackpackAlignment alignment; /* * Desired text alignment for the LED backpack. */
} ws_display_LedBackpackConfig;

/* *
 CharLcdConfig represents the configuration for a character LCD display. */
typedef struct _ws_display_CharLcdConfig {
    uint32_t rows; /* * Number of rows for the character LCD. */
    uint32_t columns; /* * Number of columns for the character LCD. */
} ws_display_CharLcdConfig;

/* *
 TftSpiConfig contains the configuration for SPI TFT displays.
 Includes the SPI bus number and pin assignments. */
typedef struct _ws_display_TftSpiConfig {
    bool has_spi_pins;
    ws_display_SpiPinConfig spi_pins; /* * SPI bus and pin configuration for TFT. */
} ws_display_TftSpiConfig;

/* * TTL RGB666 pin configuration for parallel RGB displays. */
typedef struct _ws_display_TtlRgb666PinConfig {
    char pin_r0[6]; /* * Pin for R0 */
    char pin_r1[6]; /* * Pin for R1 */
    char pin_r2[6]; /* * Pin for R2 */
    char pin_g0[6]; /* * Pin for G0 */
    char pin_g1[6]; /* * Pin for G1 */
    char pin_g2[6]; /* * Pin for G2 */
    char pin_b0[6]; /* * Pin for B0 */
    char pin_b1[6]; /* * Pin for B1 */
    char pin_b2[6]; /* * Pin for B2 */
} ws_display_TtlRgb666PinConfig;

/* * Intel 8080 8-bit parallel pin configuration for displays. */
typedef struct _ws_display_I8080PinConfig {
    char pin_d0[6]; /* * Pin for D0 */
    char pin_d1[6]; /* * Pin for D1 */
    char pin_d2[6]; /* * Pin for D2 */
    char pin_d3[6]; /* * Pin for D3 */
    char pin_d4[6]; /* * Pin for D4 */
    char pin_d5[6]; /* * Pin for D5 */
    char pin_d6[6]; /* * Pin for D6 */
    char pin_d7[6]; /* * Pin for D7 */
    char pin_cs[6]; /* * Pin for chip select */
    char pin_dc[6]; /* * Pin for data/command */
    char pin_rst[6]; /* * Pin for reset */
} ws_display_I8080PinConfig;

/* *
 DsiInterfaceConfig contains the minimal configuration for MIPI DSI displays.
 DSI clock and data lanes are dedicated differential pads on the SoC, not GPIOs. */
typedef struct _ws_display_DsiInterfaceConfig {
    uint32_t bus; /* * DSI bus index (0 if only one DSI peripheral). */
    uint32_t pin_rst; /* * GPIO pin for display panel reset. */
} ws_display_DsiInterfaceConfig;

/* *
 BacklightConfig configures the display backlight.
 Shared across any display type with a controllable backlight
 (TFT, DSI, Character LCD with RGB backlight, etc.). */
typedef struct _ws_display_BacklightConfig {
    pb_size_t which_backlight_add;
    union {
        ws_digitalio_Add backlight_digital; /* * Optional digital pin configuration for backlight control, used during check-in. */
        ws_pwm_Add backlight_pwm; /* * Optional PWM configuration for backlight control, used during check-in. */
    } backlight_add;
} ws_display_BacklightConfig;

/* *
 Remove removes an existing display. */
typedef struct _ws_display_Remove {
    char dummy_field;
} ws_display_Remove;

/* *
 Write writes content to a display. */
typedef struct _ws_display_Write {
    char message[1024]; /* * Monospace text message */
} ws_display_Write;

/* *
 Add adds a new display or replaces an existing one.
 Used as ws.display.Add in i2c.proto for I2C-based displays.

 Known driver strings (migrated from DisplayDriver enum):
 EPD drivers: "SSD1680", "ILI0373", "UC8253", "UC8179", "UC8151", "SSD1683"
 TFT drivers: "ST7789"
 OLED drivers: "SSD1306", "SSD1305", "SH1106", "SH1107"
 LED Backpack drivers: "HT16K33"
 Character LCD drivers: "MCP23008", "PCF8574"

 Panel naming conventions (for E-Paper displays with same driver, different panels):
 Format: "{size}-{resolution}-{color_mode}" or "adafruit-{product_id}"
 Examples: "5.83-648x480-mono", "4.2-300x400-gray", "adafruit-6397"

To shorten the component names, Brent and I discussed using sub folders for class/driver/resolution, then maybe colour/panel type, but not clear cut.
displays/oled/ssd1306/
displays/epd/ssd1680/250x122/mono/    [2.13" e-ink featherwing which has a panel variant with the same driver and no distinguishing features rev2024] */
typedef struct _ws_display_Add {
    ws_display_DisplayClass type; /* * The type of display */
    char driver[32]; /* * Driver name (e.g., "UC8179", "SSD1306", "HT16K33") */
    char panel[32]; /* * Panel identifier for same driver with different configs */
    pb_size_t which_interface_type;
    union {
        ws_display_EpdSpiConfig spi_epd; /* * SPI configuration for EPD. */
        ws_display_TftSpiConfig spi_tft; /* * SPI configuration for TFT. */
        ws_i2c_DeviceDescriptor i2c; /* * I2C configuration for OLED/LED/LCD displays. */
        ws_display_TtlRgb666PinConfig ttl_rgb666; /* * RGB666 configuration for Qualia. */
        ws_display_I8080PinConfig i8080; /* * i8080 8-bit parallel for T-DisplayS3/Memento. */
        ws_display_DsiInterfaceConfig dsi; /* * DSI configuration for MIPI DSI displays (e.g., ESP32-P4). */
    } interface_type;
    pb_size_t which_config;
    union {
        ws_display_EPDConfig config_epd; /* * Configuration for EPD. */
        ws_display_LedBackpackConfig config_led; /* * Configuration for LED Backpack. */
        ws_display_CharLcdConfig config_char_lcd; /* * Configuration for Character LCD. */
        ws_display_DisplayProperties config_display; /* * Configuration for Generic display (w/h/r/txtSz). */
    } config;
    bool has_write;
    ws_display_Write write; /* * Optional initial write for a display, used during check-in. */
    bool has_backlight;
    ws_display_BacklightConfig backlight; /* * Optional backlight configuration (shared across display types). */
} ws_display_Add;

/* *
 BrokerToDevice message envelope */
typedef struct _ws_display_B2D {
    pb_callback_t name; /* * Unique instance identifier for the display. */
    pb_size_t which_payload;
    union {
        ws_display_Add add;
        ws_display_Remove remove;
        ws_display_Write write;
    } payload;
} ws_display_B2D;

/* *
 AddedOrReplaced confirms a display was added or replaced. */
typedef struct _ws_display_AddedOrReplaced {
    char dummy_field;
} ws_display_AddedOrReplaced;

/* *
 Removed confirms a display was removed. */
typedef struct _ws_display_Removed {
    char dummy_field;
} ws_display_Removed;

/* *
 DeviceToBroker message envelope */
typedef struct _ws_display_D2B {
    pb_callback_t name; /* * Unique instance identifier for the display. */
    bool did_succeed; /* * Indicates if the requested operation succeeded. */
    pb_size_t which_payload;
    union {
        ws_display_AddedOrReplaced added_or_replaced;
        ws_display_Removed removed;
    } payload;
} ws_display_D2B;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ws_display_DisplayClass_MIN ws_display_DisplayClass_DISPLAY_CLASS_UNSPECIFIED
#define _ws_display_DisplayClass_MAX ws_display_DisplayClass_DISPLAY_CLASS_CHAR_LCD
#define _ws_display_DisplayClass_ARRAYSIZE ((ws_display_DisplayClass)(ws_display_DisplayClass_DISPLAY_CLASS_CHAR_LCD+1))

#define _ws_display_EPDMode_MIN ws_display_EPDMode_EPD_MODE_UNSPECIFIED
#define _ws_display_EPDMode_MAX ws_display_EPDMode_EPD_MODE_MONO
#define _ws_display_EPDMode_ARRAYSIZE ((ws_display_EPDMode)(ws_display_EPDMode_EPD_MODE_MONO+1))

#define _ws_display_LedBackpackAlignment_MIN ws_display_LedBackpackAlignment_LBA_UNSPECIFIED
#define _ws_display_LedBackpackAlignment_MAX ws_display_LedBackpackAlignment_LBA_RIGHT
#define _ws_display_LedBackpackAlignment_ARRAYSIZE ((ws_display_LedBackpackAlignment)(ws_display_LedBackpackAlignment_LBA_RIGHT+1))





#define ws_display_EPDConfig_mode_ENUMTYPE ws_display_EPDMode

#define ws_display_LedBackpackConfig_alignment_ENUMTYPE ws_display_LedBackpackAlignment







#define ws_display_Add_type_ENUMTYPE ws_display_DisplayClass






/* Initializer values for message structs */
#define ws_display_B2D_init_default              {{{NULL}, NULL}, 0, {ws_display_Add_init_default}}
#define ws_display_D2B_init_default              {{{NULL}, NULL}, 0, 0, {ws_display_AddedOrReplaced_init_default}}
#define ws_display_DisplayProperties_init_default {0, 0, 0, 0}
#define ws_display_SpiPinConfig_init_default     {0, "", "", "", "", "", ""}
#define ws_display_EpdSpiConfig_init_default     {false, ws_display_SpiPinConfig_init_default, 0, 0}
#define ws_display_EPDConfig_init_default        {_ws_display_EPDMode_MIN, false, ws_display_DisplayProperties_init_default}
#define ws_display_LedBackpackConfig_init_default {0, _ws_display_LedBackpackAlignment_MIN}
#define ws_display_CharLcdConfig_init_default    {0, 0}
#define ws_display_TftSpiConfig_init_default     {false, ws_display_SpiPinConfig_init_default}
#define ws_display_TtlRgb666PinConfig_init_default {"", "", "", "", "", "", "", "", ""}
#define ws_display_I8080PinConfig_init_default   {"", "", "", "", "", "", "", "", "", "", ""}
#define ws_display_DsiInterfaceConfig_init_default {0, 0}
#define ws_display_BacklightConfig_init_default  {0, {ws_digitalio_Add_init_default}}
#define ws_display_Add_init_default              {_ws_display_DisplayClass_MIN, "", "", 0, {ws_display_EpdSpiConfig_init_default}, 0, {ws_display_EPDConfig_init_default}, false, ws_display_Write_init_default, false, ws_display_BacklightConfig_init_default}
#define ws_display_Remove_init_default           {0}
#define ws_display_Write_init_default            {""}
#define ws_display_AddedOrReplaced_init_default  {0}
#define ws_display_Removed_init_default          {0}
#define ws_display_B2D_init_zero                 {{{NULL}, NULL}, 0, {ws_display_Add_init_zero}}
#define ws_display_D2B_init_zero                 {{{NULL}, NULL}, 0, 0, {ws_display_AddedOrReplaced_init_zero}}
#define ws_display_DisplayProperties_init_zero   {0, 0, 0, 0}
#define ws_display_SpiPinConfig_init_zero        {0, "", "", "", "", "", ""}
#define ws_display_EpdSpiConfig_init_zero        {false, ws_display_SpiPinConfig_init_zero, 0, 0}
#define ws_display_EPDConfig_init_zero           {_ws_display_EPDMode_MIN, false, ws_display_DisplayProperties_init_zero}
#define ws_display_LedBackpackConfig_init_zero   {0, _ws_display_LedBackpackAlignment_MIN}
#define ws_display_CharLcdConfig_init_zero       {0, 0}
#define ws_display_TftSpiConfig_init_zero        {false, ws_display_SpiPinConfig_init_zero}
#define ws_display_TtlRgb666PinConfig_init_zero  {"", "", "", "", "", "", "", "", ""}
#define ws_display_I8080PinConfig_init_zero      {"", "", "", "", "", "", "", "", "", "", ""}
#define ws_display_DsiInterfaceConfig_init_zero  {0, 0}
#define ws_display_BacklightConfig_init_zero     {0, {ws_digitalio_Add_init_zero}}
#define ws_display_Add_init_zero                 {_ws_display_DisplayClass_MIN, "", "", 0, {ws_display_EpdSpiConfig_init_zero}, 0, {ws_display_EPDConfig_init_zero}, false, ws_display_Write_init_zero, false, ws_display_BacklightConfig_init_zero}
#define ws_display_Remove_init_zero              {0}
#define ws_display_Write_init_zero               {""}
#define ws_display_AddedOrReplaced_init_zero     {0}
#define ws_display_Removed_init_zero             {0}

/* Field tags (for use in manual encoding/decoding) */
#define ws_display_DisplayProperties_width_tag   1
#define ws_display_DisplayProperties_height_tag  2
#define ws_display_DisplayProperties_rotation_tag 3
#define ws_display_DisplayProperties_text_size_tag 4
#define ws_display_SpiPinConfig_bus_tag          1
#define ws_display_SpiPinConfig_pin_mosi_tag     2
#define ws_display_SpiPinConfig_pin_sck_tag      3
#define ws_display_SpiPinConfig_pin_miso_tag     4
#define ws_display_SpiPinConfig_pin_cs_tag       5
#define ws_display_SpiPinConfig_pin_dc_tag       6
#define ws_display_SpiPinConfig_pin_rst_tag      7
#define ws_display_EpdSpiConfig_spi_pins_tag     1
#define ws_display_EpdSpiConfig_pin_sram_cs_tag  2
#define ws_display_EpdSpiConfig_pin_busy_tag     3
#define ws_display_EPDConfig_mode_tag            1
#define ws_display_EPDConfig_properties_tag      2
#define ws_display_LedBackpackConfig_brightness_tag 1
#define ws_display_LedBackpackConfig_alignment_tag 2
#define ws_display_CharLcdConfig_rows_tag        1
#define ws_display_CharLcdConfig_columns_tag     2
#define ws_display_TftSpiConfig_spi_pins_tag     1
#define ws_display_TtlRgb666PinConfig_pin_r0_tag 1
#define ws_display_TtlRgb666PinConfig_pin_r1_tag 2
#define ws_display_TtlRgb666PinConfig_pin_r2_tag 3
#define ws_display_TtlRgb666PinConfig_pin_g0_tag 4
#define ws_display_TtlRgb666PinConfig_pin_g1_tag 5
#define ws_display_TtlRgb666PinConfig_pin_g2_tag 6
#define ws_display_TtlRgb666PinConfig_pin_b0_tag 7
#define ws_display_TtlRgb666PinConfig_pin_b1_tag 8
#define ws_display_TtlRgb666PinConfig_pin_b2_tag 9
#define ws_display_I8080PinConfig_pin_d0_tag     1
#define ws_display_I8080PinConfig_pin_d1_tag     2
#define ws_display_I8080PinConfig_pin_d2_tag     3
#define ws_display_I8080PinConfig_pin_d3_tag     4
#define ws_display_I8080PinConfig_pin_d4_tag     5
#define ws_display_I8080PinConfig_pin_d5_tag     6
#define ws_display_I8080PinConfig_pin_d6_tag     7
#define ws_display_I8080PinConfig_pin_d7_tag     8
#define ws_display_I8080PinConfig_pin_cs_tag     9
#define ws_display_I8080PinConfig_pin_dc_tag     10
#define ws_display_I8080PinConfig_pin_rst_tag    11
#define ws_display_DsiInterfaceConfig_bus_tag    1
#define ws_display_DsiInterfaceConfig_pin_rst_tag 2
#define ws_display_BacklightConfig_backlight_digital_tag 1
#define ws_display_BacklightConfig_backlight_pwm_tag 2
#define ws_display_Write_message_tag             1
#define ws_display_Add_type_tag                  1
#define ws_display_Add_driver_tag                2
#define ws_display_Add_panel_tag                 3
#define ws_display_Add_spi_epd_tag               5
#define ws_display_Add_spi_tft_tag               6
#define ws_display_Add_i2c_tag                   7
#define ws_display_Add_ttl_rgb666_tag            8
#define ws_display_Add_i8080_tag                 9
#define ws_display_Add_dsi_tag                   10
#define ws_display_Add_config_epd_tag            11
#define ws_display_Add_config_led_tag            14
#define ws_display_Add_config_char_lcd_tag       15
#define ws_display_Add_config_display_tag        18
#define ws_display_Add_write_tag                 19
#define ws_display_Add_backlight_tag             20
#define ws_display_B2D_name_tag                  1
#define ws_display_B2D_add_tag                   2
#define ws_display_B2D_remove_tag                3
#define ws_display_B2D_write_tag                 4
#define ws_display_D2B_name_tag                  1
#define ws_display_D2B_did_succeed_tag           2
#define ws_display_D2B_added_or_replaced_tag     3
#define ws_display_D2B_removed_tag               4

/* Struct field encoding specification for nanopb */
#define ws_display_B2D_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,add,payload.add),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,remove,payload.remove),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,write,payload.write),   4)
#define ws_display_B2D_CALLBACK pb_default_field_callback
#define ws_display_B2D_DEFAULT NULL
#define ws_display_B2D_payload_add_MSGTYPE ws_display_Add
#define ws_display_B2D_payload_remove_MSGTYPE ws_display_Remove
#define ws_display_B2D_payload_write_MSGTYPE ws_display_Write

#define ws_display_D2B_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, BOOL,     did_succeed,       2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,added_or_replaced,payload.added_or_replaced),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,removed,payload.removed),   4)
#define ws_display_D2B_CALLBACK pb_default_field_callback
#define ws_display_D2B_DEFAULT NULL
#define ws_display_D2B_payload_added_or_replaced_MSGTYPE ws_display_AddedOrReplaced
#define ws_display_D2B_payload_removed_MSGTYPE ws_display_Removed

#define ws_display_DisplayProperties_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    width,             1) \
X(a, STATIC,   SINGULAR, INT32,    height,            2) \
X(a, STATIC,   SINGULAR, INT32,    rotation,          3) \
X(a, STATIC,   SINGULAR, INT32,    text_size,         4)
#define ws_display_DisplayProperties_CALLBACK NULL
#define ws_display_DisplayProperties_DEFAULT NULL

#define ws_display_SpiPinConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    bus,               1) \
X(a, STATIC,   SINGULAR, STRING,   pin_mosi,          2) \
X(a, STATIC,   SINGULAR, STRING,   pin_sck,           3) \
X(a, STATIC,   SINGULAR, STRING,   pin_miso,          4) \
X(a, STATIC,   SINGULAR, STRING,   pin_cs,            5) \
X(a, STATIC,   SINGULAR, STRING,   pin_dc,            6) \
X(a, STATIC,   SINGULAR, STRING,   pin_rst,           7)
#define ws_display_SpiPinConfig_CALLBACK NULL
#define ws_display_SpiPinConfig_DEFAULT NULL

#define ws_display_EpdSpiConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  spi_pins,          1) \
X(a, STATIC,   SINGULAR, UINT32,   pin_sram_cs,       2) \
X(a, STATIC,   SINGULAR, UINT32,   pin_busy,          3)
#define ws_display_EpdSpiConfig_CALLBACK NULL
#define ws_display_EpdSpiConfig_DEFAULT NULL
#define ws_display_EpdSpiConfig_spi_pins_MSGTYPE ws_display_SpiPinConfig

#define ws_display_EPDConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  properties,        2)
#define ws_display_EPDConfig_CALLBACK NULL
#define ws_display_EPDConfig_DEFAULT NULL
#define ws_display_EPDConfig_properties_MSGTYPE ws_display_DisplayProperties

#define ws_display_LedBackpackConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    brightness,        1) \
X(a, STATIC,   SINGULAR, UENUM,    alignment,         2)
#define ws_display_LedBackpackConfig_CALLBACK NULL
#define ws_display_LedBackpackConfig_DEFAULT NULL

#define ws_display_CharLcdConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   rows,              1) \
X(a, STATIC,   SINGULAR, UINT32,   columns,           2)
#define ws_display_CharLcdConfig_CALLBACK NULL
#define ws_display_CharLcdConfig_DEFAULT NULL

#define ws_display_TftSpiConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  spi_pins,          1)
#define ws_display_TftSpiConfig_CALLBACK NULL
#define ws_display_TftSpiConfig_DEFAULT NULL
#define ws_display_TftSpiConfig_spi_pins_MSGTYPE ws_display_SpiPinConfig

#define ws_display_TtlRgb666PinConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin_r0,            1) \
X(a, STATIC,   SINGULAR, STRING,   pin_r1,            2) \
X(a, STATIC,   SINGULAR, STRING,   pin_r2,            3) \
X(a, STATIC,   SINGULAR, STRING,   pin_g0,            4) \
X(a, STATIC,   SINGULAR, STRING,   pin_g1,            5) \
X(a, STATIC,   SINGULAR, STRING,   pin_g2,            6) \
X(a, STATIC,   SINGULAR, STRING,   pin_b0,            7) \
X(a, STATIC,   SINGULAR, STRING,   pin_b1,            8) \
X(a, STATIC,   SINGULAR, STRING,   pin_b2,            9)
#define ws_display_TtlRgb666PinConfig_CALLBACK NULL
#define ws_display_TtlRgb666PinConfig_DEFAULT NULL

#define ws_display_I8080PinConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin_d0,            1) \
X(a, STATIC,   SINGULAR, STRING,   pin_d1,            2) \
X(a, STATIC,   SINGULAR, STRING,   pin_d2,            3) \
X(a, STATIC,   SINGULAR, STRING,   pin_d3,            4) \
X(a, STATIC,   SINGULAR, STRING,   pin_d4,            5) \
X(a, STATIC,   SINGULAR, STRING,   pin_d5,            6) \
X(a, STATIC,   SINGULAR, STRING,   pin_d6,            7) \
X(a, STATIC,   SINGULAR, STRING,   pin_d7,            8) \
X(a, STATIC,   SINGULAR, STRING,   pin_cs,            9) \
X(a, STATIC,   SINGULAR, STRING,   pin_dc,           10) \
X(a, STATIC,   SINGULAR, STRING,   pin_rst,          11)
#define ws_display_I8080PinConfig_CALLBACK NULL
#define ws_display_I8080PinConfig_DEFAULT NULL

#define ws_display_DsiInterfaceConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   bus,               1) \
X(a, STATIC,   SINGULAR, UINT32,   pin_rst,           2)
#define ws_display_DsiInterfaceConfig_CALLBACK NULL
#define ws_display_DsiInterfaceConfig_DEFAULT NULL

#define ws_display_BacklightConfig_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (backlight_add,backlight_digital,backlight_add.backlight_digital),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (backlight_add,backlight_pwm,backlight_add.backlight_pwm),   2)
#define ws_display_BacklightConfig_CALLBACK NULL
#define ws_display_BacklightConfig_DEFAULT NULL
#define ws_display_BacklightConfig_backlight_add_backlight_digital_MSGTYPE ws_digitalio_Add
#define ws_display_BacklightConfig_backlight_add_backlight_pwm_MSGTYPE ws_pwm_Add

#define ws_display_Add_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, STRING,   driver,            2) \
X(a, STATIC,   SINGULAR, STRING,   panel,             3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (interface_type,spi_epd,interface_type.spi_epd),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (interface_type,spi_tft,interface_type.spi_tft),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (interface_type,i2c,interface_type.i2c),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (interface_type,ttl_rgb666,interface_type.ttl_rgb666),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (interface_type,i8080,interface_type.i8080),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (interface_type,dsi,interface_type.dsi),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config,config_epd,config.config_epd),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config,config_led,config.config_led),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config,config_char_lcd,config.config_char_lcd),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config,config_display,config.config_display),  18) \
X(a, STATIC,   OPTIONAL, MESSAGE,  write,            19) \
X(a, STATIC,   OPTIONAL, MESSAGE,  backlight,        20)
#define ws_display_Add_CALLBACK NULL
#define ws_display_Add_DEFAULT NULL
#define ws_display_Add_interface_type_spi_epd_MSGTYPE ws_display_EpdSpiConfig
#define ws_display_Add_interface_type_spi_tft_MSGTYPE ws_display_TftSpiConfig
#define ws_display_Add_interface_type_i2c_MSGTYPE ws_i2c_DeviceDescriptor
#define ws_display_Add_interface_type_ttl_rgb666_MSGTYPE ws_display_TtlRgb666PinConfig
#define ws_display_Add_interface_type_i8080_MSGTYPE ws_display_I8080PinConfig
#define ws_display_Add_interface_type_dsi_MSGTYPE ws_display_DsiInterfaceConfig
#define ws_display_Add_config_config_epd_MSGTYPE ws_display_EPDConfig
#define ws_display_Add_config_config_led_MSGTYPE ws_display_LedBackpackConfig
#define ws_display_Add_config_config_char_lcd_MSGTYPE ws_display_CharLcdConfig
#define ws_display_Add_config_config_display_MSGTYPE ws_display_DisplayProperties
#define ws_display_Add_write_MSGTYPE ws_display_Write
#define ws_display_Add_backlight_MSGTYPE ws_display_BacklightConfig

#define ws_display_Remove_FIELDLIST(X, a) \

#define ws_display_Remove_CALLBACK NULL
#define ws_display_Remove_DEFAULT NULL

#define ws_display_Write_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message,           1)
#define ws_display_Write_CALLBACK NULL
#define ws_display_Write_DEFAULT NULL

#define ws_display_AddedOrReplaced_FIELDLIST(X, a) \

#define ws_display_AddedOrReplaced_CALLBACK NULL
#define ws_display_AddedOrReplaced_DEFAULT NULL

#define ws_display_Removed_FIELDLIST(X, a) \

#define ws_display_Removed_CALLBACK NULL
#define ws_display_Removed_DEFAULT NULL

extern const pb_msgdesc_t ws_display_B2D_msg;
extern const pb_msgdesc_t ws_display_D2B_msg;
extern const pb_msgdesc_t ws_display_DisplayProperties_msg;
extern const pb_msgdesc_t ws_display_SpiPinConfig_msg;
extern const pb_msgdesc_t ws_display_EpdSpiConfig_msg;
extern const pb_msgdesc_t ws_display_EPDConfig_msg;
extern const pb_msgdesc_t ws_display_LedBackpackConfig_msg;
extern const pb_msgdesc_t ws_display_CharLcdConfig_msg;
extern const pb_msgdesc_t ws_display_TftSpiConfig_msg;
extern const pb_msgdesc_t ws_display_TtlRgb666PinConfig_msg;
extern const pb_msgdesc_t ws_display_I8080PinConfig_msg;
extern const pb_msgdesc_t ws_display_DsiInterfaceConfig_msg;
extern const pb_msgdesc_t ws_display_BacklightConfig_msg;
extern const pb_msgdesc_t ws_display_Add_msg;
extern const pb_msgdesc_t ws_display_Remove_msg;
extern const pb_msgdesc_t ws_display_Write_msg;
extern const pb_msgdesc_t ws_display_AddedOrReplaced_msg;
extern const pb_msgdesc_t ws_display_Removed_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ws_display_B2D_fields &ws_display_B2D_msg
#define ws_display_D2B_fields &ws_display_D2B_msg
#define ws_display_DisplayProperties_fields &ws_display_DisplayProperties_msg
#define ws_display_SpiPinConfig_fields &ws_display_SpiPinConfig_msg
#define ws_display_EpdSpiConfig_fields &ws_display_EpdSpiConfig_msg
#define ws_display_EPDConfig_fields &ws_display_EPDConfig_msg
#define ws_display_LedBackpackConfig_fields &ws_display_LedBackpackConfig_msg
#define ws_display_CharLcdConfig_fields &ws_display_CharLcdConfig_msg
#define ws_display_TftSpiConfig_fields &ws_display_TftSpiConfig_msg
#define ws_display_TtlRgb666PinConfig_fields &ws_display_TtlRgb666PinConfig_msg
#define ws_display_I8080PinConfig_fields &ws_display_I8080PinConfig_msg
#define ws_display_DsiInterfaceConfig_fields &ws_display_DsiInterfaceConfig_msg
#define ws_display_BacklightConfig_fields &ws_display_BacklightConfig_msg
#define ws_display_Add_fields &ws_display_Add_msg
#define ws_display_Remove_fields &ws_display_Remove_msg
#define ws_display_Write_fields &ws_display_Write_msg
#define ws_display_AddedOrReplaced_fields &ws_display_AddedOrReplaced_msg
#define ws_display_Removed_fields &ws_display_Removed_msg

/* Maximum encoded size of messages (where known) */
#if defined(ws_digitalio_Add_size)
union ws_display_B2D_payload_size_union {char f2[(1240 + sizeof(union ws_display_BacklightConfig_backlight_add_size_union))]; char f0[1029];};
#endif
#if defined(ws_digitalio_Add_size)
union ws_display_BacklightConfig_backlight_add_size_union {char f1[(6 + ws_digitalio_Add_size)]; char f0[53];};
#endif
/* ws_display_B2D_size depends on runtime parameters */
/* ws_display_D2B_size depends on runtime parameters */
#define ws_display_AddedOrReplaced_size          0
#define ws_display_CharLcdConfig_size            12
#define ws_display_DisplayProperties_size        44
#define ws_display_DsiInterfaceConfig_size       12
#define ws_display_EPDConfig_size                48
#define ws_display_EpdSpiConfig_size             67
#define ws_display_I8080PinConfig_size           77
#define ws_display_LedBackpackConfig_size        13
#define ws_display_Remove_size                   0
#define ws_display_Removed_size                  0
#define ws_display_SpiPinConfig_size             53
#define ws_display_TftSpiConfig_size             55
#define ws_display_TtlRgb666PinConfig_size       63
#define ws_display_Write_size                    1026
#if defined(ws_digitalio_Add_size)
#define WS_DISPLAY_DISPLAY_PB_H_MAX_SIZE         ws_display_Add_size
#define ws_display_Add_size                      (1234 + sizeof(union ws_display_BacklightConfig_backlight_add_size_union))
#define ws_display_BacklightConfig_size          (0 + sizeof(union ws_display_BacklightConfig_backlight_add_size_union))
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
