/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Fri May 29 19:14:08 2026. */

#include "display.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_display_B2D, ws_display_B2D, 2)


PB_BIND(ws_display_DisplayProperties, ws_display_DisplayProperties, AUTO)


PB_BIND(ws_display_EpdSpiDescriptor, ws_display_EpdSpiDescriptor, AUTO)


PB_BIND(ws_display_EPDConfig, ws_display_EPDConfig, AUTO)


PB_BIND(ws_display_LedBackpackConfig, ws_display_LedBackpackConfig, AUTO)


PB_BIND(ws_display_CharLcdConfig, ws_display_CharLcdConfig, AUTO)


PB_BIND(ws_display_TftSpiDescriptor, ws_display_TftSpiDescriptor, AUTO)


PB_BIND(ws_display_TtlRgb666PinDescriptor, ws_display_TtlRgb666PinDescriptor, AUTO)


PB_BIND(ws_display_I8080PinDescriptor, ws_display_I8080PinDescriptor, AUTO)


PB_BIND(ws_display_DsiInterfaceDescriptor, ws_display_DsiInterfaceDescriptor, AUTO)


PB_BIND(ws_display_BacklightConfig, ws_display_BacklightConfig, AUTO)


PB_BIND(ws_display_Add, ws_display_Add, 2)


PB_BIND(ws_display_Remove, ws_display_Remove, AUTO)


PB_BIND(ws_display_Write, ws_display_Write, 2)






