/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Wed Aug 21 15:48:44 2024. */

#include "error.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_error_Error, wippersnapper_error_Error, AUTO)



