/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Fri May 29 19:14:08 2026. */

#include "error.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_error_ErrorIOBan, ws_error_ErrorIOBan, AUTO)


PB_BIND(ws_error_ErrorIOThrottle, ws_error_ErrorIOThrottle, AUTO)


PB_BIND(ws_error_B2D, ws_error_B2D, AUTO)


PB_BIND(ws_error_D2B, ws_error_D2B, AUTO)


PB_BIND(ws_error_BanError, ws_error_BanError, AUTO)


PB_BIND(ws_error_ThrottleError, ws_error_ThrottleError, AUTO)


PB_BIND(ws_error_DeviceError, ws_error_DeviceError, AUTO)


PB_BIND(ws_error_ComponentError, ws_error_ComponentError, AUTO)



