/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 at Tue Dec 30 19:36:24 2025. */

#ifndef PB_WS_ERROR_ERROR_PB_H_INCLUDED
#define PB_WS_ERROR_ERROR_PB_H_INCLUDED
#include <pb.h>
#include "i2c.pb.h"
#include "uart.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* ComponentType
 Enum representing the class/type of component
 that an error message is associated with. */
typedef enum _ws_error_ComponentType {
    ws_error_ComponentType_COMPONENT_TYPE_UNSPECIFIED = 0, /* * Invalid Component Type. */
    ws_error_ComponentType_COMPONENT_TYPE_DIGITALIO = 1, /* * Digital IO Component. */
    ws_error_ComponentType_COMPONENT_TYPE_ANALOGIO = 2, /* * Analog IO Component. */
    ws_error_ComponentType_COMPONENT_TYPE_PWM = 3, /* * PWM Component. */
    ws_error_ComponentType_COMPONENT_TYPE_SERVO = 4, /* * Servo Component. */
    ws_error_ComponentType_COMPONENT_TYPE_PIXELS = 5, /* * Pixels Component. */
    ws_error_ComponentType_COMPONENT_TYPE_DS18X20 = 6, /* * DS18X20 Component. */
    ws_error_ComponentType_COMPONENT_TYPE_UART = 7, /* * UART Component. */
    ws_error_ComponentType_COMPONENT_TYPE_I2C = 8, /* * I2C Component. */
    ws_error_ComponentType_COMPONENT_TYPE_GPS = 9 /* * GPS Component. */
} ws_error_ComponentType;

/* Struct definitions */
/* ErrorIOBan
 The ErrorIOBan message is sent from the broker to a device
 to inform the device that it has been banned from IO. */
typedef struct _ws_error_ErrorIOBan {
    char dummy_field;
} ws_error_ErrorIOBan;

/* ErrorIOThrottle
 The ErrorIOThrottle message is sent from the broker to a device
 to inform the device that it has been rate-limited by IO. */
typedef struct _ws_error_ErrorIOThrottle {
    uint32_t timeout;
} ws_error_ErrorIOThrottle;

/* ErrorB2D
 The ErrorB2D message is sent from the broker to a device
 to inform the device of an error that has occurred
 from IO. */
typedef struct _ws_error_ErrorB2D {
    pb_callback_t cb_payload;
    pb_size_t which_payload;
    union {
        ws_error_ErrorIOBan io_ban;
        ws_error_ErrorIOThrottle io_throttle;
    } payload;
} ws_error_ErrorB2D;

/* ErrorD2B
 The ErrorD2B message is sent from a device to the broker
 to report an error that has occurred on a specific component.
 It contains a way to identify the specific component along
 with a human-readable error message. */
typedef struct _ws_error_ErrorD2B {
    ws_error_ComponentType type;
    pb_size_t which_component_id;
    union {
        pb_callback_t pin;
        ws_i2c_DeviceDescriptor i2c;
        ws_uart_Descriptor uart;
    } component_id;
    pb_callback_t error;
} ws_error_ErrorD2B;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ws_error_ComponentType_MIN ws_error_ComponentType_COMPONENT_TYPE_UNSPECIFIED
#define _ws_error_ComponentType_MAX ws_error_ComponentType_COMPONENT_TYPE_GPS
#define _ws_error_ComponentType_ARRAYSIZE ((ws_error_ComponentType)(ws_error_ComponentType_COMPONENT_TYPE_GPS+1))




#define ws_error_ErrorD2B_type_ENUMTYPE ws_error_ComponentType


/* Initializer values for message structs */
#define ws_error_ErrorIOBan_init_default         {0}
#define ws_error_ErrorIOThrottle_init_default    {0}
#define ws_error_ErrorB2D_init_default           {{{NULL}, NULL}, 0, {ws_error_ErrorIOBan_init_default}}
#define ws_error_ErrorD2B_init_default           {_ws_error_ComponentType_MIN, 0, {{{NULL}, NULL}}, {{NULL}, NULL}}
#define ws_error_ErrorIOBan_init_zero            {0}
#define ws_error_ErrorIOThrottle_init_zero       {0}
#define ws_error_ErrorB2D_init_zero              {{{NULL}, NULL}, 0, {ws_error_ErrorIOBan_init_zero}}
#define ws_error_ErrorD2B_init_zero              {_ws_error_ComponentType_MIN, 0, {{{NULL}, NULL}}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define ws_error_ErrorIOThrottle_timeout_tag     1
#define ws_error_ErrorB2D_io_ban_tag             1
#define ws_error_ErrorB2D_io_throttle_tag        2
#define ws_error_ErrorD2B_type_tag               1
#define ws_error_ErrorD2B_pin_tag                2
#define ws_error_ErrorD2B_i2c_tag                3
#define ws_error_ErrorD2B_uart_tag               4
#define ws_error_ErrorD2B_error_tag              5

/* Struct field encoding specification for nanopb */
#define ws_error_ErrorIOBan_FIELDLIST(X, a) \

#define ws_error_ErrorIOBan_CALLBACK NULL
#define ws_error_ErrorIOBan_DEFAULT NULL

#define ws_error_ErrorIOThrottle_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timeout,           1)
#define ws_error_ErrorIOThrottle_CALLBACK NULL
#define ws_error_ErrorIOThrottle_DEFAULT NULL

#define ws_error_ErrorB2D_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,io_ban,payload.io_ban),   1) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,io_throttle,payload.io_throttle),   2)
#define ws_error_ErrorB2D_CALLBACK NULL
#define ws_error_ErrorB2D_DEFAULT NULL
#define ws_error_ErrorB2D_payload_io_ban_MSGTYPE ws_error_ErrorIOBan
#define ws_error_ErrorB2D_payload_io_throttle_MSGTYPE ws_error_ErrorIOThrottle

#define ws_error_ErrorD2B_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, CALLBACK, ONEOF,    STRING,   (component_id,pin,component_id.pin),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (component_id,i2c,component_id.i2c),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (component_id,uart,component_id.uart),   4) \
X(a, CALLBACK, SINGULAR, STRING,   error,             5)
#define ws_error_ErrorD2B_CALLBACK pb_default_field_callback
#define ws_error_ErrorD2B_DEFAULT NULL
#define ws_error_ErrorD2B_component_id_i2c_MSGTYPE ws_i2c_DeviceDescriptor
#define ws_error_ErrorD2B_component_id_uart_MSGTYPE ws_uart_Descriptor

extern const pb_msgdesc_t ws_error_ErrorIOBan_msg;
extern const pb_msgdesc_t ws_error_ErrorIOThrottle_msg;
extern const pb_msgdesc_t ws_error_ErrorB2D_msg;
extern const pb_msgdesc_t ws_error_ErrorD2B_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ws_error_ErrorIOBan_fields &ws_error_ErrorIOBan_msg
#define ws_error_ErrorIOThrottle_fields &ws_error_ErrorIOThrottle_msg
#define ws_error_ErrorB2D_fields &ws_error_ErrorB2D_msg
#define ws_error_ErrorD2B_fields &ws_error_ErrorD2B_msg

/* Maximum encoded size of messages (where known) */
/* ws_error_ErrorD2B_size depends on runtime parameters */
#define WS_ERROR_ERROR_PB_H_MAX_SIZE             ws_error_ErrorB2D_size
#define ws_error_ErrorB2D_size                   8
#define ws_error_ErrorIOBan_size                 0
#define ws_error_ErrorIOThrottle_size            6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
