/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 at Thu Mar 12 16:26:13 2026. */

#include "error.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_error_ErrorIOBan, ws_error_ErrorIOBan, AUTO)


PB_BIND(ws_error_ErrorIOThrottle, ws_error_ErrorIOThrottle, AUTO)


PB_BIND(ws_error_ErrorB2D, ws_error_ErrorB2D, AUTO)


PB_BIND(ws_error_ErrorD2B, ws_error_ErrorD2B, AUTO)





