/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 at Tue Jun  2 20:59:40 2026. */

#ifndef PB_WS_ERROR_ERROR_PB_H_INCLUDED
#define PB_WS_ERROR_ERROR_PB_H_INCLUDED
#include <pb.h>
#include "i2c.pb.h"
#include "spi.pb.h"
#include "uart.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* ErrorIOBan
 The ErrorIOBan message is sent from the broker to a device
 to inform the device that it has been banned from IO. */
typedef struct _ws_error_ErrorIOBan {
    char dummy_field;
} ws_error_ErrorIOBan;

/* ErrorIOThrottle
 The ErrorIOThrottle message is sent from the broker to a device
 to inform the device that it has been rate-limited by IO. */
typedef struct _ws_error_ErrorIOThrottle {
    uint32_t timeout;
} ws_error_ErrorIOThrottle;

/* BanError
 The BanError message is sent from the broker to a device
 to inform the device that it has been banned from IO. */
typedef struct _ws_error_BanError {
    char dummy_field;
} ws_error_BanError;

/* ThrottleError
 The ThrottleError message is sent from the broker to a device
 to inform the device that it has been rate-limited by IO. */
typedef struct _ws_error_ThrottleError {
    uint32_t timeout; /* how long to wait before trying again */
} ws_error_ThrottleError;

/* ErrorB2D
 The ErrorB2D message is sent from the broker to a device
 to inform the device of an error that has occurred
 from IO. */
typedef struct _ws_error_B2D {
    pb_callback_t cb_payload;
    pb_size_t which_payload;
    union {
        ws_error_BanError ban;
        ws_error_ThrottleError throttle;
    } payload;
} ws_error_B2D;

/* DeviceError represents a device-level issue */
typedef struct _ws_error_DeviceError {
    pb_callback_t message; /* explanation of the error */
    pb_size_t which_descriptor;
    union {
        ws_i2c_AddressSpace i2c_bus; /* an i2c bus error */
    } descriptor;
} ws_error_DeviceError;

/* ComponentError represents a specific error about a specific component. */
typedef struct _ws_error_ComponentError {
    pb_callback_t message; /* explanation of the error */
    pb_size_t which_descriptor;
    union {
        pb_callback_t pin; /* digital, analog, pwm, servo, pixel, ds18x20, pixel */
        ws_i2c_Descriptor i2c; /* i2c, gps, display, expander */
        ws_uart_Descriptor uart; /* uart */
        ws_spi_Descriptor spi; /* SPI displays */
    } descriptor;
} ws_error_ComponentError;

/* D2B
 The D2B message is sent from a device to the broker
 to report an error that has occurred on a specific component.
 It contains a way to identify the specific component along
 with a human-readable error message. */
typedef struct _ws_error_D2B {
    pb_size_t which_payload;
    union {
        ws_error_DeviceError device;
        ws_error_ComponentError component;
    } payload;
} ws_error_D2B;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ws_error_ErrorIOBan_init_default         {0}
#define ws_error_ErrorIOThrottle_init_default    {0}
#define ws_error_B2D_init_default                {{{NULL}, NULL}, 0, {ws_error_BanError_init_default}}
#define ws_error_D2B_init_default                {0, {ws_error_DeviceError_init_default}}
#define ws_error_BanError_init_default           {0}
#define ws_error_ThrottleError_init_default      {0}
#define ws_error_DeviceError_init_default        {{{NULL}, NULL}, 0, {ws_i2c_AddressSpace_init_default}}
#define ws_error_ComponentError_init_default     {{{NULL}, NULL}, 0, {{{NULL}, NULL}}}
#define ws_error_ErrorIOBan_init_zero            {0}
#define ws_error_ErrorIOThrottle_init_zero       {0}
#define ws_error_B2D_init_zero                   {{{NULL}, NULL}, 0, {ws_error_BanError_init_zero}}
#define ws_error_D2B_init_zero                   {0, {ws_error_DeviceError_init_zero}}
#define ws_error_BanError_init_zero              {0}
#define ws_error_ThrottleError_init_zero         {0}
#define ws_error_DeviceError_init_zero           {{{NULL}, NULL}, 0, {ws_i2c_AddressSpace_init_zero}}
#define ws_error_ComponentError_init_zero        {{{NULL}, NULL}, 0, {{{NULL}, NULL}}}

/* Field tags (for use in manual encoding/decoding) */
#define ws_error_ErrorIOThrottle_timeout_tag     1
#define ws_error_ThrottleError_timeout_tag       1
#define ws_error_B2D_ban_tag                     1
#define ws_error_B2D_throttle_tag                2
#define ws_error_DeviceError_message_tag         1
#define ws_error_DeviceError_i2c_bus_tag         2
#define ws_error_ComponentError_message_tag      1
#define ws_error_ComponentError_pin_tag          2
#define ws_error_ComponentError_i2c_tag          3
#define ws_error_ComponentError_uart_tag         4
#define ws_error_ComponentError_spi_tag          5
#define ws_error_D2B_device_tag                  1
#define ws_error_D2B_component_tag               2

/* Struct field encoding specification for nanopb */
#define ws_error_ErrorIOBan_FIELDLIST(X, a) \

#define ws_error_ErrorIOBan_CALLBACK NULL
#define ws_error_ErrorIOBan_DEFAULT NULL

#define ws_error_ErrorIOThrottle_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timeout,           1)
#define ws_error_ErrorIOThrottle_CALLBACK NULL
#define ws_error_ErrorIOThrottle_DEFAULT NULL

#define ws_error_B2D_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,ban,payload.ban),   1) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,throttle,payload.throttle),   2)
#define ws_error_B2D_CALLBACK NULL
#define ws_error_B2D_DEFAULT NULL
#define ws_error_B2D_payload_ban_MSGTYPE ws_error_BanError
#define ws_error_B2D_payload_throttle_MSGTYPE ws_error_ThrottleError

#define ws_error_D2B_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,device,payload.device),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,component,payload.component),   2)
#define ws_error_D2B_CALLBACK NULL
#define ws_error_D2B_DEFAULT NULL
#define ws_error_D2B_payload_device_MSGTYPE ws_error_DeviceError
#define ws_error_D2B_payload_component_MSGTYPE ws_error_ComponentError

#define ws_error_BanError_FIELDLIST(X, a) \

#define ws_error_BanError_CALLBACK NULL
#define ws_error_BanError_DEFAULT NULL

#define ws_error_ThrottleError_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timeout,           1)
#define ws_error_ThrottleError_CALLBACK NULL
#define ws_error_ThrottleError_DEFAULT NULL

#define ws_error_DeviceError_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   message,           1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (descriptor,i2c_bus,descriptor.i2c_bus),   2)
#define ws_error_DeviceError_CALLBACK pb_default_field_callback
#define ws_error_DeviceError_DEFAULT NULL
#define ws_error_DeviceError_descriptor_i2c_bus_MSGTYPE ws_i2c_AddressSpace

#define ws_error_ComponentError_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   message,           1) \
X(a, CALLBACK, ONEOF,    STRING,   (descriptor,pin,descriptor.pin),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (descriptor,i2c,descriptor.i2c),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (descriptor,uart,descriptor.uart),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (descriptor,spi,descriptor.spi),   5)
#define ws_error_ComponentError_CALLBACK pb_default_field_callback
#define ws_error_ComponentError_DEFAULT NULL
#define ws_error_ComponentError_descriptor_i2c_MSGTYPE ws_i2c_Descriptor
#define ws_error_ComponentError_descriptor_uart_MSGTYPE ws_uart_Descriptor
#define ws_error_ComponentError_descriptor_spi_MSGTYPE ws_spi_Descriptor

extern const pb_msgdesc_t ws_error_ErrorIOBan_msg;
extern const pb_msgdesc_t ws_error_ErrorIOThrottle_msg;
extern const pb_msgdesc_t ws_error_B2D_msg;
extern const pb_msgdesc_t ws_error_D2B_msg;
extern const pb_msgdesc_t ws_error_BanError_msg;
extern const pb_msgdesc_t ws_error_ThrottleError_msg;
extern const pb_msgdesc_t ws_error_DeviceError_msg;
extern const pb_msgdesc_t ws_error_ComponentError_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ws_error_ErrorIOBan_fields &ws_error_ErrorIOBan_msg
#define ws_error_ErrorIOThrottle_fields &ws_error_ErrorIOThrottle_msg
#define ws_error_B2D_fields &ws_error_B2D_msg
#define ws_error_D2B_fields &ws_error_D2B_msg
#define ws_error_BanError_fields &ws_error_BanError_msg
#define ws_error_ThrottleError_fields &ws_error_ThrottleError_msg
#define ws_error_DeviceError_fields &ws_error_DeviceError_msg
#define ws_error_ComponentError_fields &ws_error_ComponentError_msg

/* Maximum encoded size of messages (where known) */
/* ws_error_D2B_size depends on runtime parameters */
/* ws_error_DeviceError_size depends on runtime parameters */
/* ws_error_ComponentError_size depends on runtime parameters */
#define WS_ERROR_ERROR_PB_H_MAX_SIZE             ws_error_B2D_size
#define ws_error_B2D_size                        8
#define ws_error_BanError_size                   0
#define ws_error_ErrorIOBan_size                 0
#define ws_error_ErrorIOThrottle_size            6
#define ws_error_ThrottleError_size              6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
