/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Wed Apr 22 16:43:09 2026. */

#include "expander.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_expander_B2D, ws_expander_B2D, AUTO)


PB_BIND(ws_expander_D2B, ws_expander_D2B, AUTO)


PB_BIND(ws_expander_Add, ws_expander_Add, AUTO)


PB_BIND(ws_expander_Added, ws_expander_Added, AUTO)


PB_BIND(ws_expander_Remove, ws_expander_Remove, AUTO)


PB_BIND(ws_expander_Removed, ws_expander_Removed, AUTO)



