/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Tue Jun  2 20:59:40 2026. */

#include "expander.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_expander_B2D, ws_expander_B2D, AUTO)


PB_BIND(ws_expander_Add, ws_expander_Add, AUTO)


PB_BIND(ws_expander_Remove, ws_expander_Remove, AUTO)



