/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 at Wed May 27 15:48:49 2026. */

#ifndef PB_WS_EXPANDER_EXPANDER_PB_H_INCLUDED
#define PB_WS_EXPANDER_EXPANDER_PB_H_INCLUDED
#include <pb.h>
#include "i2c.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* *
 Add adds an expander to the hardware. */
typedef struct _ws_expander_Add {
    bool has_cfg_i2c;
    ws_i2c_Add cfg_i2c; /* * I2C configuration for the expander. */
} ws_expander_Add;

/* *
 Remove removes an expander from the hardware. */
typedef struct _ws_expander_Remove {
    bool has_cfg_i2c;
    ws_i2c_Remove cfg_i2c; /* * I2C configuration for the expander to remove. */
} ws_expander_Remove;

/* *
 BrokerToDevice message envelope */
typedef struct _ws_expander_B2D {
    pb_size_t which_payload;
    union {
        ws_expander_Add add;
        ws_expander_Remove remove;
    } payload;
} ws_expander_B2D;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ws_expander_B2D_init_default             {0, {ws_expander_Add_init_default}}
#define ws_expander_Add_init_default             {false, ws_i2c_Add_init_default}
#define ws_expander_Remove_init_default          {false, ws_i2c_Remove_init_default}
#define ws_expander_B2D_init_zero                {0, {ws_expander_Add_init_zero}}
#define ws_expander_Add_init_zero                {false, ws_i2c_Add_init_zero}
#define ws_expander_Remove_init_zero             {false, ws_i2c_Remove_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ws_expander_Add_cfg_i2c_tag              1
#define ws_expander_Remove_cfg_i2c_tag           1
#define ws_expander_B2D_add_tag                  1
#define ws_expander_B2D_remove_tag               2

/* Struct field encoding specification for nanopb */
#define ws_expander_B2D_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,add,payload.add),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,remove,payload.remove),   2)
#define ws_expander_B2D_CALLBACK NULL
#define ws_expander_B2D_DEFAULT NULL
#define ws_expander_B2D_payload_add_MSGTYPE ws_expander_Add
#define ws_expander_B2D_payload_remove_MSGTYPE ws_expander_Remove

#define ws_expander_Add_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cfg_i2c,           1)
#define ws_expander_Add_CALLBACK NULL
#define ws_expander_Add_DEFAULT NULL
#define ws_expander_Add_cfg_i2c_MSGTYPE ws_i2c_Add

#define ws_expander_Remove_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cfg_i2c,           1)
#define ws_expander_Remove_CALLBACK NULL
#define ws_expander_Remove_DEFAULT NULL
#define ws_expander_Remove_cfg_i2c_MSGTYPE ws_i2c_Remove

extern const pb_msgdesc_t ws_expander_B2D_msg;
extern const pb_msgdesc_t ws_expander_Add_msg;
extern const pb_msgdesc_t ws_expander_Remove_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ws_expander_B2D_fields &ws_expander_B2D_msg
#define ws_expander_Add_fields &ws_expander_Add_msg
#define ws_expander_Remove_fields &ws_expander_Remove_msg

/* Maximum encoded size of messages (where known) */
#if defined(ws_i2c_Add_size)
union ws_expander_B2D_payload_size_union {char f1[(12 + ws_i2c_Add_size)]; char f0[38];};
#endif
#if defined(ws_i2c_Add_size)
#define ws_expander_Add_size                     (6 + ws_i2c_Add_size)
#define ws_expander_B2D_size                     (0 + sizeof(union ws_expander_B2D_payload_size_union))
#endif
#define WS_EXPANDER_EXPANDER_PB_H_MAX_SIZE       ws_expander_Remove_size
#define ws_expander_Remove_size                  36

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
