/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 at Wed Apr 22 16:43:09 2026. */

#ifndef PB_WS_EXPANDER_EXPANDER_PB_H_INCLUDED
#define PB_WS_EXPANDER_EXPANDER_PB_H_INCLUDED
#include <pb.h>
#include "i2c.pb.h"
#include "digitalio.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* *
 Add adds an expander to the hardware. */
typedef struct _ws_expander_Add {
    bool has_cfg;
    ws_i2c_DeviceAddOrReplace cfg; /* * I2C configuration for the expander. */
} ws_expander_Add;

/* *
 Added represents a message from the hardware indicating an expander was added. */
typedef struct _ws_expander_Added {
    bool has_response;
    ws_i2c_DeviceAddedOrReplaced response; /* * I2C configuration response. */
} ws_expander_Added;

/* *
 Remove removes an analog pin from the hardware. */
typedef struct _ws_expander_Remove {
    bool has_cfg;
    ws_i2c_DeviceRemove cfg; /* * I2C configuration for the expander to remove. */
} ws_expander_Remove;

/* *
 BrokerToDevice message envelope */
typedef struct _ws_expander_B2D {
    pb_size_t which_payload;
    union {
        ws_expander_Add add;
        ws_expander_Remove remove;
    } payload;
} ws_expander_B2D;

/* *
 Removed represents a message from the device indicating an expander was removed. */
typedef struct _ws_expander_Removed {
    bool has_response;
    ws_i2c_DeviceRemoved response; /* * I2C configuration response. */
} ws_expander_Removed;

/* *
DeviceToBroker message envelope */
typedef struct _ws_expander_D2B {
    pb_size_t which_payload;
    union {
        ws_expander_Added added;
        ws_expander_Removed removed;
    } payload;
} ws_expander_D2B;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ws_expander_B2D_init_default             {0, {ws_expander_Add_init_default}}
#define ws_expander_D2B_init_default             {0, {ws_expander_Added_init_default}}
#define ws_expander_Add_init_default             {false, ws_i2c_DeviceAddOrReplace_init_default}
#define ws_expander_Added_init_default           {false, ws_i2c_DeviceAddedOrReplaced_init_default}
#define ws_expander_Remove_init_default          {false, ws_i2c_DeviceRemove_init_default}
#define ws_expander_Removed_init_default         {false, ws_i2c_DeviceRemoved_init_default}
#define ws_expander_B2D_init_zero                {0, {ws_expander_Add_init_zero}}
#define ws_expander_D2B_init_zero                {0, {ws_expander_Added_init_zero}}
#define ws_expander_Add_init_zero                {false, ws_i2c_DeviceAddOrReplace_init_zero}
#define ws_expander_Added_init_zero              {false, ws_i2c_DeviceAddedOrReplaced_init_zero}
#define ws_expander_Remove_init_zero             {false, ws_i2c_DeviceRemove_init_zero}
#define ws_expander_Removed_init_zero            {false, ws_i2c_DeviceRemoved_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ws_expander_Add_cfg_tag                  1
#define ws_expander_Added_response_tag           1
#define ws_expander_Remove_cfg_tag               1
#define ws_expander_B2D_add_tag                  1
#define ws_expander_B2D_remove_tag               2
#define ws_expander_Removed_response_tag         1
#define ws_expander_D2B_added_tag                1
#define ws_expander_D2B_removed_tag              2

/* Struct field encoding specification for nanopb */
#define ws_expander_B2D_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,add,payload.add),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,remove,payload.remove),   2)
#define ws_expander_B2D_CALLBACK NULL
#define ws_expander_B2D_DEFAULT NULL
#define ws_expander_B2D_payload_add_MSGTYPE ws_expander_Add
#define ws_expander_B2D_payload_remove_MSGTYPE ws_expander_Remove

#define ws_expander_D2B_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,added,payload.added),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,removed,payload.removed),   2)
#define ws_expander_D2B_CALLBACK NULL
#define ws_expander_D2B_DEFAULT NULL
#define ws_expander_D2B_payload_added_MSGTYPE ws_expander_Added
#define ws_expander_D2B_payload_removed_MSGTYPE ws_expander_Removed

#define ws_expander_Add_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cfg,               1)
#define ws_expander_Add_CALLBACK NULL
#define ws_expander_Add_DEFAULT NULL
#define ws_expander_Add_cfg_MSGTYPE ws_i2c_DeviceAddOrReplace

#define ws_expander_Added_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  response,          1)
#define ws_expander_Added_CALLBACK NULL
#define ws_expander_Added_DEFAULT NULL
#define ws_expander_Added_response_MSGTYPE ws_i2c_DeviceAddedOrReplaced

#define ws_expander_Remove_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cfg,               1)
#define ws_expander_Remove_CALLBACK NULL
#define ws_expander_Remove_DEFAULT NULL
#define ws_expander_Remove_cfg_MSGTYPE ws_i2c_DeviceRemove

#define ws_expander_Removed_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  response,          1)
#define ws_expander_Removed_CALLBACK NULL
#define ws_expander_Removed_DEFAULT NULL
#define ws_expander_Removed_response_MSGTYPE ws_i2c_DeviceRemoved

extern const pb_msgdesc_t ws_expander_B2D_msg;
extern const pb_msgdesc_t ws_expander_D2B_msg;
extern const pb_msgdesc_t ws_expander_Add_msg;
extern const pb_msgdesc_t ws_expander_Added_msg;
extern const pb_msgdesc_t ws_expander_Remove_msg;
extern const pb_msgdesc_t ws_expander_Removed_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ws_expander_B2D_fields &ws_expander_B2D_msg
#define ws_expander_D2B_fields &ws_expander_D2B_msg
#define ws_expander_Add_fields &ws_expander_Add_msg
#define ws_expander_Added_fields &ws_expander_Added_msg
#define ws_expander_Remove_fields &ws_expander_Remove_msg
#define ws_expander_Removed_fields &ws_expander_Removed_msg

/* Maximum encoded size of messages (where known) */
#define WS_EXPANDER_EXPANDER_PB_H_MAX_SIZE       ws_expander_B2D_size
#define ws_expander_Add_size                     88
#define ws_expander_Added_size                   38
#define ws_expander_B2D_size                     90
#define ws_expander_D2B_size                     40
#define ws_expander_Remove_size                  34
#define ws_expander_Removed_size                 36

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
