/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Fri Nov 21 15:17:32 2025. */

#include "gps.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_gps_D2B, ws_gps_D2B, 2)


PB_BIND(ws_gps_Config, ws_gps_Config, 2)


PB_BIND(ws_gps_DateTime, ws_gps_DateTime, AUTO)


PB_BIND(ws_gps_RMCResponse, ws_gps_RMCResponse, AUTO)


PB_BIND(ws_gps_GPGGAResponse, ws_gps_GPGGAResponse, AUTO)


PB_BIND(ws_gps_Event, ws_gps_Event, 2)



