/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Wed Nov 12 15:48:51 2025. */

#include "gps.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_gps_GPSD2B, wippersnapper_gps_GPSD2B, 2)


PB_BIND(wippersnapper_gps_GPSConfig, wippersnapper_gps_GPSConfig, 2)


PB_BIND(wippersnapper_gps_GPSDateTime, wippersnapper_gps_GPSDateTime, AUTO)


PB_BIND(wippersnapper_gps_GPSRMCResponse, wippersnapper_gps_GPSRMCResponse, AUTO)


PB_BIND(wippersnapper_gps_GPGGAResponse, wippersnapper_gps_GPGGAResponse, AUTO)


PB_BIND(wippersnapper_gps_GPSEvent, wippersnapper_gps_GPSEvent, 2)



