/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 at Mon May 18 19:55:53 2026. */

#ifndef PB_WS_I2C_I2C_PB_H_INCLUDED
#define PB_WS_I2C_I2C_PB_H_INCLUDED
#include <pb.h>
#include "sensor.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* *
 Represents a separate I2C address space, either a Bus or a Mux.
 - when describing a bus, specify only the scl and sda pins
 - when describing a single mux channel, specify all fields
 - when describing an entire mux (all channels), leave mux_channel blank */
typedef struct _ws_i2c_AddressSpace {
    uint32_t pin_scl; /* * Pin name for the I2C SCL line * */
    uint32_t pin_sda; /* * Pin name for the I2C SDA line * */
    uint32_t mux_address; /* * Optional - I2C multiplexer address. * */
    uint32_t mux_channel; /* * Optional - I2C multiplexer channel, or blank for "all channels" * */
} ws_i2c_AddressSpace;

/* *
 Request an I2C probe of one or more address spaces, optionally narrowing the
 scope of the probe to particular addresses.
 - a v1-style Scan would contain a single AddressSpace and no Address narrowing (scan all 112)
 - a v2-style Probe would contain every AddressSpace and a ist of specific Addresses to probe for */
typedef struct _ws_i2c_Probe {
    pb_callback_t address_spaces; /* * One or more AddressSpaces, with no mux_channels * */
    pb_callback_t addresses; /* * Optional - Specific addresses to probe on each AddressSpace. Empty means "all address". * */
} ws_i2c_Probe;

/* *
 The results of scanning a particular AddressSpace.
 - success with found addresses populates the found_addresses list
 - an error is emitted through the error channel */
typedef struct _ws_i2c_AddressSpaceResult {
    bool has_address_space;
    ws_i2c_AddressSpace address_space; /* * Which AddressSpace was probed * */
    pb_callback_t found_addresses; /* * List of I2C addresses where a device was detected, empty in case of error * */
} ws_i2c_AddressSpaceResult;

/* *
 Response from a Probe request, with results for every AddressSpace that either:
 - found 1 or more addresses
 - had an error
 (Successful probes that did not find anything do not need to be returned.) */
typedef struct _ws_i2c_Probed {
    pb_size_t results_count;
    ws_i2c_AddressSpaceResult results[16]; /* * A success or error result for each AddressSpace probed * */
} ws_i2c_Probed;

/* *
 Descriptor represents a specific device's I2C address within an address space. */
typedef struct _ws_i2c_Descriptor {
    bool has_address_space;
    ws_i2c_AddressSpace address_space; /* * Which address space this device lives in, with mux_channel required. * */
    uint32_t address; /* * Device's i2c address, either on the bus or the mux * */
} ws_i2c_Descriptor;

typedef struct _ws_i2c_Add_TypesEntry {
    uint32_t key;
    ws_sensor_Type value;
} ws_i2c_Add_TypesEntry;

/* *
 Add is a message for initializing (or replacing/updating) an i2c device. */
typedef struct _ws_i2c_Add {
    bool has_descriptor;
    ws_i2c_Descriptor descriptor; /* * The I2c device's address and metadata. */
    /* * The I2c device's name, MUST MATCH the name on the JSON
  definition file on the Wippersnapper_Components repo. */
    char name[16];
    float period; /* * The desired period to update the I2c device's sensor(s), in seconds. */
    pb_size_t types_count;
    ws_i2c_Add_TypesEntry types[16]; /* * SI Types for each sensor on the I2c device. */
} ws_i2c_Add;

/* *
 Remove represents a request to de-init an i2c device. */
typedef struct _ws_i2c_Remove {
    bool has_descriptor;
    ws_i2c_Descriptor descriptor; /* * The I2c device's address and metadata. */
} ws_i2c_Remove;

/* *
 BrokerToDevice message envelope */
typedef struct _ws_i2c_B2D {
    pb_size_t which_payload;
    union {
        ws_i2c_Probe probe;
        ws_i2c_Add add;
        ws_i2c_Remove remove;
    } payload;
} ws_i2c_B2D;

typedef struct _ws_i2c_Event_EventsEntry {
    uint32_t key;
    bool has_value;
    ws_sensor_Event value;
} ws_i2c_Event_EventsEntry;

/* *
 Each Event represents data from **one** I2C device, containing one or more sensors. */
typedef struct _ws_i2c_Event {
    bool has_descriptor;
    ws_i2c_Descriptor descriptor; /* * The I2c device's address and metadata. */
    pb_size_t events_count;
    ws_i2c_Event_EventsEntry events[16]; /* * An event from each of the device's configured sensors. */
} ws_i2c_Event;

/* *
 DeviceToBroker message envelope */
typedef struct _ws_i2c_D2B {
    pb_size_t which_payload;
    union {
        ws_i2c_Probed probed;
        ws_i2c_Event event;
    } payload;
} ws_i2c_D2B;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ws_i2c_B2D_init_default                  {0, {ws_i2c_Probe_init_default}}
#define ws_i2c_D2B_init_default                  {0, {ws_i2c_Probed_init_default}}
#define ws_i2c_AddressSpace_init_default         {0, 0, 0, 0}
#define ws_i2c_Probe_init_default                {{{NULL}, NULL}, {{NULL}, NULL}}
#define ws_i2c_AddressSpaceResult_init_default   {false, ws_i2c_AddressSpace_init_default, {{NULL}, NULL}}
#define ws_i2c_Probed_init_default               {0, {ws_i2c_AddressSpaceResult_init_default, ws_i2c_AddressSpaceResult_init_default, ws_i2c_AddressSpaceResult_init_default, ws_i2c_AddressSpaceResult_init_default, ws_i2c_AddressSpaceResult_init_default, ws_i2c_AddressSpaceResult_init_default, ws_i2c_AddressSpaceResult_init_default, ws_i2c_AddressSpaceResult_init_default, ws_i2c_AddressSpaceResult_init_default, ws_i2c_AddressSpaceResult_init_default, ws_i2c_AddressSpaceResult_init_default, ws_i2c_AddressSpaceResult_init_default, ws_i2c_AddressSpaceResult_init_default, ws_i2c_AddressSpaceResult_init_default, ws_i2c_AddressSpaceResult_init_default, ws_i2c_AddressSpaceResult_init_default}}
#define ws_i2c_Descriptor_init_default           {false, ws_i2c_AddressSpace_init_default, 0}
#define ws_i2c_Add_init_default                  {false, ws_i2c_Descriptor_init_default, "", 0, 0, {ws_i2c_Add_TypesEntry_init_default, ws_i2c_Add_TypesEntry_init_default, ws_i2c_Add_TypesEntry_init_default, ws_i2c_Add_TypesEntry_init_default, ws_i2c_Add_TypesEntry_init_default, ws_i2c_Add_TypesEntry_init_default, ws_i2c_Add_TypesEntry_init_default, ws_i2c_Add_TypesEntry_init_default, ws_i2c_Add_TypesEntry_init_default, ws_i2c_Add_TypesEntry_init_default, ws_i2c_Add_TypesEntry_init_default, ws_i2c_Add_TypesEntry_init_default, ws_i2c_Add_TypesEntry_init_default, ws_i2c_Add_TypesEntry_init_default, ws_i2c_Add_TypesEntry_init_default, ws_i2c_Add_TypesEntry_init_default}}
#define ws_i2c_Add_TypesEntry_init_default       {0, _ws_sensor_Type_MIN}
#define ws_i2c_Remove_init_default               {false, ws_i2c_Descriptor_init_default}
#define ws_i2c_Event_init_default                {false, ws_i2c_Descriptor_init_default, 0, {ws_i2c_Event_EventsEntry_init_default, ws_i2c_Event_EventsEntry_init_default, ws_i2c_Event_EventsEntry_init_default, ws_i2c_Event_EventsEntry_init_default, ws_i2c_Event_EventsEntry_init_default, ws_i2c_Event_EventsEntry_init_default, ws_i2c_Event_EventsEntry_init_default, ws_i2c_Event_EventsEntry_init_default, ws_i2c_Event_EventsEntry_init_default, ws_i2c_Event_EventsEntry_init_default, ws_i2c_Event_EventsEntry_init_default, ws_i2c_Event_EventsEntry_init_default, ws_i2c_Event_EventsEntry_init_default, ws_i2c_Event_EventsEntry_init_default, ws_i2c_Event_EventsEntry_init_default, ws_i2c_Event_EventsEntry_init_default}}
#define ws_i2c_Event_EventsEntry_init_default    {0, false, ws_sensor_Event_init_default}
#define ws_i2c_B2D_init_zero                     {0, {ws_i2c_Probe_init_zero}}
#define ws_i2c_D2B_init_zero                     {0, {ws_i2c_Probed_init_zero}}
#define ws_i2c_AddressSpace_init_zero            {0, 0, 0, 0}
#define ws_i2c_Probe_init_zero                   {{{NULL}, NULL}, {{NULL}, NULL}}
#define ws_i2c_AddressSpaceResult_init_zero      {false, ws_i2c_AddressSpace_init_zero, {{NULL}, NULL}}
#define ws_i2c_Probed_init_zero                  {0, {ws_i2c_AddressSpaceResult_init_zero, ws_i2c_AddressSpaceResult_init_zero, ws_i2c_AddressSpaceResult_init_zero, ws_i2c_AddressSpaceResult_init_zero, ws_i2c_AddressSpaceResult_init_zero, ws_i2c_AddressSpaceResult_init_zero, ws_i2c_AddressSpaceResult_init_zero, ws_i2c_AddressSpaceResult_init_zero, ws_i2c_AddressSpaceResult_init_zero, ws_i2c_AddressSpaceResult_init_zero, ws_i2c_AddressSpaceResult_init_zero, ws_i2c_AddressSpaceResult_init_zero, ws_i2c_AddressSpaceResult_init_zero, ws_i2c_AddressSpaceResult_init_zero, ws_i2c_AddressSpaceResult_init_zero, ws_i2c_AddressSpaceResult_init_zero}}
#define ws_i2c_Descriptor_init_zero              {false, ws_i2c_AddressSpace_init_zero, 0}
#define ws_i2c_Add_init_zero                     {false, ws_i2c_Descriptor_init_zero, "", 0, 0, {ws_i2c_Add_TypesEntry_init_zero, ws_i2c_Add_TypesEntry_init_zero, ws_i2c_Add_TypesEntry_init_zero, ws_i2c_Add_TypesEntry_init_zero, ws_i2c_Add_TypesEntry_init_zero, ws_i2c_Add_TypesEntry_init_zero, ws_i2c_Add_TypesEntry_init_zero, ws_i2c_Add_TypesEntry_init_zero, ws_i2c_Add_TypesEntry_init_zero, ws_i2c_Add_TypesEntry_init_zero, ws_i2c_Add_TypesEntry_init_zero, ws_i2c_Add_TypesEntry_init_zero, ws_i2c_Add_TypesEntry_init_zero, ws_i2c_Add_TypesEntry_init_zero, ws_i2c_Add_TypesEntry_init_zero, ws_i2c_Add_TypesEntry_init_zero}}
#define ws_i2c_Add_TypesEntry_init_zero          {0, _ws_sensor_Type_MIN}
#define ws_i2c_Remove_init_zero                  {false, ws_i2c_Descriptor_init_zero}
#define ws_i2c_Event_init_zero                   {false, ws_i2c_Descriptor_init_zero, 0, {ws_i2c_Event_EventsEntry_init_zero, ws_i2c_Event_EventsEntry_init_zero, ws_i2c_Event_EventsEntry_init_zero, ws_i2c_Event_EventsEntry_init_zero, ws_i2c_Event_EventsEntry_init_zero, ws_i2c_Event_EventsEntry_init_zero, ws_i2c_Event_EventsEntry_init_zero, ws_i2c_Event_EventsEntry_init_zero, ws_i2c_Event_EventsEntry_init_zero, ws_i2c_Event_EventsEntry_init_zero, ws_i2c_Event_EventsEntry_init_zero, ws_i2c_Event_EventsEntry_init_zero, ws_i2c_Event_EventsEntry_init_zero, ws_i2c_Event_EventsEntry_init_zero, ws_i2c_Event_EventsEntry_init_zero, ws_i2c_Event_EventsEntry_init_zero}}
#define ws_i2c_Event_EventsEntry_init_zero       {0, false, ws_sensor_Event_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ws_i2c_AddressSpace_pin_scl_tag          1
#define ws_i2c_AddressSpace_pin_sda_tag          2
#define ws_i2c_AddressSpace_mux_address_tag      3
#define ws_i2c_AddressSpace_mux_channel_tag      4
#define ws_i2c_Probe_address_spaces_tag          1
#define ws_i2c_Probe_addresses_tag               2
#define ws_i2c_AddressSpaceResult_address_space_tag 1
#define ws_i2c_AddressSpaceResult_found_addresses_tag 2
#define ws_i2c_Probed_results_tag                1
#define ws_i2c_Descriptor_address_space_tag      1
#define ws_i2c_Descriptor_address_tag            2
#define ws_i2c_Add_TypesEntry_key_tag            1
#define ws_i2c_Add_TypesEntry_value_tag          2
#define ws_i2c_Add_descriptor_tag                1
#define ws_i2c_Add_name_tag                      2
#define ws_i2c_Add_period_tag                    3
#define ws_i2c_Add_types_tag                     4
#define ws_i2c_Remove_descriptor_tag             1
#define ws_i2c_B2D_probe_tag                     1
#define ws_i2c_B2D_add_tag                       2
#define ws_i2c_B2D_remove_tag                    3
#define ws_i2c_Event_EventsEntry_key_tag         1
#define ws_i2c_Event_EventsEntry_value_tag       2
#define ws_i2c_Event_descriptor_tag              1
#define ws_i2c_Event_events_tag                  2
#define ws_i2c_D2B_probed_tag                    1
#define ws_i2c_D2B_event_tag                     2

/* Struct field encoding specification for nanopb */
#define ws_i2c_B2D_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,probe,payload.probe),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,add,payload.add),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,remove,payload.remove),   3)
#define ws_i2c_B2D_CALLBACK NULL
#define ws_i2c_B2D_DEFAULT NULL
#define ws_i2c_B2D_payload_probe_MSGTYPE ws_i2c_Probe
#define ws_i2c_B2D_payload_add_MSGTYPE ws_i2c_Add
#define ws_i2c_B2D_payload_remove_MSGTYPE ws_i2c_Remove

#define ws_i2c_D2B_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,probed,payload.probed),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,event,payload.event),   2)
#define ws_i2c_D2B_CALLBACK NULL
#define ws_i2c_D2B_DEFAULT NULL
#define ws_i2c_D2B_payload_probed_MSGTYPE ws_i2c_Probed
#define ws_i2c_D2B_payload_event_MSGTYPE ws_i2c_Event

#define ws_i2c_AddressSpace_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pin_scl,           1) \
X(a, STATIC,   SINGULAR, UINT32,   pin_sda,           2) \
X(a, STATIC,   SINGULAR, UINT32,   mux_address,       3) \
X(a, STATIC,   SINGULAR, UINT32,   mux_channel,       4)
#define ws_i2c_AddressSpace_CALLBACK NULL
#define ws_i2c_AddressSpace_DEFAULT NULL

#define ws_i2c_Probe_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  address_spaces,    1) \
X(a, CALLBACK, REPEATED, UINT32,   addresses,         2)
#define ws_i2c_Probe_CALLBACK pb_default_field_callback
#define ws_i2c_Probe_DEFAULT NULL
#define ws_i2c_Probe_address_spaces_MSGTYPE ws_i2c_AddressSpace

#define ws_i2c_AddressSpaceResult_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  address_space,     1) \
X(a, CALLBACK, REPEATED, UINT32,   found_addresses,   2)
#define ws_i2c_AddressSpaceResult_CALLBACK pb_default_field_callback
#define ws_i2c_AddressSpaceResult_DEFAULT NULL
#define ws_i2c_AddressSpaceResult_address_space_MSGTYPE ws_i2c_AddressSpace

#define ws_i2c_Probed_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  results,           1)
#define ws_i2c_Probed_CALLBACK NULL
#define ws_i2c_Probed_DEFAULT NULL
#define ws_i2c_Probed_results_MSGTYPE ws_i2c_AddressSpaceResult

#define ws_i2c_Descriptor_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  address_space,     1) \
X(a, STATIC,   SINGULAR, UINT32,   address,           2)
#define ws_i2c_Descriptor_CALLBACK NULL
#define ws_i2c_Descriptor_DEFAULT NULL
#define ws_i2c_Descriptor_address_space_MSGTYPE ws_i2c_AddressSpace

#define ws_i2c_Add_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  descriptor,        1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, FLOAT,    period,            3) \
X(a, STATIC,   REPEATED, MESSAGE,  types,             4)
#define ws_i2c_Add_CALLBACK NULL
#define ws_i2c_Add_DEFAULT NULL
#define ws_i2c_Add_descriptor_MSGTYPE ws_i2c_Descriptor
#define ws_i2c_Add_types_MSGTYPE ws_i2c_Add_TypesEntry

#define ws_i2c_Add_TypesEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key,               1) \
X(a, STATIC,   SINGULAR, UENUM,    value,             2)
#define ws_i2c_Add_TypesEntry_CALLBACK NULL
#define ws_i2c_Add_TypesEntry_DEFAULT NULL

#define ws_i2c_Remove_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  descriptor,        1)
#define ws_i2c_Remove_CALLBACK NULL
#define ws_i2c_Remove_DEFAULT NULL
#define ws_i2c_Remove_descriptor_MSGTYPE ws_i2c_Descriptor

#define ws_i2c_Event_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  descriptor,        1) \
X(a, STATIC,   REPEATED, MESSAGE,  events,            2)
#define ws_i2c_Event_CALLBACK NULL
#define ws_i2c_Event_DEFAULT NULL
#define ws_i2c_Event_descriptor_MSGTYPE ws_i2c_Descriptor
#define ws_i2c_Event_events_MSGTYPE ws_i2c_Event_EventsEntry

#define ws_i2c_Event_EventsEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define ws_i2c_Event_EventsEntry_CALLBACK NULL
#define ws_i2c_Event_EventsEntry_DEFAULT NULL
#define ws_i2c_Event_EventsEntry_value_MSGTYPE ws_sensor_Event

extern const pb_msgdesc_t ws_i2c_B2D_msg;
extern const pb_msgdesc_t ws_i2c_D2B_msg;
extern const pb_msgdesc_t ws_i2c_AddressSpace_msg;
extern const pb_msgdesc_t ws_i2c_Probe_msg;
extern const pb_msgdesc_t ws_i2c_AddressSpaceResult_msg;
extern const pb_msgdesc_t ws_i2c_Probed_msg;
extern const pb_msgdesc_t ws_i2c_Descriptor_msg;
extern const pb_msgdesc_t ws_i2c_Add_msg;
extern const pb_msgdesc_t ws_i2c_Add_TypesEntry_msg;
extern const pb_msgdesc_t ws_i2c_Remove_msg;
extern const pb_msgdesc_t ws_i2c_Event_msg;
extern const pb_msgdesc_t ws_i2c_Event_EventsEntry_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ws_i2c_B2D_fields &ws_i2c_B2D_msg
#define ws_i2c_D2B_fields &ws_i2c_D2B_msg
#define ws_i2c_AddressSpace_fields &ws_i2c_AddressSpace_msg
#define ws_i2c_Probe_fields &ws_i2c_Probe_msg
#define ws_i2c_AddressSpaceResult_fields &ws_i2c_AddressSpaceResult_msg
#define ws_i2c_Probed_fields &ws_i2c_Probed_msg
#define ws_i2c_Descriptor_fields &ws_i2c_Descriptor_msg
#define ws_i2c_Add_fields &ws_i2c_Add_msg
#define ws_i2c_Add_TypesEntry_fields &ws_i2c_Add_TypesEntry_msg
#define ws_i2c_Remove_fields &ws_i2c_Remove_msg
#define ws_i2c_Event_fields &ws_i2c_Event_msg
#define ws_i2c_Event_EventsEntry_fields &ws_i2c_Event_EventsEntry_msg

/* Maximum encoded size of messages (where known) */
/* ws_i2c_B2D_size depends on runtime parameters */
/* ws_i2c_D2B_size depends on runtime parameters */
/* ws_i2c_Probe_size depends on runtime parameters */
/* ws_i2c_AddressSpaceResult_size depends on runtime parameters */
/* ws_i2c_Probed_size depends on runtime parameters */
#define ws_i2c_Add_TypesEntry_size               8
#define ws_i2c_Add_size                          216
#define ws_i2c_AddressSpace_size                 24
#define ws_i2c_Descriptor_size                   32
#define ws_i2c_Remove_size                       34
#if defined(ws_sensor_Event_size)
#define WS_I2C_I2C_PB_H_MAX_SIZE                 ws_i2c_Event_size
#define ws_i2c_Event_EventsEntry_size            (12 + ws_sensor_Event_size)
#define ws_i2c_Event_size                        (322 + 16*ws_sensor_Event_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
