/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Thu Feb 26 21:17:42 2026. */

#include "i2c.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_i2c_B2D, ws_i2c_B2D, 2)


PB_BIND(ws_i2c_D2B, ws_i2c_D2B, 4)


PB_BIND(ws_i2c_DeviceDescriptor, ws_i2c_DeviceDescriptor, AUTO)


PB_BIND(ws_i2c_BusDescriptor, ws_i2c_BusDescriptor, AUTO)


PB_BIND(ws_i2c_BusScan, ws_i2c_BusScan, AUTO)


PB_BIND(ws_i2c_BusScanned, ws_i2c_BusScanned, 4)


PB_BIND(ws_i2c_DeviceAddOrReplace, ws_i2c_DeviceAddOrReplace, 2)


PB_BIND(ws_i2c_DeviceAddedOrReplaced, ws_i2c_DeviceAddedOrReplaced, AUTO)


PB_BIND(ws_i2c_DeviceRemove, ws_i2c_DeviceRemove, AUTO)


PB_BIND(ws_i2c_DeviceRemoved, ws_i2c_DeviceRemoved, AUTO)


PB_BIND(ws_i2c_DeviceEvent, ws_i2c_DeviceEvent, 2)


PB_BIND(ws_i2c_DeviceOutputWrite, ws_i2c_DeviceOutputWrite, 2)





