/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 at Wed Mar 18 15:14:21 2026. */

#ifndef PB_WS_I2C_I2C_PB_H_INCLUDED
#define PB_WS_I2C_I2C_PB_H_INCLUDED
#include <pb.h>
#include "gps.pb.h"
#include "sensor.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* *
 BusStatus represents the status of a board's I2C bus */
typedef enum _ws_i2c_BusStatus {
    ws_i2c_BusStatus_BS_UNSPECIFIED = 0, /* * Unspecified error occurred. * */
    ws_i2c_BusStatus_BS_SUCCESS = 1, /* * I2C bus successfully initialized. * */
    ws_i2c_BusStatus_BS_ERROR_HANG = 2, /* * I2C Bus hang, user should reset their board if this persists. * */
    ws_i2c_BusStatus_BS_ERROR_PULLUPS = 3, /* * I2C bus failed to initialize - SDA or SCL needs a pull up. * */
    ws_i2c_BusStatus_BS_ERROR_WIRING = 4, /* * I2C bus failed to communicate - Please check your wiring. * */
    ws_i2c_BusStatus_BS_ERROR_INVALID_CHANNEL = 5 /* * I2C MUX failed - Output channel must be within range 0-7. * */
} ws_i2c_BusStatus;

/* *
 DeviceStatus represents the state of an I2C device/peripheral */
typedef enum _ws_i2c_DeviceStatus {
    ws_i2c_DeviceStatus_DS_UNSPECIFIED = 0, /* * Unspecified error occurred. * */
    ws_i2c_DeviceStatus_DS_SUCCESS = 1, /* * I2C device successfully initialized. * */
    ws_i2c_DeviceStatus_DS_FAIL_INIT = 2, /* * I2C device failed to initialize. * */
    ws_i2c_DeviceStatus_DS_FAIL_DEINIT = 3, /* * I2C device failed to deinitialize. * */
    ws_i2c_DeviceStatus_DS_FAIL_UNSUPPORTED_SENSOR = 4, /* * WipperSnapper version is outdated and does not include this device. * */
    ws_i2c_DeviceStatus_DS_NOT_FOUND = 5 /* * I2C device not found on the bus. * */
} ws_i2c_DeviceStatus;

/* Struct definitions */
/* *
 DeviceDescriptor represents the I2c device's address and related metadata. */
typedef struct _ws_i2c_DeviceDescriptor {
    uint32_t pin_scl; /* * Pin name for the I2C SCL line * */
    uint32_t pin_sda; /* * Pin name for the I2C SDA line * */
    uint32_t device_address; /* * Device's i2c address, either on the bus or the mux * */
    uint32_t mux_address; /* * Optional - I2C multiplexer address. * */
    uint32_t mux_channel; /* * Optional - I2C multiplexer channel. * */
} ws_i2c_DeviceDescriptor;

/* *
 Scan represents a command for a device to perform an i2c scan. */
typedef struct _ws_i2c_Scan {
    uint32_t pin_scl; /* * Pin name for the I2C SCL line * */
    uint32_t pin_sda; /* * Pin name for the I2C SDA line * */
    uint32_t mux_address; /* * Optional - I2C multiplexer address to scan. * */
} ws_i2c_Scan;

/* *
 Scanned represents a list of I2c addresses on a bus and optionally a mux,
 found after Scan has executed. */
typedef struct _ws_i2c_Scanned {
    pb_size_t found_devices_count;
    ws_i2c_DeviceDescriptor found_devices[16]; /* * List of the I2c device addresses found, with bus and mux info. */
    ws_i2c_BusStatus bus_status; /* * The I2c bus' status, in case of bus error. * */
} ws_i2c_Scanned;

/* *
 DeviceAddOrReplace is a message for initializing (or replacing/updating) an i2c device. */
typedef struct _ws_i2c_DeviceAddOrReplace {
    bool has_device_description;
    ws_i2c_DeviceDescriptor device_description; /* * The I2c device's address and metadata. */
    char device_name[16]; /* * The I2c device's name, MUST MATCH the name on the JSON definition file on
https://github.com/adafruit/Wippersnapper_Components. */
    float device_period; /* * The desired period to update the I2c device's sensor(s), in seconds. */
    pb_size_t device_sensor_types_count;
    ws_sensor_Type device_sensor_types[16]; /* * SI Types for each sensor on the I2c device. */
    bool has_gps_config;
    ws_gps_Config gps_config; /* * Optional - If the I2C device is a GPS driver, fill this field with the GPS config. * */
} ws_i2c_DeviceAddOrReplace;

/* *
 DeviceAddedOrReplaced contains the response from a device after processing a DeviceAddOrReplace message. */
typedef struct _ws_i2c_DeviceAddedOrReplaced {
    bool has_device_description;
    ws_i2c_DeviceDescriptor device_description; /* * The I2c device's address and metadata, unless there was an error. * */
    ws_i2c_BusStatus bus_status; /* * The I2c bus' status, in case of bus error. * */
    ws_i2c_DeviceStatus device_status; /* * The I2c device's status, in case of device error. * */
} ws_i2c_DeviceAddedOrReplaced;

/* *
 DeviceRemove represents a request to de-init an i2c device. */
typedef struct _ws_i2c_DeviceRemove {
    bool has_device_description;
    ws_i2c_DeviceDescriptor device_description; /* * The I2c device's address and metadata. */
} ws_i2c_DeviceRemove;

/* *
 BrokerToDevice message envelope */
typedef struct _ws_i2c_B2D {
    pb_size_t which_payload;
    union {
        ws_i2c_Scan bus_scan;
        ws_i2c_DeviceAddOrReplace device_add_replace;
        ws_i2c_DeviceRemove device_remove;
    } payload;
} ws_i2c_B2D;

/* *
 DeviceRemoved represents a response to a I2cDeviceRemove message. */
typedef struct _ws_i2c_DeviceRemoved {
    bool has_device_description;
    ws_i2c_DeviceDescriptor device_description; /* * The I2c device's address and metadata. */
    bool did_remove; /* * True if the I2C device was successfully removed from the controller, False otherwise. * */
} ws_i2c_DeviceRemoved;

/* *
 Each DeviceEvent represents data from **one** I2C device, containing one or more sensors. */
typedef struct _ws_i2c_DeviceEvent {
    bool has_device_description;
    ws_i2c_DeviceDescriptor device_description; /* * The I2c device's address and metadata. */
    pb_size_t device_events_count;
    ws_sensor_Event device_events[16]; /* * An event from each of the device's configured sensors. */
} ws_i2c_DeviceEvent;

/* *
 DeviceToBroker message envelope */
typedef struct _ws_i2c_D2B {
    pb_size_t which_payload;
    union {
        ws_i2c_Scanned bus_scanned;
        ws_i2c_DeviceAddedOrReplaced device_added_replaced;
        ws_i2c_DeviceRemoved device_removed;
        ws_i2c_DeviceEvent device_event;
    } payload;
} ws_i2c_D2B;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ws_i2c_BusStatus_MIN ws_i2c_BusStatus_BS_UNSPECIFIED
#define _ws_i2c_BusStatus_MAX ws_i2c_BusStatus_BS_ERROR_INVALID_CHANNEL
#define _ws_i2c_BusStatus_ARRAYSIZE ((ws_i2c_BusStatus)(ws_i2c_BusStatus_BS_ERROR_INVALID_CHANNEL+1))

#define _ws_i2c_DeviceStatus_MIN ws_i2c_DeviceStatus_DS_UNSPECIFIED
#define _ws_i2c_DeviceStatus_MAX ws_i2c_DeviceStatus_DS_NOT_FOUND
#define _ws_i2c_DeviceStatus_ARRAYSIZE ((ws_i2c_DeviceStatus)(ws_i2c_DeviceStatus_DS_NOT_FOUND+1))





#define ws_i2c_Scanned_bus_status_ENUMTYPE ws_i2c_BusStatus

#define ws_i2c_DeviceAddOrReplace_device_sensor_types_ENUMTYPE ws_sensor_Type

#define ws_i2c_DeviceAddedOrReplaced_bus_status_ENUMTYPE ws_i2c_BusStatus
#define ws_i2c_DeviceAddedOrReplaced_device_status_ENUMTYPE ws_i2c_DeviceStatus





/* Initializer values for message structs */
#define ws_i2c_B2D_init_default                  {0, {ws_i2c_Scan_init_default}}
#define ws_i2c_D2B_init_default                  {0, {ws_i2c_Scanned_init_default}}
#define ws_i2c_DeviceDescriptor_init_default     {0, 0, 0, 0, 0}
#define ws_i2c_Scan_init_default                 {0, 0, 0}
#define ws_i2c_Scanned_init_default              {0, {ws_i2c_DeviceDescriptor_init_default, ws_i2c_DeviceDescriptor_init_default, ws_i2c_DeviceDescriptor_init_default, ws_i2c_DeviceDescriptor_init_default, ws_i2c_DeviceDescriptor_init_default, ws_i2c_DeviceDescriptor_init_default, ws_i2c_DeviceDescriptor_init_default, ws_i2c_DeviceDescriptor_init_default, ws_i2c_DeviceDescriptor_init_default, ws_i2c_DeviceDescriptor_init_default, ws_i2c_DeviceDescriptor_init_default, ws_i2c_DeviceDescriptor_init_default, ws_i2c_DeviceDescriptor_init_default, ws_i2c_DeviceDescriptor_init_default, ws_i2c_DeviceDescriptor_init_default, ws_i2c_DeviceDescriptor_init_default}, _ws_i2c_BusStatus_MIN}
#define ws_i2c_DeviceAddOrReplace_init_default   {false, ws_i2c_DeviceDescriptor_init_default, "", 0, 0, {_ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN}, false, ws_gps_Config_init_default}
#define ws_i2c_DeviceAddedOrReplaced_init_default {false, ws_i2c_DeviceDescriptor_init_default, _ws_i2c_BusStatus_MIN, _ws_i2c_DeviceStatus_MIN}
#define ws_i2c_DeviceRemove_init_default         {false, ws_i2c_DeviceDescriptor_init_default}
#define ws_i2c_DeviceRemoved_init_default        {false, ws_i2c_DeviceDescriptor_init_default, 0}
#define ws_i2c_DeviceEvent_init_default          {false, ws_i2c_DeviceDescriptor_init_default, 0, {ws_sensor_Event_init_default, ws_sensor_Event_init_default, ws_sensor_Event_init_default, ws_sensor_Event_init_default, ws_sensor_Event_init_default, ws_sensor_Event_init_default, ws_sensor_Event_init_default, ws_sensor_Event_init_default, ws_sensor_Event_init_default, ws_sensor_Event_init_default, ws_sensor_Event_init_default, ws_sensor_Event_init_default, ws_sensor_Event_init_default, ws_sensor_Event_init_default, ws_sensor_Event_init_default, ws_sensor_Event_init_default}}
#define ws_i2c_B2D_init_zero                     {0, {ws_i2c_Scan_init_zero}}
#define ws_i2c_D2B_init_zero                     {0, {ws_i2c_Scanned_init_zero}}
#define ws_i2c_DeviceDescriptor_init_zero        {0, 0, 0, 0, 0}
#define ws_i2c_Scan_init_zero                    {0, 0, 0}
#define ws_i2c_Scanned_init_zero                 {0, {ws_i2c_DeviceDescriptor_init_zero, ws_i2c_DeviceDescriptor_init_zero, ws_i2c_DeviceDescriptor_init_zero, ws_i2c_DeviceDescriptor_init_zero, ws_i2c_DeviceDescriptor_init_zero, ws_i2c_DeviceDescriptor_init_zero, ws_i2c_DeviceDescriptor_init_zero, ws_i2c_DeviceDescriptor_init_zero, ws_i2c_DeviceDescriptor_init_zero, ws_i2c_DeviceDescriptor_init_zero, ws_i2c_DeviceDescriptor_init_zero, ws_i2c_DeviceDescriptor_init_zero, ws_i2c_DeviceDescriptor_init_zero, ws_i2c_DeviceDescriptor_init_zero, ws_i2c_DeviceDescriptor_init_zero, ws_i2c_DeviceDescriptor_init_zero}, _ws_i2c_BusStatus_MIN}
#define ws_i2c_DeviceAddOrReplace_init_zero      {false, ws_i2c_DeviceDescriptor_init_zero, "", 0, 0, {_ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN, _ws_sensor_Type_MIN}, false, ws_gps_Config_init_zero}
#define ws_i2c_DeviceAddedOrReplaced_init_zero   {false, ws_i2c_DeviceDescriptor_init_zero, _ws_i2c_BusStatus_MIN, _ws_i2c_DeviceStatus_MIN}
#define ws_i2c_DeviceRemove_init_zero            {false, ws_i2c_DeviceDescriptor_init_zero}
#define ws_i2c_DeviceRemoved_init_zero           {false, ws_i2c_DeviceDescriptor_init_zero, 0}
#define ws_i2c_DeviceEvent_init_zero             {false, ws_i2c_DeviceDescriptor_init_zero, 0, {ws_sensor_Event_init_zero, ws_sensor_Event_init_zero, ws_sensor_Event_init_zero, ws_sensor_Event_init_zero, ws_sensor_Event_init_zero, ws_sensor_Event_init_zero, ws_sensor_Event_init_zero, ws_sensor_Event_init_zero, ws_sensor_Event_init_zero, ws_sensor_Event_init_zero, ws_sensor_Event_init_zero, ws_sensor_Event_init_zero, ws_sensor_Event_init_zero, ws_sensor_Event_init_zero, ws_sensor_Event_init_zero, ws_sensor_Event_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define ws_i2c_DeviceDescriptor_pin_scl_tag      1
#define ws_i2c_DeviceDescriptor_pin_sda_tag      2
#define ws_i2c_DeviceDescriptor_device_address_tag 3
#define ws_i2c_DeviceDescriptor_mux_address_tag  4
#define ws_i2c_DeviceDescriptor_mux_channel_tag  5
#define ws_i2c_Scan_pin_scl_tag                  1
#define ws_i2c_Scan_pin_sda_tag                  2
#define ws_i2c_Scan_mux_address_tag              3
#define ws_i2c_Scanned_found_devices_tag         1
#define ws_i2c_Scanned_bus_status_tag            2
#define ws_i2c_DeviceAddOrReplace_device_description_tag 1
#define ws_i2c_DeviceAddOrReplace_device_name_tag 2
#define ws_i2c_DeviceAddOrReplace_device_period_tag 3
#define ws_i2c_DeviceAddOrReplace_device_sensor_types_tag 4
#define ws_i2c_DeviceAddOrReplace_gps_config_tag 5
#define ws_i2c_DeviceAddedOrReplaced_device_description_tag 1
#define ws_i2c_DeviceAddedOrReplaced_bus_status_tag 2
#define ws_i2c_DeviceAddedOrReplaced_device_status_tag 3
#define ws_i2c_DeviceRemove_device_description_tag 1
#define ws_i2c_B2D_bus_scan_tag                  1
#define ws_i2c_B2D_device_add_replace_tag        2
#define ws_i2c_B2D_device_remove_tag             3
#define ws_i2c_DeviceRemoved_device_description_tag 1
#define ws_i2c_DeviceRemoved_did_remove_tag      2
#define ws_i2c_DeviceEvent_device_description_tag 1
#define ws_i2c_DeviceEvent_device_events_tag     2
#define ws_i2c_D2B_bus_scanned_tag               1
#define ws_i2c_D2B_device_added_replaced_tag     2
#define ws_i2c_D2B_device_removed_tag            3
#define ws_i2c_D2B_device_event_tag              4

/* Struct field encoding specification for nanopb */
#define ws_i2c_B2D_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,bus_scan,payload.bus_scan),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,device_add_replace,payload.device_add_replace),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,device_remove,payload.device_remove),   3)
#define ws_i2c_B2D_CALLBACK NULL
#define ws_i2c_B2D_DEFAULT NULL
#define ws_i2c_B2D_payload_bus_scan_MSGTYPE ws_i2c_Scan
#define ws_i2c_B2D_payload_device_add_replace_MSGTYPE ws_i2c_DeviceAddOrReplace
#define ws_i2c_B2D_payload_device_remove_MSGTYPE ws_i2c_DeviceRemove

#define ws_i2c_D2B_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,bus_scanned,payload.bus_scanned),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,device_added_replaced,payload.device_added_replaced),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,device_removed,payload.device_removed),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,device_event,payload.device_event),   4)
#define ws_i2c_D2B_CALLBACK NULL
#define ws_i2c_D2B_DEFAULT NULL
#define ws_i2c_D2B_payload_bus_scanned_MSGTYPE ws_i2c_Scanned
#define ws_i2c_D2B_payload_device_added_replaced_MSGTYPE ws_i2c_DeviceAddedOrReplaced
#define ws_i2c_D2B_payload_device_removed_MSGTYPE ws_i2c_DeviceRemoved
#define ws_i2c_D2B_payload_device_event_MSGTYPE ws_i2c_DeviceEvent

#define ws_i2c_DeviceDescriptor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pin_scl,           1) \
X(a, STATIC,   SINGULAR, UINT32,   pin_sda,           2) \
X(a, STATIC,   SINGULAR, UINT32,   device_address,    3) \
X(a, STATIC,   SINGULAR, UINT32,   mux_address,       4) \
X(a, STATIC,   SINGULAR, UINT32,   mux_channel,       5)
#define ws_i2c_DeviceDescriptor_CALLBACK NULL
#define ws_i2c_DeviceDescriptor_DEFAULT NULL

#define ws_i2c_Scan_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pin_scl,           1) \
X(a, STATIC,   SINGULAR, UINT32,   pin_sda,           2) \
X(a, STATIC,   SINGULAR, UINT32,   mux_address,       3)
#define ws_i2c_Scan_CALLBACK NULL
#define ws_i2c_Scan_DEFAULT NULL

#define ws_i2c_Scanned_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  found_devices,     1) \
X(a, STATIC,   SINGULAR, UENUM,    bus_status,        2)
#define ws_i2c_Scanned_CALLBACK NULL
#define ws_i2c_Scanned_DEFAULT NULL
#define ws_i2c_Scanned_found_devices_MSGTYPE ws_i2c_DeviceDescriptor

#define ws_i2c_DeviceAddOrReplace_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_description,   1) \
X(a, STATIC,   SINGULAR, STRING,   device_name,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    device_period,     3) \
X(a, STATIC,   REPEATED, UENUM,    device_sensor_types,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gps_config,        5)
#define ws_i2c_DeviceAddOrReplace_CALLBACK NULL
#define ws_i2c_DeviceAddOrReplace_DEFAULT NULL
#define ws_i2c_DeviceAddOrReplace_device_description_MSGTYPE ws_i2c_DeviceDescriptor
#define ws_i2c_DeviceAddOrReplace_gps_config_MSGTYPE ws_gps_Config

#define ws_i2c_DeviceAddedOrReplaced_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_description,   1) \
X(a, STATIC,   SINGULAR, UENUM,    bus_status,        2) \
X(a, STATIC,   SINGULAR, UENUM,    device_status,     3)
#define ws_i2c_DeviceAddedOrReplaced_CALLBACK NULL
#define ws_i2c_DeviceAddedOrReplaced_DEFAULT NULL
#define ws_i2c_DeviceAddedOrReplaced_device_description_MSGTYPE ws_i2c_DeviceDescriptor

#define ws_i2c_DeviceRemove_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_description,   1)
#define ws_i2c_DeviceRemove_CALLBACK NULL
#define ws_i2c_DeviceRemove_DEFAULT NULL
#define ws_i2c_DeviceRemove_device_description_MSGTYPE ws_i2c_DeviceDescriptor

#define ws_i2c_DeviceRemoved_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_description,   1) \
X(a, STATIC,   SINGULAR, BOOL,     did_remove,        2)
#define ws_i2c_DeviceRemoved_CALLBACK NULL
#define ws_i2c_DeviceRemoved_DEFAULT NULL
#define ws_i2c_DeviceRemoved_device_description_MSGTYPE ws_i2c_DeviceDescriptor

#define ws_i2c_DeviceEvent_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_description,   1) \
X(a, STATIC,   REPEATED, MESSAGE,  device_events,     2)
#define ws_i2c_DeviceEvent_CALLBACK NULL
#define ws_i2c_DeviceEvent_DEFAULT NULL
#define ws_i2c_DeviceEvent_device_description_MSGTYPE ws_i2c_DeviceDescriptor
#define ws_i2c_DeviceEvent_device_events_MSGTYPE ws_sensor_Event

extern const pb_msgdesc_t ws_i2c_B2D_msg;
extern const pb_msgdesc_t ws_i2c_D2B_msg;
extern const pb_msgdesc_t ws_i2c_DeviceDescriptor_msg;
extern const pb_msgdesc_t ws_i2c_Scan_msg;
extern const pb_msgdesc_t ws_i2c_Scanned_msg;
extern const pb_msgdesc_t ws_i2c_DeviceAddOrReplace_msg;
extern const pb_msgdesc_t ws_i2c_DeviceAddedOrReplaced_msg;
extern const pb_msgdesc_t ws_i2c_DeviceRemove_msg;
extern const pb_msgdesc_t ws_i2c_DeviceRemoved_msg;
extern const pb_msgdesc_t ws_i2c_DeviceEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ws_i2c_B2D_fields &ws_i2c_B2D_msg
#define ws_i2c_D2B_fields &ws_i2c_D2B_msg
#define ws_i2c_DeviceDescriptor_fields &ws_i2c_DeviceDescriptor_msg
#define ws_i2c_Scan_fields &ws_i2c_Scan_msg
#define ws_i2c_Scanned_fields &ws_i2c_Scanned_msg
#define ws_i2c_DeviceAddOrReplace_fields &ws_i2c_DeviceAddOrReplace_msg
#define ws_i2c_DeviceAddedOrReplaced_fields &ws_i2c_DeviceAddedOrReplaced_msg
#define ws_i2c_DeviceRemove_fields &ws_i2c_DeviceRemove_msg
#define ws_i2c_DeviceRemoved_fields &ws_i2c_DeviceRemoved_msg
#define ws_i2c_DeviceEvent_fields &ws_i2c_DeviceEvent_msg

/* Maximum encoded size of messages (where known) */
#if defined(ws_sensor_Event_size)
union ws_i2c_D2B_payload_size_union {char f4[(134 + 16*ws_sensor_Event_size)]; char f0[517];};
#endif
#define WS_I2C_I2C_PB_H_MAX_SIZE                 ws_i2c_B2D_size
#define ws_i2c_B2D_size                          1879
#define ws_i2c_DeviceAddOrReplace_size           1876
#define ws_i2c_DeviceAddedOrReplaced_size        36
#define ws_i2c_DeviceDescriptor_size             30
#define ws_i2c_DeviceRemove_size                 32
#define ws_i2c_DeviceRemoved_size                34
#define ws_i2c_Scan_size                         18
#define ws_i2c_Scanned_size                      514
#if defined(ws_sensor_Event_size)
#define ws_i2c_D2B_size                          (0 + sizeof(union ws_i2c_D2B_payload_size_union))
#define ws_i2c_DeviceEvent_size                  (128 + 16*ws_sensor_Event_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
