/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Wed Apr 22 19:54:40 2026. */

#include "i2c.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_i2c_B2D, ws_i2c_B2D, AUTO)


PB_BIND(ws_i2c_D2B, ws_i2c_D2B, 2)


PB_BIND(ws_i2c_DeviceDescriptor, ws_i2c_DeviceDescriptor, AUTO)


PB_BIND(ws_i2c_Scan, ws_i2c_Scan, AUTO)


PB_BIND(ws_i2c_Scanned, ws_i2c_Scanned, 2)


PB_BIND(ws_i2c_DeviceAddOrReplace, ws_i2c_DeviceAddOrReplace, AUTO)


PB_BIND(ws_i2c_DeviceAddedOrReplaced, ws_i2c_DeviceAddedOrReplaced, AUTO)


PB_BIND(ws_i2c_DeviceRemove, ws_i2c_DeviceRemove, AUTO)


PB_BIND(ws_i2c_DeviceRemoved, ws_i2c_DeviceRemoved, AUTO)


PB_BIND(ws_i2c_DeviceEvent, ws_i2c_DeviceEvent, 2)





