/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "i2c_output.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_i2c_output_LedBackpackConfig, wippersnapper_i2c_output_LedBackpackConfig, AUTO)


PB_BIND(wippersnapper_i2c_output_CharLCDConfig, wippersnapper_i2c_output_CharLCDConfig, AUTO)


PB_BIND(wippersnapper_i2c_output_I2cOutputAdd, wippersnapper_i2c_output_I2cOutputAdd, AUTO)


PB_BIND(wippersnapper_i2c_output_LedBackpackWrite, wippersnapper_i2c_output_LedBackpackWrite, AUTO)


PB_BIND(wippersnapper_i2c_output_CharLCDWrite, wippersnapper_i2c_output_CharLCDWrite, AUTO)





