/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Fri Nov 21 15:17:32 2025. */

#include "i2c_output.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_i2c_output_LedBackpackConfig, ws_i2c_output_LedBackpackConfig, AUTO)


PB_BIND(ws_i2c_output_CharLCDConfig, ws_i2c_output_CharLCDConfig, AUTO)


PB_BIND(ws_i2c_output_OledConfig, ws_i2c_output_OledConfig, AUTO)


PB_BIND(ws_i2c_output_Add, ws_i2c_output_Add, AUTO)


PB_BIND(ws_i2c_output_LedBackpackWrite, ws_i2c_output_LedBackpackWrite, AUTO)


PB_BIND(ws_i2c_output_CharLCDWrite, ws_i2c_output_CharLCDWrite, AUTO)


PB_BIND(ws_i2c_output_OLEDWrite, ws_i2c_output_OLEDWrite, 2)





