/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Mon Dec 29 19:28:37 2025. */

#include "pixels.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_pixels_B2D, ws_pixels_B2D, AUTO)


PB_BIND(ws_pixels_D2B, ws_pixels_D2B, AUTO)


PB_BIND(ws_pixels_Add, ws_pixels_Add, AUTO)


PB_BIND(ws_pixels_Added, ws_pixels_Added, AUTO)


PB_BIND(ws_pixels_Remove, ws_pixels_Remove, AUTO)


PB_BIND(ws_pixels_Write, ws_pixels_Write, AUTO)





