/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Wed Nov 12 15:48:51 2025. */

#include "sensor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_sensor_SensorEvent, wippersnapper_sensor_SensorEvent, AUTO)


PB_BIND(wippersnapper_sensor_SensorEvent_SensorEventColor, wippersnapper_sensor_SensorEvent_SensorEventColor, AUTO)


PB_BIND(wippersnapper_sensor_SensorEvent_SensorEvent3DVector, wippersnapper_sensor_SensorEvent_SensorEvent3DVector, AUTO)


PB_BIND(wippersnapper_sensor_SensorEvent_SensorEventOrientation, wippersnapper_sensor_SensorEvent_SensorEventOrientation, AUTO)




