/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Wed May 20 15:18:06 2026. */

#include "servo.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_servo_B2D, ws_servo_B2D, AUTO)


PB_BIND(ws_servo_Add, ws_servo_Add, AUTO)


PB_BIND(ws_servo_Remove, ws_servo_Remove, AUTO)


PB_BIND(ws_servo_Write, ws_servo_Write, AUTO)



