/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 at Mon Dec 29 19:28:37 2025. */

#ifndef PB_WS_SIGNAL_SIGNAL_PB_H_INCLUDED
#define PB_WS_SIGNAL_SIGNAL_PB_H_INCLUDED
#include <pb.h>
#include "error.pb.h"
#include "checkin.pb.h"
#include "analogio.pb.h"
#include "digitalio.pb.h"
#include "ds18x20.pb.h"
#include "i2c.pb.h"
#include "pixels.pb.h"
#include "pwm.pb.h"
#include "servo.pb.h"
#include "sleep.pb.h"
#include "uart.pb.h"
#include "gps.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* BrokerToDevice
 The BrokerToDevice message is sent from the broker to the device.
 It contains a oneof payload, which is a union of all the possible
 message-types that can be sent from the broker to a device. */
typedef struct _ws_signal_BrokerToDevice {
    pb_callback_t cb_payload;
    pb_size_t which_payload;
    union {
        /* System Events */
        ws_error_ErrorB2D error;
        /* Device Interactions */
        ws_checkin_B2D checkin;
        ws_sleep_B2D sleep;
        /* Component Interactions */
        ws_digitalio_B2D digitalio;
        ws_analogio_B2D analogio;
        ws_servo_B2D servo;
        ws_pwm_B2D pwm;
        ws_pixels_B2D pixels;
        ws_ds18x20_B2D ds18x20;
        ws_uart_B2D uart;
        ws_i2c_B2D i2c;
    } payload;
} ws_signal_BrokerToDevice;

/* DeviceToBroker
 The DeviceToBroker message is sent from the device to the broker.
 It contains a oneof payload, which is a union of all the possible
 message-types that can be sent from a device to the broker. */
typedef struct _ws_signal_DeviceToBroker {
    pb_callback_t cb_payload;
    pb_size_t which_payload;
    union {
        /* System Events */
        ws_error_ErrorD2B error;
        /* Device Interactions */
        ws_checkin_D2B checkin;
        ws_sleep_D2B sleep;
        /* Component Interactions */
        ws_digitalio_D2B digitalio;
        ws_analogio_D2B analogio;
        ws_servo_D2B servo;
        ws_pwm_D2B pwm;
        ws_pixels_D2B pixels;
        ws_ds18x20_D2B ds18x20;
        ws_uart_D2B uart;
        ws_i2c_D2B i2c;
        ws_gps_D2B gps;
    } payload;
} ws_signal_DeviceToBroker;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ws_signal_BrokerToDevice_init_default    {{{NULL}, NULL}, 0, {ws_error_ErrorB2D_init_default}}
#define ws_signal_DeviceToBroker_init_default    {{{NULL}, NULL}, 0, {ws_error_ErrorD2B_init_default}}
#define ws_signal_BrokerToDevice_init_zero       {{{NULL}, NULL}, 0, {ws_error_ErrorB2D_init_zero}}
#define ws_signal_DeviceToBroker_init_zero       {{{NULL}, NULL}, 0, {ws_error_ErrorD2B_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define ws_signal_BrokerToDevice_error_tag       10
#define ws_signal_BrokerToDevice_checkin_tag     20
#define ws_signal_BrokerToDevice_sleep_tag       21
#define ws_signal_BrokerToDevice_digitalio_tag   30
#define ws_signal_BrokerToDevice_analogio_tag    31
#define ws_signal_BrokerToDevice_servo_tag       32
#define ws_signal_BrokerToDevice_pwm_tag         33
#define ws_signal_BrokerToDevice_pixels_tag      34
#define ws_signal_BrokerToDevice_ds18x20_tag     35
#define ws_signal_BrokerToDevice_uart_tag        36
#define ws_signal_BrokerToDevice_i2c_tag         37
#define ws_signal_DeviceToBroker_error_tag       10
#define ws_signal_DeviceToBroker_checkin_tag     20
#define ws_signal_DeviceToBroker_sleep_tag       21
#define ws_signal_DeviceToBroker_digitalio_tag   30
#define ws_signal_DeviceToBroker_analogio_tag    31
#define ws_signal_DeviceToBroker_servo_tag       32
#define ws_signal_DeviceToBroker_pwm_tag         33
#define ws_signal_DeviceToBroker_pixels_tag      34
#define ws_signal_DeviceToBroker_ds18x20_tag     35
#define ws_signal_DeviceToBroker_uart_tag        36
#define ws_signal_DeviceToBroker_i2c_tag         37
#define ws_signal_DeviceToBroker_gps_tag         38

/* Struct field encoding specification for nanopb */
#define ws_signal_BrokerToDevice_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,error,payload.error),  10) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,checkin,payload.checkin),  20) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,sleep,payload.sleep),  21) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,digitalio,payload.digitalio),  30) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,analogio,payload.analogio),  31) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,servo,payload.servo),  32) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,pwm,payload.pwm),  33) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,pixels,payload.pixels),  34) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,ds18x20,payload.ds18x20),  35) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,uart,payload.uart),  36) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,i2c,payload.i2c),  37)
#define ws_signal_BrokerToDevice_CALLBACK NULL
#define ws_signal_BrokerToDevice_DEFAULT NULL
#define ws_signal_BrokerToDevice_payload_error_MSGTYPE ws_error_ErrorB2D
#define ws_signal_BrokerToDevice_payload_checkin_MSGTYPE ws_checkin_B2D
#define ws_signal_BrokerToDevice_payload_sleep_MSGTYPE ws_sleep_B2D
#define ws_signal_BrokerToDevice_payload_digitalio_MSGTYPE ws_digitalio_B2D
#define ws_signal_BrokerToDevice_payload_analogio_MSGTYPE ws_analogio_B2D
#define ws_signal_BrokerToDevice_payload_servo_MSGTYPE ws_servo_B2D
#define ws_signal_BrokerToDevice_payload_pwm_MSGTYPE ws_pwm_B2D
#define ws_signal_BrokerToDevice_payload_pixels_MSGTYPE ws_pixels_B2D
#define ws_signal_BrokerToDevice_payload_ds18x20_MSGTYPE ws_ds18x20_B2D
#define ws_signal_BrokerToDevice_payload_uart_MSGTYPE ws_uart_B2D
#define ws_signal_BrokerToDevice_payload_i2c_MSGTYPE ws_i2c_B2D

#define ws_signal_DeviceToBroker_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,error,payload.error),  10) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,checkin,payload.checkin),  20) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,sleep,payload.sleep),  21) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,digitalio,payload.digitalio),  30) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,analogio,payload.analogio),  31) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,servo,payload.servo),  32) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,pwm,payload.pwm),  33) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,pixels,payload.pixels),  34) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,ds18x20,payload.ds18x20),  35) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,uart,payload.uart),  36) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,i2c,payload.i2c),  37) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,gps,payload.gps),  38)
#define ws_signal_DeviceToBroker_CALLBACK NULL
#define ws_signal_DeviceToBroker_DEFAULT NULL
#define ws_signal_DeviceToBroker_payload_error_MSGTYPE ws_error_ErrorD2B
#define ws_signal_DeviceToBroker_payload_checkin_MSGTYPE ws_checkin_D2B
#define ws_signal_DeviceToBroker_payload_sleep_MSGTYPE ws_sleep_D2B
#define ws_signal_DeviceToBroker_payload_digitalio_MSGTYPE ws_digitalio_D2B
#define ws_signal_DeviceToBroker_payload_analogio_MSGTYPE ws_analogio_D2B
#define ws_signal_DeviceToBroker_payload_servo_MSGTYPE ws_servo_D2B
#define ws_signal_DeviceToBroker_payload_pwm_MSGTYPE ws_pwm_D2B
#define ws_signal_DeviceToBroker_payload_pixels_MSGTYPE ws_pixels_D2B
#define ws_signal_DeviceToBroker_payload_ds18x20_MSGTYPE ws_ds18x20_D2B
#define ws_signal_DeviceToBroker_payload_uart_MSGTYPE ws_uart_D2B
#define ws_signal_DeviceToBroker_payload_i2c_MSGTYPE ws_i2c_D2B
#define ws_signal_DeviceToBroker_payload_gps_MSGTYPE ws_gps_D2B

extern const pb_msgdesc_t ws_signal_BrokerToDevice_msg;
extern const pb_msgdesc_t ws_signal_DeviceToBroker_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ws_signal_BrokerToDevice_fields &ws_signal_BrokerToDevice_msg
#define ws_signal_DeviceToBroker_fields &ws_signal_DeviceToBroker_msg

/* Maximum encoded size of messages (where known) */
#if defined(ws_checkin_B2D_size) && defined(ws_digitalio_B2D_size) && defined(ws_uart_B2D_size)
union ws_signal_BrokerToDevice_payload_size_union {char f20[(7 + ws_checkin_B2D_size)]; char f30[(7 + ws_digitalio_B2D_size)]; char f36[(7 + ws_uart_B2D_size)]; char f0[1924];};
#endif
#if defined(ws_error_ErrorD2B_size) && defined(ws_sleep_D2B_size) && defined(ws_digitalio_D2B_size) && defined(ws_analogio_D2B_size) && defined(ws_ds18x20_D2B_size) && defined(ws_uart_D2B_size) && defined(ws_i2c_D2B_size)
union ws_signal_DeviceToBroker_payload_size_union {char f10[(6 + ws_error_ErrorD2B_size)]; char f21[(7 + ws_sleep_D2B_size)]; char f30[(7 + ws_digitalio_D2B_size)]; char f31[(7 + ws_analogio_D2B_size)]; char f35[(7 + ws_ds18x20_D2B_size)]; char f36[(7 + ws_uart_D2B_size)]; char f37[(7 + ws_i2c_D2B_size)]; char f0[3137];};
#endif
#if defined(ws_checkin_B2D_size) && defined(ws_digitalio_B2D_size) && defined(ws_uart_B2D_size)
#define WS_SIGNAL_SIGNAL_PB_H_MAX_SIZE           ws_signal_BrokerToDevice_size
#define ws_signal_BrokerToDevice_size            (0 + sizeof(union ws_signal_BrokerToDevice_payload_size_union))
#endif
#if defined(ws_error_ErrorD2B_size) && defined(ws_sleep_D2B_size) && defined(ws_digitalio_D2B_size) && defined(ws_analogio_D2B_size) && defined(ws_ds18x20_D2B_size) && defined(ws_uart_D2B_size) && defined(ws_i2c_D2B_size)
#define ws_signal_DeviceToBroker_size            (0 + sizeof(union ws_signal_DeviceToBroker_payload_size_union))
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
