/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Thu Feb 26 21:17:42 2026. */

#include "sleep.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_sleep_B2D, ws_sleep_B2D, AUTO)


PB_BIND(ws_sleep_D2B, ws_sleep_D2B, AUTO)


PB_BIND(ws_sleep_Goodnight, ws_sleep_Goodnight, AUTO)


PB_BIND(ws_sleep_Wake, ws_sleep_Wake, AUTO)


PB_BIND(ws_sleep_TimerConfig, ws_sleep_TimerConfig, AUTO)


PB_BIND(ws_sleep_Ext0Config, ws_sleep_Ext0Config, AUTO)


PB_BIND(ws_sleep_Enter, ws_sleep_Enter, AUTO)





