/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Wed Apr 22 19:54:40 2026. */

#include "spi.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_spi_Config, ws_spi_Config, AUTO)



