/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Fri May 29 18:45:30 2026. */

#include "uart.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ws_uart_B2D, ws_uart_B2D, AUTO)


PB_BIND(ws_uart_D2B, ws_uart_D2B, 2)


PB_BIND(ws_uart_SerialConfig, ws_uart_SerialConfig, AUTO)


PB_BIND(ws_uart_GenericInputConfig, ws_uart_GenericInputConfig, AUTO)


PB_BIND(ws_uart_TrinamicDynamixelConfig, ws_uart_TrinamicDynamixelConfig, AUTO)


PB_BIND(ws_uart_PM25AQIConfig, ws_uart_PM25AQIConfig, AUTO)


PB_BIND(ws_uart_DeviceConfig, ws_uart_DeviceConfig, AUTO)


PB_BIND(ws_uart_Descriptor, ws_uart_Descriptor, AUTO)


PB_BIND(ws_uart_Add, ws_uart_Add, AUTO)


PB_BIND(ws_uart_Remove, ws_uart_Remove, AUTO)


PB_BIND(ws_uart_Write, ws_uart_Write, AUTO)


PB_BIND(ws_uart_Event, ws_uart_Event, 2)





