/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.2 */

#ifndef PB_WIPPERSNAPPER_DESCRIPTION_V1_DESCRIPTION_PB_H_INCLUDED
#define PB_WIPPERSNAPPER_DESCRIPTION_V1_DESCRIPTION_PB_H_INCLUDED
#include <pb.h>
#include "nanopb/nanopb.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* *
 Response. Specifies if the hardware definiton is within the database. */
typedef enum _wippersnapper_description_v1_CreateDescriptionResponse_Response {
    wippersnapper_description_v1_CreateDescriptionResponse_Response_RESPONSE_UNSPECIFIED = 0, /* * Invalid response from server */
    wippersnapper_description_v1_CreateDescriptionResponse_Response_RESPONSE_OK = 1, /* * Board found within definition index */
    wippersnapper_description_v1_CreateDescriptionResponse_Response_RESPONSE_BOARD_NOT_FOUND = 2 /* * Board not found in definition index */
} wippersnapper_description_v1_CreateDescriptionResponse_Response;

/* Struct definitions */
/* *
 CreateDescriptionRequest identifies a device with Adafruit.io WipperSnapper. */
typedef struct _wippersnapper_description_v1_CreateDescriptionRequest {
    char machine_name[64]; /* * Identifies client's physical hardware */
    int32_t mac_addr; /* * Client's UID, last 3 bytes of MAC address */
    int32_t usb_vid; /* * Optional, USB Vendor ID */
    int32_t usb_pid; /* * Optional, USB Product ID */
    char str_version[20]; /* * Library version, as a string */
} wippersnapper_description_v1_CreateDescriptionRequest;

typedef struct _wippersnapper_description_v1_CreateDescriptionRequest_Version {
    char dummy_field;
} wippersnapper_description_v1_CreateDescriptionRequest_Version;

/* *
 CreateDescriptionResponse represents a device's specifications. */
typedef struct _wippersnapper_description_v1_CreateDescriptionResponse {
    wippersnapper_description_v1_CreateDescriptionResponse_Response response; /* * Specifies if the hardware definition exists on the server. */
    int32_t total_gpio_pins; /* * Specifies the number of GPIO pins on the client's physical hardware. */
    int32_t total_analog_pins; /* * Specifies the number of analog pins on the client's physical hardware. */
    float reference_voltage; /* * Specifies the hardware's default reference voltage. */
    int32_t total_i2c_ports; /* * Specifies the number of hardware's I2C ports (i2cPorts[]). */
} wippersnapper_description_v1_CreateDescriptionResponse;

/* *
 RegistrationComplete Specifies if the device finished configuring
 its components and is ready for configuration messages. */
typedef struct _wippersnapper_description_v1_RegistrationComplete {
    bool is_complete; /* * True if device successfully configured its components, False otherwise. */
} wippersnapper_description_v1_RegistrationComplete;

/* Request the board definition JSON from a device
 MQTT Topic: `device/ID/description/get` */
typedef struct _wippersnapper_description_v1_GetDefinitionRequest {
    char dummy_field;
} wippersnapper_description_v1_GetDefinitionRequest;

/* Response from Adafruit IO with the JSON board definition as a string
 MQTT Topic: `device/ID/description/get` */
typedef struct _wippersnapper_description_v1_GetDefinitionResponse {
    char dummy_field;
} wippersnapper_description_v1_GetDefinitionResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _wippersnapper_description_v1_CreateDescriptionResponse_Response_MIN wippersnapper_description_v1_CreateDescriptionResponse_Response_RESPONSE_UNSPECIFIED
#define _wippersnapper_description_v1_CreateDescriptionResponse_Response_MAX wippersnapper_description_v1_CreateDescriptionResponse_Response_RESPONSE_BOARD_NOT_FOUND
#define _wippersnapper_description_v1_CreateDescriptionResponse_Response_ARRAYSIZE ((wippersnapper_description_v1_CreateDescriptionResponse_Response)(wippersnapper_description_v1_CreateDescriptionResponse_Response_RESPONSE_BOARD_NOT_FOUND+1))



#define wippersnapper_description_v1_CreateDescriptionResponse_response_ENUMTYPE wippersnapper_description_v1_CreateDescriptionResponse_Response





/* Initializer values for message structs */
#define wippersnapper_description_v1_CreateDescriptionRequest_init_default {"", 0, 0, 0, ""}
#define wippersnapper_description_v1_CreateDescriptionRequest_Version_init_default {0}
#define wippersnapper_description_v1_CreateDescriptionResponse_init_default {_wippersnapper_description_v1_CreateDescriptionResponse_Response_MIN, 0, 0, 0, 0}
#define wippersnapper_description_v1_RegistrationComplete_init_default {0}
#define wippersnapper_description_v1_GetDefinitionRequest_init_default {0}
#define wippersnapper_description_v1_GetDefinitionResponse_init_default {0}
#define wippersnapper_description_v1_CreateDescriptionRequest_init_zero {"", 0, 0, 0, ""}
#define wippersnapper_description_v1_CreateDescriptionRequest_Version_init_zero {0}
#define wippersnapper_description_v1_CreateDescriptionResponse_init_zero {_wippersnapper_description_v1_CreateDescriptionResponse_Response_MIN, 0, 0, 0, 0}
#define wippersnapper_description_v1_RegistrationComplete_init_zero {0}
#define wippersnapper_description_v1_GetDefinitionRequest_init_zero {0}
#define wippersnapper_description_v1_GetDefinitionResponse_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define wippersnapper_description_v1_CreateDescriptionRequest_machine_name_tag 1
#define wippersnapper_description_v1_CreateDescriptionRequest_mac_addr_tag 2
#define wippersnapper_description_v1_CreateDescriptionRequest_usb_vid_tag 3
#define wippersnapper_description_v1_CreateDescriptionRequest_usb_pid_tag 4
#define wippersnapper_description_v1_CreateDescriptionRequest_str_version_tag 15
#define wippersnapper_description_v1_CreateDescriptionResponse_response_tag 1
#define wippersnapper_description_v1_CreateDescriptionResponse_total_gpio_pins_tag 2
#define wippersnapper_description_v1_CreateDescriptionResponse_total_analog_pins_tag 3
#define wippersnapper_description_v1_CreateDescriptionResponse_reference_voltage_tag 4
#define wippersnapper_description_v1_CreateDescriptionResponse_total_i2c_ports_tag 5
#define wippersnapper_description_v1_RegistrationComplete_is_complete_tag 1

/* Struct field encoding specification for nanopb */
#define wippersnapper_description_v1_CreateDescriptionRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   machine_name,      1) \
X(a, STATIC,   SINGULAR, INT32,    mac_addr,          2) \
X(a, STATIC,   SINGULAR, INT32,    usb_vid,           3) \
X(a, STATIC,   SINGULAR, INT32,    usb_pid,           4) \
X(a, STATIC,   SINGULAR, STRING,   str_version,      15)
#define wippersnapper_description_v1_CreateDescriptionRequest_CALLBACK NULL
#define wippersnapper_description_v1_CreateDescriptionRequest_DEFAULT NULL

#define wippersnapper_description_v1_CreateDescriptionRequest_Version_FIELDLIST(X, a) \

#define wippersnapper_description_v1_CreateDescriptionRequest_Version_CALLBACK NULL
#define wippersnapper_description_v1_CreateDescriptionRequest_Version_DEFAULT NULL

#define wippersnapper_description_v1_CreateDescriptionResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    response,          1) \
X(a, STATIC,   SINGULAR, INT32,    total_gpio_pins,   2) \
X(a, STATIC,   SINGULAR, INT32,    total_analog_pins,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    reference_voltage,   4) \
X(a, STATIC,   SINGULAR, INT32,    total_i2c_ports,   5)
#define wippersnapper_description_v1_CreateDescriptionResponse_CALLBACK NULL
#define wippersnapper_description_v1_CreateDescriptionResponse_DEFAULT NULL

#define wippersnapper_description_v1_RegistrationComplete_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     is_complete,       1)
#define wippersnapper_description_v1_RegistrationComplete_CALLBACK NULL
#define wippersnapper_description_v1_RegistrationComplete_DEFAULT NULL

#define wippersnapper_description_v1_GetDefinitionRequest_FIELDLIST(X, a) \

#define wippersnapper_description_v1_GetDefinitionRequest_CALLBACK NULL
#define wippersnapper_description_v1_GetDefinitionRequest_DEFAULT NULL

#define wippersnapper_description_v1_GetDefinitionResponse_FIELDLIST(X, a) \

#define wippersnapper_description_v1_GetDefinitionResponse_CALLBACK NULL
#define wippersnapper_description_v1_GetDefinitionResponse_DEFAULT NULL

extern const pb_msgdesc_t wippersnapper_description_v1_CreateDescriptionRequest_msg;
extern const pb_msgdesc_t wippersnapper_description_v1_CreateDescriptionRequest_Version_msg;
extern const pb_msgdesc_t wippersnapper_description_v1_CreateDescriptionResponse_msg;
extern const pb_msgdesc_t wippersnapper_description_v1_RegistrationComplete_msg;
extern const pb_msgdesc_t wippersnapper_description_v1_GetDefinitionRequest_msg;
extern const pb_msgdesc_t wippersnapper_description_v1_GetDefinitionResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define wippersnapper_description_v1_CreateDescriptionRequest_fields &wippersnapper_description_v1_CreateDescriptionRequest_msg
#define wippersnapper_description_v1_CreateDescriptionRequest_Version_fields &wippersnapper_description_v1_CreateDescriptionRequest_Version_msg
#define wippersnapper_description_v1_CreateDescriptionResponse_fields &wippersnapper_description_v1_CreateDescriptionResponse_msg
#define wippersnapper_description_v1_RegistrationComplete_fields &wippersnapper_description_v1_RegistrationComplete_msg
#define wippersnapper_description_v1_GetDefinitionRequest_fields &wippersnapper_description_v1_GetDefinitionRequest_msg
#define wippersnapper_description_v1_GetDefinitionResponse_fields &wippersnapper_description_v1_GetDefinitionResponse_msg

/* Maximum encoded size of messages (where known) */
#define WIPPERSNAPPER_DESCRIPTION_V1_DESCRIPTION_PB_H_MAX_SIZE wippersnapper_description_v1_CreateDescriptionRequest_size
#define wippersnapper_description_v1_CreateDescriptionRequest_Version_size 0
#define wippersnapper_description_v1_CreateDescriptionRequest_size 119
#define wippersnapper_description_v1_CreateDescriptionResponse_size 40
#define wippersnapper_description_v1_GetDefinitionRequest_size 0
#define wippersnapper_description_v1_GetDefinitionResponse_size 0
#define wippersnapper_description_v1_RegistrationComplete_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
