name: Arduino Library CI

on: [pull_request, repository_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arduino-platform: ["esp8266", "esp32", "funhouse",
                           "pyportal_tinyusb", "metro_m4_airliftlite_tinyusb"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
         repository: brentru/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    # manually install Adafruit WiFiNINA library fork
    - name: extra libraries
      run: |
        git clone --quiet https://github.com/adafruit/WiFiNINA.git /home/runner/Arduino/libraries/WiFiNINA

    - name: test platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }} --export-binaries


  clang_and_doxy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: clang
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -e "./src/wippersnapper/*" -e "./src/nanopb/*" -e "./src/pb.h" -r .

    # - name: doxygen
    #   env:
    #     GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
    #     PRETTYNAME : "Adafruit Wippersnapper Arduino Library"
    #   run: bash ci/doxy_gen_and_deploy.sh

