# SPDX-FileCopyrightText: Brent Rubell for Adafruit Industries, 2022
#
# SPDX-License-Identifier: MIT
name: WipperSnapper Release Callee

on:
  workflow_call:

jobs:
  release-wippersnapper:
    name: Release WipperSnapper
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts from build-platform steps
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: List Files
        run: ls
      - name: Upload Assets to the GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
                  build-files/wippersnapper.*.uf2
                  build-files/wippersnapper.*.bin
                  build-files/wippersnapper.*.zip
