# SPDX-FileCopyrightText: Brent Rubell for Adafruit Industries, 2022-2024
#
# SPDX-License-Identifier: MIT
name: WipperSnapper Release Callee

on:
  workflow_call:

jobs:
  release-wippersnapper:
    name: Release WipperSnapper
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts from build-platform steps
        uses: actions/download-artifact@v2
        with:
          name: build-files
      - name: List Files
        run: ls
      - name: Upload Assets to the GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
                  wippersnapper.*.uf2
                  wippersnapper.*.bin
                  wippersnapper.*.zip
