# SPDX-FileCopyrightText: Brent Rubell for Adafruit Industries, 2024-2025
#
# SPDX-License-Identifier: MIT
name: WipperSnapper Tests for Offline Mode
on:
    release:
      types: [published]
      secrets:
        GH_REPO_TOKEN:
          required: true
permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
      - name: Install Wokwi CI server
        uses: wokwi/wokwi-ci-server-action@v1
      - name: Install Wokwi CLI
        run: curl -L https://wokwi.com/ci/install.sh | sh
      - name: Install platformIO libraries
        run: pio lib install
      - name: Build PlatformIO examples
        run: pio ci --board=esp32dev
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
      - name: Test on Wokwi
        run: pytest tests/${{ matrix.test }}.py --junitxml=report.xml -v
        env:
          WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            /home/runner/work/Adafruit_Wippersnapper_Arduino/Adafruit_Wippersnapper_Arduino/report.xml