/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev at Fri Jul 16 14:44:19 2021. */

#include "wippersnapper/location/v1/location.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_location_v1_GetLocationRequest, wippersnapper_location_v1_GetLocationRequest, AUTO)


PB_BIND(wippersnapper_location_v1_GetLocationResponse, wippersnapper_location_v1_GetLocationResponse, AUTO)



